//! (generated by module split — pure refactor, behavior identical)
#![allow(unused_imports)]

use std::collections::BTreeMap;
use std::path::PathBuf;
use std::process::Stdio;
use std::sync::Arc;

use anyhow::Result;
use axum::{
    Json, Router,
    extract::{Path as AxPath, State},
    http::StatusCode,
    response::{Html, IntoResponse},
    routing::{delete, get, post},
};
use rtrt_core::{
    OutputStyleLevel, read_output_style_level, read_output_style_level_for,
    write_output_style_level_for,
};
use rtrt_memory::{
    ClusterIndex, ConceptHierarchy, DetailedRecord, Embedder, MemoryStore, PayloadFilter,
    Summariser,
};
use rtrt_providers::{
    ChatMessage, ChatRequest, ChatResponse, Gateway, MetricsView, Prefer, Provider, RequestMetric,
    Role, RouteAlternative, RouteRequest, UsageSnapshot, select_route,
};
use rtrt_security::{Profile, ScanReport};
use rtrt_templates::{Prompt, PromptRegistry};
use serde::{Deserialize, Serialize};
use tokio::io::AsyncWriteExt;
use tokio::sync::Mutex;
use tokio::sync::broadcast;

use crate::prelude::*;

pub(crate) async fn index() -> Html<&'static str> {
    Html(INDEX_HTML)
}

/// Serve the vendored graph libraries (Cytoscape + cola/fcose layout deps) from
/// the binary itself, so the memory map renders WITHOUT any CDN / internet — a
/// blocked CDN was making the map fall back to a plain list.
pub(crate) async fn vendor_asset(
    axum::extract::Path(file): axum::extract::Path<String>,
) -> std::result::Result<([(axum::http::HeaderName, &'static str); 2], &'static str), StatusCode> {
    let body = match file.as_str() {
        "cytoscape.min.js" => VENDOR_CYTOSCAPE,
        "layout-base.js" => VENDOR_LAYOUT_BASE,
        "cose-base.js" => VENDOR_COSE_BASE,
        "cytoscape-fcose.js" => VENDOR_FCOSE,
        "cola.min.js" => VENDOR_COLA,
        "cytoscape-cola.js" => VENDOR_CYTO_COLA,
        _ => return Err(StatusCode::NOT_FOUND),
    };
    Ok((
        [
            (
                axum::http::header::CONTENT_TYPE,
                "application/javascript; charset=utf-8",
            ),
            (axum::http::header::CACHE_CONTROL, "public, max-age=86400"),
        ],
        body,
    ))
}

/// Serve a front-end asset (split out of index.html) with an explicit
/// Content-Type. Embedded via include_str! so the binary stays self-contained.
pub(crate) fn asset_response(
    body: &'static str,
    content_type: &'static str,
) -> ([(axum::http::HeaderName, &'static str); 1], &'static str) {
    ([(axum::http::header::CONTENT_TYPE, content_type)], body)
}

pub(crate) async fn asset_styles_css() -> ([(axum::http::HeaderName, &'static str); 1], &'static str)
{
    asset_response(ASSET_STYLES_CSS, "text/css; charset=utf-8")
}

pub(crate) async fn asset_js_api() -> ([(axum::http::HeaderName, &'static str); 1], &'static str) {
    asset_response(ASSET_JS_API, "text/javascript; charset=utf-8")
}

pub(crate) async fn asset_js_components()
-> ([(axum::http::HeaderName, &'static str); 1], &'static str) {
    asset_response(ASSET_JS_COMPONENTS, "text/javascript; charset=utf-8")
}

pub(crate) async fn asset_js_pages() -> ([(axum::http::HeaderName, &'static str); 1], &'static str)
{
    asset_response(ASSET_JS_PAGES, "text/javascript; charset=utf-8")
}

pub(crate) async fn asset_js_app() -> ([(axum::http::HeaderName, &'static str); 1], &'static str) {
    asset_response(ASSET_JS_APP, "text/javascript; charset=utf-8")
}

pub(crate) const INDEX_HTML: &str = include_str!("../ui/index.html");

// Front-end assets split out of index.html (served at /assets/*), embedded in
// the binary via include_str! so the dashboard stays a self-contained, offline,
// no-build-step app — no filesystem reads, no CDN.

pub(crate) const ASSET_STYLES_CSS: &str = include_str!("../ui/assets/styles.css");

pub(crate) const ASSET_JS_API: &str = include_str!("../ui/assets/js/api.js");

pub(crate) const ASSET_JS_COMPONENTS: &str = include_str!("../ui/assets/js/components.js");

pub(crate) const ASSET_JS_PAGES: &str = include_str!("../ui/assets/js/pages.js");
pub(crate) const ASSET_JS_APP: &str = include_str!("../ui/assets/js/app.js");

// Vendored graph libraries (served at /vendor/*) so the map needs no CDN.

pub(crate) const VENDOR_CYTOSCAPE: &str = include_str!("../ui/vendor/cytoscape.min.js");

pub(crate) const VENDOR_LAYOUT_BASE: &str = include_str!("../ui/vendor/layout-base.js");

pub(crate) const VENDOR_COSE_BASE: &str = include_str!("../ui/vendor/cose-base.js");

pub(crate) const VENDOR_FCOSE: &str = include_str!("../ui/vendor/cytoscape-fcose.js");

pub(crate) const VENDOR_COLA: &str = include_str!("../ui/vendor/cola.min.js");
pub(crate) const VENDOR_CYTO_COLA: &str = include_str!("../ui/vendor/cytoscape-cola.js");
