//! (generated by module split — pure refactor, behavior identical)
#![allow(unused_imports)]

use std::collections::BTreeMap;
use std::path::PathBuf;
use std::process::Stdio;
use std::sync::Arc;

use anyhow::Result;
use axum::{
    Json, Router,
    extract::{Path as AxPath, State},
    http::StatusCode,
    response::{Html, IntoResponse},
    routing::{delete, get, post},
};
use rtrt_core::{
    OutputStyleLevel, read_output_style_level, read_output_style_level_for,
    write_output_style_level_for,
};
use rtrt_memory::{
    ClusterIndex, ConceptHierarchy, DetailedRecord, Embedder, MemoryStore, PayloadFilter,
    Summariser,
};
use rtrt_providers::{
    ChatMessage, ChatRequest, ChatResponse, Gateway, MetricsView, Prefer, Provider, RequestMetric,
    Role, RouteAlternative, RouteRequest, UsageSnapshot, select_route,
};
use rtrt_security::{Profile, ScanReport};
use rtrt_templates::{Prompt, PromptRegistry};
use serde::{Deserialize, Serialize};
use tokio::io::AsyncWriteExt;
use tokio::sync::Mutex;
use tokio::sync::broadcast;

use crate::prelude::*;

/// Hourly background sweep — keeps each project's row count under
/// `RTRT_CONSOLIDATE_KEEP` (default 1000) using the LLM-free archive path.
/// Disabled when `RTRT_CONSOLIDATE_INTERVAL_SEC=0`.
pub(crate) fn spawn_consolidation_daemon(memory: Option<Arc<Mutex<MemoryStore>>>) {
    // OFF by default: this daemon DELETES the oldest rows beyond `keep` (no LLM
    // summary), which conflicts with rtrt's permanent-memory promise. Opt in
    // explicitly with RTRT_CONSOLIDATE_INTERVAL_SEC > 0 if you want a hard cap.
    // Token growth is handled by the auto-compress daemon, which shrinks bodies
    // while keeping every row (and the original in body_full).
    let interval_sec: u64 = std::env::var("RTRT_CONSOLIDATE_INTERVAL_SEC")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(0);
    if interval_sec == 0 {
        tracing::info!(
            "consolidation daemon off (permanent memory; set RTRT_CONSOLIDATE_INTERVAL_SEC>0 to cap)"
        );
        return;
    }
    let keep: usize = std::env::var("RTRT_CONSOLIDATE_KEEP")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(1000);
    let Some(store) = memory else {
        tracing::info!("consolidation daemon off (no memory store)");
        return;
    };
    tracing::info!(
        "consolidation daemon every {interval_sec}s, keep {keep} most-recent rows per project"
    );
    tokio::spawn(async move {
        let mut tick = tokio::time::interval(std::time::Duration::from_secs(interval_sec));
        // The first tick fires immediately — skip it so the daemon doesn't
        // sweep on startup before any rows have accumulated.
        tick.tick().await;
        loop {
            tick.tick().await;
            let guard = store.lock().await;
            let projects = match guard.projects() {
                Ok(p) => p,
                Err(e) => {
                    tracing::warn!("consolidate: list projects: {e}");
                    continue;
                }
            };
            for (project, count, _) in projects {
                if count <= keep {
                    continue;
                }
                match guard.archive_overflow_no_llm(&project, keep) {
                    Ok(removed) if removed > 0 => {
                        tracing::info!(project = %project, removed, kept = keep, "consolidated");
                    }
                    Ok(_) => {}
                    Err(e) => tracing::warn!("consolidate {project}: {e}"),
                }
            }
        }
    });
}

/// Opt-in background worker — sweeps memory rows older than
/// `RTRT_AUTO_COMPRESS_AGE_SEC` whose body is longer than
/// `RTRT_AUTO_COMPRESS_MIN_CHARS`, asks the configured LLM model to
/// compress each one, and writes the result back via `set_body`.
/// Idempotent: every rewritten row is tagged `metadata.compressed_at`,
/// and `compress_candidates` filters those out next sweep.
///
/// Disabled unless `RTRT_AUTO_COMPRESS_LLM=1`. Honours the same
/// `RTRT_AUTO_COMPRESS_*` knobs documented in `docs/USAGE.md`.
pub(crate) fn spawn_auto_compress_daemon(
    memory: Option<Arc<Mutex<MemoryStore>>>,
    gateway: Arc<Gateway>,
) {
    // Resolution order: env var > ~/.rtrt/config.toml > built-in default.
    // So the daemon turns on when EITHER RTRT_AUTO_COMPRESS_LLM=1 OR the
    // config's [auto_compress] enabled=true.
    let cfg = rtrt_core::Config::load().unwrap_or_default().auto_compress;
    let enabled = match std::env::var("RTRT_AUTO_COMPRESS_LLM") {
        Ok(v) => v == "1" || v.eq_ignore_ascii_case("true") || v.eq_ignore_ascii_case("yes"),
        Err(_) => cfg.enabled,
    };
    if !enabled {
        tracing::info!(
            "auto-compress daemon off (set RTRT_AUTO_COMPRESS_LLM=1 or [auto_compress] enabled=true)"
        );
        return;
    }
    let Some(store) = memory else {
        tracing::info!("auto-compress daemon off (no memory store)");
        return;
    };
    let interval_sec: u64 = std::env::var("RTRT_AUTO_COMPRESS_INTERVAL_SEC")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(cfg.interval_sec);
    let age_sec: i64 = std::env::var("RTRT_AUTO_COMPRESS_AGE_SEC")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(cfg.age_sec);
    let min_chars: usize = std::env::var("RTRT_AUTO_COMPRESS_MIN_CHARS")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(cfg.min_chars);
    let batch: usize = std::env::var("RTRT_AUTO_COMPRESS_BATCH")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(cfg.batch);
    let model = std::env::var("RTRT_AUTO_COMPRESS_MODEL").unwrap_or_else(|_| cfg.model.clone());
    let max_tokens: u32 = std::env::var("RTRT_AUTO_COMPRESS_MAX_TOKENS")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(cfg.max_tokens);
    tracing::info!(
        "auto-compress daemon on: model={model}, every {interval_sec}s, age>{age_sec}s, min_chars={min_chars}, batch={batch}"
    );
    tokio::spawn(async move {
        let mut tick = tokio::time::interval(std::time::Duration::from_secs(interval_sec));
        tick.tick().await;
        loop {
            tick.tick().await;
            let now = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_secs() as i64)
                .unwrap_or(0);
            let cutoff = now - age_sec;
            let projects = {
                let guard = store.lock().await;
                match guard.projects() {
                    Ok(p) => p,
                    Err(e) => {
                        tracing::warn!("auto-compress: list projects: {e}");
                        continue;
                    }
                }
            };
            for (project, _, _) in projects {
                let candidates = {
                    let guard = store.lock().await;
                    match guard.compress_candidates(&project, cutoff, min_chars, batch) {
                        Ok(rows) => rows,
                        Err(e) => {
                            tracing::warn!("auto-compress {project}: candidates: {e}");
                            continue;
                        }
                    }
                };
                for (id, body) in candidates {
                    let req = ChatRequest {
                        model: model.clone(),
                        messages: vec![
                            ChatMessage {
                                role: Role::System,
                                content: "You are a lossless-meaning compressor. Rewrite the user message in the shortest form that preserves every fact, decision, file path, identifier, command, and number. Drop filler, hedging, headings, and greetings. Plain text only. No commentary, no preamble, no quotes — emit only the compressed text.".to_string(),
                            },
                            ChatMessage {
                                role: Role::User,
                                content: body.clone(),
                            },
                        ],
                        max_tokens: Some(max_tokens),
                        temperature: Some(0.0),
                    };
                    let resp = match gateway.chat(req).await {
                        Ok(r) => r,
                        Err(e) => {
                            tracing::warn!("auto-compress {project}#{id}: {e}");
                            continue;
                        }
                    };
                    let new_body = resp.content.trim().to_string();
                    if new_body.is_empty() || new_body.len() >= body.len() {
                        // No win — skip but still mark so we don't retry.
                        let guard = store.lock().await;
                        let mut meta = guard.get_metadata(id).unwrap_or_default();
                        meta.insert("compressed_at".into(), now.to_string());
                        meta.insert("compressed_skip".into(), "no-shrink".into());
                        let _ = guard.set_metadata(id, &meta);
                        continue;
                    }
                    let guard = store.lock().await;
                    if let Err(e) = guard.compress_in_place(id, &new_body) {
                        tracing::warn!("auto-compress {project}#{id}: set_body: {e}");
                        continue;
                    }
                    let mut meta = guard.get_metadata(id).unwrap_or_default();
                    meta.insert("compressed_at".into(), now.to_string());
                    meta.insert("compressed_model".into(), model.clone());
                    meta.insert("compressed_from_chars".into(), body.len().to_string());
                    meta.insert("compressed_to_chars".into(), new_body.len().to_string());
                    let _ = guard.set_metadata(id, &meta);
                    tracing::info!(
                        project = %project,
                        id,
                        from = body.len(),
                        to = new_body.len(),
                        "auto-compressed"
                    );
                }
            }
        }
    });
}

/// Background auto-embed worker — puts embeddings into the AUTOMATIC loop so new
/// captures (saved text-only + fast) get a vector without ever blocking capture
/// or a prompt. Every `embeddings.auto_interval_sec` it opens its OWN
/// `MemoryStore` on `memory_store_path()` (WAL = concurrent with the main store),
/// pulls `unembedded_batch(auto_batch)` newest-first, embeds each body with an
/// `OllamaEmbedder` (`embed_one` already truncates to ~2000 chars), and writes
/// the vector via `store_embedding`. Capped at `auto_batch` rows per cycle so we
/// never hammer Ollama.
///
/// OPTIONAL / LLM-FREE BY DEFAULT: spawns ONLY when `[embeddings] enabled=true`
/// AND `auto=true`. When disabled, this returns immediately — the memory loop
/// stays pure BM25, zero Ollama calls. Probes the embedder reachable ONCE before
/// engaging; if unreachable it logs once and does not spawn (no per-cycle spam).
/// An embed error on a single row is logged and skipped — the row is retried next
/// cycle, the daemon keeps going.
pub(crate) fn spawn_auto_embed_daemon(path: PathBuf) {
    let ecfg = rtrt_core::Config::load().unwrap_or_default().embeddings;
    if !ecfg.is_enabled() {
        tracing::info!(
            "auto-embed daemon off (set RTRT_EMBED_ENABLED=1 or [embeddings] enabled=true)"
        );
        return;
    }
    if !ecfg.auto {
        tracing::info!("auto-embed daemon off ([embeddings] auto=false)");
        return;
    }
    let base_url = ecfg.resolved_base_url(
        rtrt_core::Config::load()
            .ok()
            .and_then(|c| c.auto_compress.base_url)
            .as_deref(),
    );
    let model = ecfg.effective_model();
    let interval_sec = ecfg.auto_interval_sec.max(1);
    let batch = ecfg.auto_batch.max(1);

    tokio::spawn(async move {
        // Probe the embedder reachable ONCE before engaging. If Ollama is
        // unreachable, log once and stay BM25 (do NOT spam every cycle).
        // `OllamaEmbedder` isn't `Clone` (it caches a detected dimension), so we
        // carry the `base_url`/`model` strings and build a fresh one each time —
        // the same pattern the `/api/memory/embed` handler uses.
        let probe = tokio::task::spawn_blocking({
            let base_url = base_url.clone();
            let model = model.clone();
            move || {
                rtrt_memory::OllamaEmbedder::new(base_url, model).embed_one("rtrt auto-embed probe")
            }
        })
        .await;
        match probe {
            Ok(Ok(_)) => {}
            Ok(Err(e)) => {
                tracing::info!(
                    "auto-embed daemon off (embedder {base_url} model={model} unreachable: {e}); staying BM25"
                );
                return;
            }
            Err(e) => {
                tracing::info!("auto-embed daemon off (probe task failed: {e}); staying BM25");
                return;
            }
        }
        tracing::info!(
            "auto-embed daemon on: model={model}, base_url={base_url}, every {interval_sec}s, batch={batch}"
        );

        let mut tick = tokio::time::interval(std::time::Duration::from_secs(interval_sec));
        // First tick fires immediately — skip it so we don't race startup.
        tick.tick().await;
        loop {
            tick.tick().await;
            let path = path.clone();
            let base_url = base_url.clone();
            let model = model.clone();
            // Do the SQLite + embedding work off the async runtime: this opens its
            // OWN WAL connection (concurrent with the main store) and blocks on
            // Ollama HTTP, so it must not run on a tokio worker thread.
            let embedded = tokio::task::spawn_blocking(move || {
                let store = match MemoryStore::open(&path) {
                    Ok(s) => s,
                    Err(e) => {
                        tracing::warn!("auto-embed: open store failed: {e}");
                        return 0usize;
                    }
                };
                let rows = match store.unembedded_batch(batch) {
                    Ok(rows) => rows,
                    Err(e) => {
                        tracing::warn!("auto-embed: unembedded_batch: {e}");
                        return 0;
                    }
                };
                if rows.is_empty() {
                    return 0;
                }
                let embedder = rtrt_memory::OllamaEmbedder::new(base_url, model);
                let mut done = 0;
                for (id, _project, body) in rows {
                    let vector = match embedder.embed_one(&body) {
                        Ok(v) => v,
                        Err(e) => {
                            // Skip this row and keep going; retried next cycle.
                            tracing::warn!("auto-embed #{id}: embed: {e}");
                            continue;
                        }
                    };
                    if let Err(e) = store.store_embedding(id, embedder.model_name(), &vector) {
                        tracing::warn!("auto-embed #{id}: store_embedding: {e}");
                        continue;
                    }
                    done += 1;
                }
                done
            })
            .await
            .unwrap_or(0);
            if embedded > 0 {
                tracing::info!(embedded, "auto-embed cycle");
            }
        }
    });
}
