//! (generated by module split — pure refactor, behavior identical)
#![allow(unused_imports)]

use std::collections::BTreeMap;
use std::path::PathBuf;
use std::process::Stdio;
use std::sync::Arc;

use anyhow::Result;
use axum::{
    Json, Router,
    extract::{Path as AxPath, State},
    http::StatusCode,
    response::{Html, IntoResponse},
    routing::{delete, get, post},
};
use rtrt_core::{
    OutputStyleLevel, read_output_style_level, read_output_style_level_for,
    write_output_style_level_for,
};
use rtrt_memory::{
    ClusterIndex, ConceptHierarchy, DetailedRecord, Embedder, MemoryStore, PayloadFilter,
    Summariser,
};
use rtrt_providers::{
    ChatMessage, ChatRequest, ChatResponse, Gateway, MetricsView, Prefer, Provider, RequestMetric,
    Role, RouteAlternative, RouteRequest, UsageSnapshot, select_route,
};
use rtrt_security::{Profile, ScanReport};
use rtrt_templates::{Prompt, PromptRegistry};
use serde::{Deserialize, Serialize};
use tokio::io::AsyncWriteExt;
use tokio::sync::Mutex;
use tokio::sync::broadcast;

use crate::prelude::*;

#[derive(Clone)]
pub(crate) struct AppState {
    pub(crate) gateway: Arc<Gateway>,
    pub(crate) prompts: Option<Arc<PromptRegistry>>,
    pub(crate) memory: Option<Arc<Mutex<MemoryStore>>>,
    pub(crate) auto_capture: bool,
    pub(crate) auto_redact: bool,
    pub(crate) default_project: String,
    pub(crate) session_id: String,
    pub(crate) dedup_window_sec: i64,
    pub(crate) events: broadcast::Sender<String>,
    /// Shared Ollama embedder, present when `[embeddings] enabled = true` in
    /// the config (or `RTRT_EMBED_ENABLED=1`). `None` keeps all non-vector
    /// paths working without an Ollama instance.
    pub(crate) embedder: Option<Arc<dyn Embedder>>,
    /// Per-`(project, group)` LOD cluster/group index cache
    /// (`"project\x1fgroup" -> (built_at, index)`), TTL [`CLUSTER_INDEX_TTL`].
    /// The `overview` mode builds + caches; the legacy `cluster` drill-down
    /// reads the `context` entry (rebuilding if missing/expired).
    pub(crate) cluster_cache:
        Arc<Mutex<std::collections::HashMap<String, (std::time::Instant, ClusterIndex)>>>,
    /// Per-scope TOP-LEVEL "digital brain" community hierarchy cache (the
    /// `mode=brain` community level). Same style + TTL ([`CLUSTER_INDEX_TTL`]) as
    /// [`AppState::cluster_cache`], keyed `"brainh\x1f<scope>"` and holding a
    /// [`ConceptHierarchy`] (communities + inter-community edges). The per-
    /// community concept sub-graph (`community=ID`) and the per-concept memories
    /// drill (`concept=TOKEN`) are served fresh — only this top level is cached.
    pub(crate) brainh_cache:
        Arc<Mutex<std::collections::HashMap<String, (std::time::Instant, ConceptHierarchy)>>>,
    /// Opaque drill tokens minted per overview/group build
    /// (`token -> (built_at, entry)`), TTL [`LEVEL_TOKEN_TTL`]. Each token maps
    /// to the member-id set of one bubble so the client can drill many levels
    /// deep without ever sending large id lists over the wire.
    pub(crate) level_tokens:
        Arc<Mutex<std::collections::HashMap<String, (std::time::Instant, TokenEntry)>>>,
    /// On-disk SQLite path, so a background embedding backfill can open its OWN
    /// connection (WAL = concurrent with the main one) instead of holding the
    /// shared store mutex for the whole multi-minute job.
    pub(crate) memory_path: std::path::PathBuf,
    /// Projects with an embedding backfill currently running (dedup + progress).
    pub(crate) embedding_jobs: Arc<std::sync::Mutex<std::collections::HashSet<String>>>,
}

/// One drill token's payload: which project it belongs to, the member ids it
/// stands for, and the bubble label (kept for debugging / future reuse).
#[derive(Clone)]
pub(crate) struct TokenEntry {
    pub(crate) project: String,
    pub(crate) member_ids: Vec<i64>,
    /// Project total at mint time — drives the dynamic leaf cutoff so the
    /// "show individual nodes" threshold is consistent across drill levels.
    pub(crate) total_n: usize,
    /// Bubble label captured at mint time. Not read on the drill path (the
    /// child rebuild derives its own labels) but retained for debug logging
    /// and future "breadcrumb" responses.
    #[allow(dead_code)]
    pub(crate) label: String,
}

/// Monotonic source for unique drill-token suffixes (paired with a coarse
/// timestamp so tokens are short, opaque, and collision-free across rebuilds).
pub(crate) static LEVEL_TOKEN_SEQ: std::sync::atomic::AtomicU64 =
    std::sync::atomic::AtomicU64::new(0);

/// Mint a fresh opaque drill token (e.g. `t-<seq>-<nanos>`).
pub(crate) fn mint_level_token() -> String {
    let seq = LEVEL_TOKEN_SEQ.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.subsec_nanos())
        .unwrap_or(0);
    format!("t-{seq}-{nanos:09}")
}

/// Time-to-live for a cached [`ClusterIndex`] before it is rebuilt.
pub(crate) const CLUSTER_INDEX_TTL: std::time::Duration = std::time::Duration::from_secs(60);

/// Time-to-live for a minted drill [`TokenEntry`]. Long enough for a user to
/// drill several levels; short enough that the token cache stays bounded.
pub(crate) const LEVEL_TOKEN_TTL: std::time::Duration = std::time::Duration::from_secs(180);

/// Leaf cutoff: a bubble at/under this many members renders its individual
/// memory nodes instead of splitting further. Dynamic in the project total
/// (~√total, clamped) so a small project bottoms out in one or two levels while
/// a huge one does not dump thousands of points into a single leaf.
pub(crate) fn dynamic_leaf(total: usize) -> usize {
    ((total as f64).sqrt().round() as usize).clamp(40, 160)
}

/// Sub-bubble target when re-clustering a bubble of `size` members at a deeper
/// level. Dynamic in the bucket size (~1.4·√size, clamped): bigger buckets fan
/// out wider, so drill DEPTH grows with quantity instead of being a fixed step.
pub(crate) fn dynamic_branch(size: usize) -> usize {
    (((size as f64).sqrt() * 1.4).round() as usize).clamp(12, 64)
}

/// A re-cluster "did not split" — its largest child still holds this fraction of
/// the parent — so semantic clustering cannot break it up (a lexically-disjoint
/// unclustered mass). The drill path then falls back to a metadata facet.
pub(crate) const STALL_DOMINANCE: f64 = 0.6;

pub(crate) fn broadcast_event(tx: &broadcast::Sender<String>, payload: serde_json::Value) {
    let _ = tx.send(payload.to_string());
}

/// Extract the % savings from a memory row's metadata map (set by the LLM
/// compress sweep). Returns `None` when the row is not compressed or the
/// metadata fields are absent/unparseable.
pub(crate) fn compress_saved_pct_from_meta(
    meta: Option<&std::collections::BTreeMap<String, String>>,
) -> Option<f64> {
    let m = meta?;
    let from: i64 = m.get("compressed_from_chars")?.parse().ok()?;
    let to: i64 = m.get("compressed_to_chars")?.parse().ok()?;
    if from <= 0 {
        return None;
    }
    let saved = (from - to).max(0);
    Some((saved as f64 / from as f64 * 100.0 * 10.0).round() / 10.0)
}

/// Thin wrapper that makes a [`Gateway`] look like a [`Provider`] so we can
/// pass it to [`rtrt_memory::LlmSummariser`]. The adapter forwards chat calls
/// directly; streaming is not needed for summarisation.
pub(crate) struct GatewayAdapter(pub(crate) Arc<Gateway>);

#[async_trait::async_trait]
impl Provider for GatewayAdapter {
    fn name(&self) -> &str {
        "gateway"
    }
    fn supported_models(&self) -> &[&'static str] {
        &[]
    }
    async fn chat(&self, req: ChatRequest) -> rtrt_core::Result<ChatResponse> {
        self.0.chat(req).await
    }
}

impl AppState {
    /// Best-effort auto-save into the memory store. Pipeline:
    /// 1. Privacy filter (`redact_secrets`) when `auto_redact` is true.
    /// 2. SHA-256 dedup against the last `dedup_window_sec` seconds.
    /// 3. Insert raw row, then tag it with session_id + body_sha.
    pub(crate) async fn capture(
        &self,
        kind: &str,
        body: &str,
        metadata: &std::collections::BTreeMap<String, String>,
    ) {
        if !self.auto_capture {
            return;
        }
        let Some(store) = &self.memory else { return };
        let filtered = if self.auto_redact {
            rtrt_compress::redact_secrets(body)
        } else {
            body.to_string()
        };
        let project = self.default_project.clone();
        let kind = kind.to_string();
        let metadata = metadata.clone();
        let session = self.session_id.clone();
        let window = self.dedup_window_sec;
        let guard = store.lock().await;
        let sha = rtrt_memory::MemoryStore::body_sha(&filtered);
        if window > 0
            && let Ok(Some(last_ts)) = guard.body_seen_at(&project, &sha)
        {
            let now = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_secs() as i64)
                .unwrap_or(0);
            if now.saturating_sub(last_ts) < window {
                tracing::debug!(kind = %kind, "auto-capture deduped within {window}s window");
                return;
            }
        }
        let result = if metadata.is_empty() {
            guard.save(&project, &kind, &filtered)
        } else {
            guard.save_with_metadata(&project, &kind, &filtered, &metadata)
        };
        match result {
            Ok(id) => {
                if let Err(e) = guard.tag_row(id, Some(&session), Some(&sha)) {
                    tracing::warn!("auto-capture tag {kind}: {e}");
                }
                broadcast_event(
                    &self.events,
                    serde_json::json!({
                        "type": "memory.save",
                        "id": id,
                        "kind": kind,
                        "project": project,
                        "session": session,
                    }),
                );
            }
            Err(e) => tracing::warn!("auto-capture {kind}: {e}"),
        }
    }
}

pub(crate) fn memory_store_path() -> PathBuf {
    std::env::var("RTRT_MEMORY_PATH")
        .ok()
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from(".rtrt/memory.sqlite"))
}

pub(crate) fn open_memory_store() -> Option<Arc<Mutex<MemoryStore>>> {
    let path = memory_store_path();
    if let Some(parent) = path.parent()
        && !parent.as_os_str().is_empty()
    {
        let _ = std::fs::create_dir_all(parent);
    }
    match MemoryStore::open(&path) {
        Ok(store) => Some(Arc::new(Mutex::new(store))),
        Err(e) => {
            tracing::warn!(?path, "memory store unavailable: {e}");
            None
        }
    }
}

pub(crate) fn open_prompt_registry() -> Option<Arc<PromptRegistry>> {
    let root = match std::env::var("RTRT_PROMPTS_DIR") {
        Ok(p) => PathBuf::from(p),
        Err(_) => rtrt_templates::prompts::default_dir()?,
    };
    match PromptRegistry::open(&root) {
        Ok(reg) => Some(Arc::new(reg)),
        Err(e) => {
            tracing::warn!(?root, "prompts registry unavailable: {e}");
            None
        }
    }
}
