//! (generated by module split — pure refactor, behavior identical)
#![allow(unused_imports)]

use std::collections::BTreeMap;
use std::path::PathBuf;
use std::process::Stdio;
use std::sync::Arc;

use anyhow::Result;
use axum::{
    Json, Router,
    extract::{Path as AxPath, State},
    http::StatusCode,
    response::{Html, IntoResponse},
    routing::{delete, get, post},
};
use rtrt_core::{
    OutputStyleLevel, ProjectIdentity, read_output_style_level, read_output_style_level_for,
    write_output_style_level_for,
};
use rtrt_memory::{
    ClusterIndex, ConceptHierarchy, DetailedRecord, Embedder, MemoryStore, PayloadFilter,
    Summariser,
};
use rtrt_providers::{
    ChatMessage, ChatRequest, ChatResponse, Gateway, MetricsView, Prefer, Provider, RequestMetric,
    Role, RouteAlternative, RouteRequest, UsageSnapshot, select_route,
};
use rtrt_security::{Profile, ScanReport};
use rtrt_templates::{Prompt, PromptRegistry};
use serde::{Deserialize, Serialize};
use tokio::io::AsyncWriteExt;
use tokio::sync::Mutex;
use tokio::sync::broadcast;

use crate::prelude::*;
use crate::project_catalog::ProjectCatalog;

#[derive(Clone)]
pub(crate) struct ProjectContext {
    pub(crate) project: Arc<ProjectIdentity>,
    pub(crate) memory: Arc<Mutex<MemoryStore>>,
    pub(crate) memory_path: PathBuf,
    pub(crate) cluster_cache:
        Arc<Mutex<std::collections::HashMap<String, (std::time::Instant, ClusterIndex)>>>,
    pub(crate) brainh_cache:
        Arc<Mutex<std::collections::HashMap<String, (std::time::Instant, ConceptHierarchy)>>>,
    pub(crate) level_tokens:
        Arc<Mutex<std::collections::HashMap<String, (std::time::Instant, TokenEntry)>>>,
    pub(crate) embedding_jobs: Arc<std::sync::Mutex<std::collections::HashSet<String>>>,
}

impl ProjectContext {
    pub(crate) fn new(
        project: Arc<ProjectIdentity>,
        memory: Arc<Mutex<MemoryStore>>,
        memory_path: PathBuf,
    ) -> Self {
        Self {
            project,
            memory,
            memory_path,
            cluster_cache: Arc::new(Mutex::new(std::collections::HashMap::new())),
            brainh_cache: Arc::new(Mutex::new(std::collections::HashMap::new())),
            level_tokens: Arc::new(Mutex::new(std::collections::HashMap::new())),
            embedding_jobs: Arc::new(std::sync::Mutex::new(std::collections::HashSet::new())),
        }
    }
}

#[derive(Clone)]
pub(crate) struct AppState {
    pub(crate) gateway: Arc<Gateway>,
    pub(crate) prompts: Option<Arc<PromptRegistry>>,
    pub(crate) memory: Option<Arc<Mutex<MemoryStore>>>,
    pub(crate) auto_capture: bool,
    pub(crate) auto_redact: bool,
    /// Immutable identity established before any store or watcher is opened.
    pub(crate) project: Arc<ProjectIdentity>,
    pub(crate) session_id: String,
    pub(crate) dedup_window_sec: i64,
    pub(crate) events: broadcast::Sender<String>,
    /// Shared Ollama embedder, present when `[embeddings] enabled = true` in
    /// the config (or `RTRT_EMBED_ENABLED=1`). `None` keeps all non-vector
    /// paths working without an Ollama instance.
    pub(crate) embedder: Option<Arc<dyn Embedder>>,
    /// LOD cluster/group index cache for `mode=overview`, keyed on every knob
    /// that can change what's built — `"{project}\x1f{group}\x1f{basis}\x1f
    /// {target}\x1f{allow_vector as u8}"` -> `(built_at, index)`, TTL
    /// [`CLUSTER_INDEX_TTL`] (see [`CACHE_KEY_SEP`](crate::handlers::memgraph::CACHE_KEY_SEP)
    /// and `memory_graph_overview`'s `cache_key`). Only the overview build
    /// reads/writes this map now — the legacy bare-`project`-keyed entry the
    /// retired `?cluster=<id>` drill used to read (a different, incompatible
    /// partition) is gone; no code path resolves a composite key it didn't
    /// itself mint.
    pub(crate) cluster_cache:
        Arc<Mutex<std::collections::HashMap<String, (std::time::Instant, ClusterIndex)>>>,
    /// Per-scope TOP-LEVEL "digital brain" community hierarchy cache (the
    /// `mode=brain` community level). Same style + TTL ([`CLUSTER_INDEX_TTL`]) as
    /// [`AppState::cluster_cache`], keyed `"brainh\x1f<scope>"` and holding a
    /// [`ConceptHierarchy`] (communities + inter-community edges). The per-
    /// community concept sub-graph (`community=ID`) and the per-concept memories
    /// drill (`concept=TOKEN`) are served fresh — only this top level is cached.
    pub(crate) brainh_cache:
        Arc<Mutex<std::collections::HashMap<String, (std::time::Instant, ConceptHierarchy)>>>,
    /// Opaque drill tokens minted per overview/group build
    /// (`token -> (built_at, entry)`), TTL [`LEVEL_TOKEN_TTL`]. Each token maps
    /// to the member-id set of one bubble so the client can drill many levels
    /// deep without ever sending large id lists over the wire.
    pub(crate) level_tokens:
        Arc<Mutex<std::collections::HashMap<String, (std::time::Instant, TokenEntry)>>>,
    /// On-disk SQLite path, so a background embedding backfill can open its OWN
    /// connection (WAL = concurrent with the main one) instead of holding the
    /// shared store mutex for the whole multi-minute job.
    pub(crate) memory_path: std::path::PathBuf,
    /// Projects with an embedding backfill currently running (dedup + progress).
    pub(crate) embedding_jobs: Arc<std::sync::Mutex<std::collections::HashSet<String>>>,
    pub(crate) catalog: Arc<ProjectCatalog>,
    pub(crate) selected: bool,
    pub(crate) daemon_projects: Arc<std::sync::Mutex<std::collections::HashSet<String>>>,
}

/// One drill token's payload: which project it belongs to, the member ids it
/// stands for, and the bubble label (kept for debugging / future reuse).
#[derive(Clone)]
pub(crate) struct TokenEntry {
    pub(crate) project: String,
    pub(crate) member_ids: Vec<i64>,
    /// Project total at mint time — drives the dynamic leaf cutoff so the
    /// "show individual nodes" threshold is consistent across drill levels.
    pub(crate) total_n: usize,
    /// Bubble label captured at mint time. Not read on the drill path (the
    /// child rebuild derives its own labels) but retained for debug logging
    /// and future "breadcrumb" responses.
    #[allow(dead_code)]
    pub(crate) label: String,
}

/// Monotonic source for unique drill-token suffixes (paired with a coarse
/// timestamp so tokens are short, opaque, and collision-free across rebuilds).
pub(crate) static LEVEL_TOKEN_SEQ: std::sync::atomic::AtomicU64 =
    std::sync::atomic::AtomicU64::new(0);

/// Mint a fresh opaque drill token (e.g. `t-<seq>-<nanos>`).
pub(crate) fn mint_level_token() -> String {
    let seq = LEVEL_TOKEN_SEQ.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.subsec_nanos())
        .unwrap_or(0);
    format!("t-{seq}-{nanos:09}")
}

/// Time-to-live for a cached [`ClusterIndex`] before it is rebuilt.
pub(crate) const CLUSTER_INDEX_TTL: std::time::Duration = std::time::Duration::from_secs(60);

/// Time-to-live for a minted drill [`TokenEntry`]. Long enough for a user to
/// drill several levels; short enough that the token cache stays bounded.
pub(crate) const LEVEL_TOKEN_TTL: std::time::Duration = std::time::Duration::from_secs(180);

/// Leaf cutoff: a bubble at/under this many members renders its individual
/// memory nodes instead of splitting further. Dynamic in the project total
/// (~√total, clamped) so a small project bottoms out in one or two levels while
/// a huge one does not dump thousands of points into a single leaf.
pub(crate) fn dynamic_leaf(total: usize) -> usize {
    ((total as f64).sqrt().round() as usize).clamp(40, 160)
}

/// Sub-bubble target when re-clustering a bubble of `size` members at a deeper
/// level. Dynamic in the bucket size (~1.4·√size, clamped): bigger buckets fan
/// out wider, so drill DEPTH grows with quantity instead of being a fixed step.
pub(crate) fn dynamic_branch(size: usize) -> usize {
    (((size as f64).sqrt() * 1.4).round() as usize).clamp(12, 64)
}

/// A re-cluster "did not split" — its largest child still holds this fraction of
/// the parent — so semantic clustering cannot break it up (a lexically-disjoint
/// unclustered mass). The drill path then falls back to a metadata facet.
pub(crate) const STALL_DOMINANCE: f64 = 0.6;

pub(crate) fn broadcast_event(tx: &broadcast::Sender<String>, payload: serde_json::Value) {
    let _ = tx.send(payload.to_string());
}

/// Extract the % savings from a memory row's metadata map (set by the LLM
/// compress sweep). Returns `None` when the row is not compressed or the
/// metadata fields are absent/unparseable.
pub(crate) fn compress_saved_pct_from_meta(
    meta: Option<&std::collections::BTreeMap<String, String>>,
) -> Option<f64> {
    let m = meta?;
    let from: i64 = m.get("compressed_from_chars")?.parse().ok()?;
    let to: i64 = m.get("compressed_to_chars")?.parse().ok()?;
    if from <= 0 {
        return None;
    }
    let saved = (from - to).max(0);
    Some((saved as f64 / from as f64 * 100.0 * 10.0).round() / 10.0)
}

/// Thin wrapper that makes a [`Gateway`] look like a [`Provider`] so we can
/// pass it to [`rtrt_memory::LlmSummariser`]. The adapter forwards chat calls
/// directly; streaming is not needed for summarisation.
pub(crate) struct GatewayAdapter(pub(crate) Arc<Gateway>);

#[async_trait::async_trait]
impl Provider for GatewayAdapter {
    fn name(&self) -> &str {
        "gateway"
    }
    fn supported_models(&self) -> &[&'static str] {
        &[]
    }
    async fn chat(&self, req: ChatRequest) -> rtrt_core::Result<ChatResponse> {
        self.0.chat(req).await
    }
}

impl AppState {
    #[allow(clippy::too_many_arguments)]
    pub(crate) fn machine(
        gateway: Arc<Gateway>,
        prompts: Option<Arc<PromptRegistry>>,
        auto_capture: bool,
        auto_redact: bool,
        session_id: String,
        dedup_window_sec: i64,
        events: broadcast::Sender<String>,
        embedder: Option<Arc<dyn Embedder>>,
        catalog: Arc<ProjectCatalog>,
        home: PathBuf,
    ) -> Result<Self> {
        // Context fields are inert on global routes. Project routes always
        // replace them through selector middleware before handler extraction.
        let placeholder_root = home.join(".rtrt/dashboard");
        let project = Arc::new(ProjectIdentity::derive(&placeholder_root)?);
        Ok(Self {
            gateway,
            prompts,
            memory: None,
            auto_capture,
            auto_redact,
            project,
            session_id,
            dedup_window_sec,
            events,
            embedder,
            cluster_cache: Arc::new(Mutex::new(std::collections::HashMap::new())),
            brainh_cache: Arc::new(Mutex::new(std::collections::HashMap::new())),
            level_tokens: Arc::new(Mutex::new(std::collections::HashMap::new())),
            memory_path: placeholder_root.join("unavailable.sqlite"),
            embedding_jobs: Arc::new(std::sync::Mutex::new(std::collections::HashSet::new())),
            catalog,
            selected: false,
            daemon_projects: Arc::new(std::sync::Mutex::new(std::collections::HashSet::new())),
        })
    }

    pub(crate) fn with_context(&self, context: &ProjectContext) -> Self {
        let mut selected = self.clone();
        selected.project = context.project.clone();
        selected.memory = Some(context.memory.clone());
        selected.memory_path = context.memory_path.clone();
        selected.cluster_cache = context.cluster_cache.clone();
        selected.brainh_cache = context.brainh_cache.clone();
        selected.level_tokens = context.level_tokens.clone();
        selected.embedding_jobs = context.embedding_jobs.clone();
        selected.selected = true;
        selected
    }

    /// Starts each verified project's background workers at most once for this
    /// process. Refresh can safely call this after admitting new contexts.
    pub(crate) fn start_project_daemons(&self) {
        for context in self.catalog.contexts() {
            let slug = context.project.slug().to_string();
            let should_start = self
                .daemon_projects
                .lock()
                .unwrap_or_else(|e| e.into_inner())
                .insert(slug.clone());
            if !should_start {
                continue;
            }
            let memory = Some(context.memory.clone());
            crate::daemons::spawn_consolidation_daemon(memory.clone(), slug.clone());
            crate::daemons::spawn_auto_compress_daemon(memory.clone(), self.gateway.clone(), slug);
            crate::daemons::spawn_auto_embed_daemon(context.project.clone());
            crate::transcripts::spawn_reattribution(memory.clone(), context.project.clone());
            crate::transcripts::spawn_transcript_watcher(memory.clone(), context.project.clone());
            crate::opencode_transcripts::spawn_transcript_watcher(memory, context.project.clone());
        }
    }

    /// Best-effort auto-save into the memory store. Pipeline:
    /// 1. Privacy filter (`redact_secrets`) when `auto_redact` is true.
    /// 2. SHA-256 dedup against the last `dedup_window_sec` seconds.
    /// 3. Insert raw row, then tag it with session_id + body_sha.
    pub(crate) async fn capture(
        &self,
        kind: &str,
        body: &str,
        metadata: &std::collections::BTreeMap<String, String>,
    ) {
        if !self.selected || !self.auto_capture {
            return;
        }
        let Some(store) = &self.memory else { return };
        let filtered = if self.auto_redact {
            rtrt_compress::redact_secrets(body)
        } else {
            body.to_string()
        };
        let project = self.project.slug().to_string();
        let kind = kind.to_string();
        let metadata = metadata.clone();
        let session = self.session_id.clone();
        let window = self.dedup_window_sec;
        let guard = store.lock().await;
        let sha = rtrt_memory::MemoryStore::body_sha(&filtered);
        if window > 0
            && let Ok(Some(last_ts)) = guard.body_seen_at(&project, &sha)
        {
            let now = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_secs() as i64)
                .unwrap_or(0);
            if now.saturating_sub(last_ts) < window {
                tracing::debug!(kind = %kind, "auto-capture deduped within {window}s window");
                return;
            }
        }
        let result = if metadata.is_empty() {
            guard.save(&project, &kind, &filtered)
        } else {
            guard.save_with_metadata(&project, &kind, &filtered, &metadata)
        };
        match result {
            Ok(id) => {
                if let Err(e) = guard.tag_row(id, Some(&session), Some(&sha)) {
                    tracing::warn!("auto-capture tag {kind}: {e}");
                }
                broadcast_event(
                    &self.events,
                    serde_json::json!({
                        "type": "memory.save",
                        "id": id,
                        "kind": kind,
                        "project": project,
                        "session": session,
                    }),
                );
            }
            Err(e) => tracing::warn!("auto-capture {kind}: {e}"),
        }
    }
}

impl AppState {
    /// Optional client project values are assertions, never routing keys.
    pub(crate) fn assert_project<'a>(
        &'a self,
        requested: Option<&str>,
    ) -> std::result::Result<&'a str, (StatusCode, String)> {
        if let Some(value) = requested.map(str::trim).filter(|v| !v.is_empty())
            && value != self.project.slug()
        {
            return Err((StatusCode::FORBIDDEN, "foreign project".into()));
        }
        Ok(self.project.slug())
    }

    /// Canonical, symlink-safe containment under canonical main repository.
    pub(crate) fn contained_path(
        &self,
        requested: &std::path::Path,
    ) -> std::result::Result<PathBuf, (StatusCode, String)> {
        let candidate = if requested.is_absolute() {
            requested.to_path_buf()
        } else {
            self.project.memory_root().join(requested)
        };
        let canonical = std::fs::canonicalize(&candidate)
            .map_err(|_| (StatusCode::NOT_FOUND, "path not found".into()))?;
        if !canonical.starts_with(self.project.memory_root()) {
            return Err((
                StatusCode::FORBIDDEN,
                "path outside selected project".into(),
            ));
        }
        Ok(canonical)
    }

    pub(crate) fn contained_write_path(
        &self,
        requested: &std::path::Path,
    ) -> std::result::Result<PathBuf, (StatusCode, String)> {
        let candidate = if requested.is_absolute() {
            requested.to_path_buf()
        } else {
            self.project.memory_root().join(requested)
        };
        if candidate.exists() {
            return self.contained_path(&candidate);
        }
        let parent = candidate
            .parent()
            .ok_or((StatusCode::BAD_REQUEST, "target has no parent".into()))?;
        let canonical_parent = std::fs::canonicalize(parent)
            .map_err(|_| (StatusCode::NOT_FOUND, "target parent not found".into()))?;
        if !canonical_parent.starts_with(self.project.memory_root()) {
            return Err((
                StatusCode::FORBIDDEN,
                "path outside selected project".into(),
            ));
        }
        let name = candidate
            .file_name()
            .ok_or((StatusCode::BAD_REQUEST, "invalid target".into()))?;
        Ok(canonical_parent.join(name))
    }
}

pub(crate) fn open_prompt_registry() -> Option<Arc<PromptRegistry>> {
    let root = match std::env::var("RTRT_PROMPTS_DIR") {
        Ok(p) => PathBuf::from(p),
        Err(_) => rtrt_templates::prompts::default_dir()?,
    };
    match PromptRegistry::open(&root) {
        Ok(reg) => Some(Arc::new(reg)),
        Err(e) => {
            tracing::warn!(?root, "prompts registry unavailable: {e}");
            None
        }
    }
}
