//! (generated by module split — pure refactor, behavior identical)
#![allow(unused_imports)]

use std::collections::BTreeMap;
use std::path::PathBuf;
use std::process::Stdio;
use std::sync::Arc;

use anyhow::Result;
use axum::{
    Json, Router,
    extract::{Path as AxPath, State},
    http::StatusCode,
    response::{Html, IntoResponse},
    routing::{delete, get, post},
};
use rtrt_core::{
    OutputStyleLevel, read_output_style_level, read_output_style_level_for,
    write_output_style_level_for,
};
use rtrt_memory::{
    ClusterIndex, ConceptHierarchy, DetailedRecord, Embedder, MemoryStore, PayloadFilter,
    Summariser,
};
use rtrt_providers::{
    ChatMessage, ChatRequest, ChatResponse, Gateway, MetricsView, Prefer, Provider, RequestMetric,
    Role, RouteAlternative, RouteRequest, UsageSnapshot, select_route,
};
use rtrt_security::{Profile, ScanReport};
use rtrt_templates::{Prompt, PromptRegistry};
use serde::{Deserialize, Serialize};
use tokio::io::AsyncWriteExt;
use tokio::sync::Mutex;
use tokio::sync::broadcast;

use crate::prelude::*;

static CONFIG_WRITE_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());
static TEMP_COUNTER: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);

/// JSON merge-patch field preserving the distinction between omitted and null.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub(crate) enum JsonPatch<T> {
    #[default]
    Missing,
    Null,
    Value(T),
}

impl<'de, T> Deserialize<'de> for JsonPatch<T>
where
    T: Deserialize<'de>,
{
    fn deserialize<D>(deserializer: D) -> std::result::Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        Ok(match Option::<T>::deserialize(deserializer)? {
            Some(value) => Self::Value(value),
            None => Self::Null,
        })
    }
}

pub(crate) async fn healthz() -> &'static str {
    "ok"
}

pub(crate) async fn stats() -> Json<serde_json::Value> {
    Json(serde_json::json!({
        "input_saved": 0,
        "output_saved": 0,
        "provider": null,
    }))
}

/// Shared error reply for the project-aware config handlers.
pub(crate) fn clear_field_error(e: rtrt_core::Error) -> axum::response::Response {
    (
        StatusCode::INTERNAL_SERVER_ERROR,
        Json(serde_json::json!({ "error": e.to_string() })),
    )
        .into_response()
}

// ---------------------------------------------------------------------------
// GET/POST /api/providers/config
//
// Per-project active-provider + enabled overlay (`ProjectConfig.providers`).
// GET reports the effective active provider + each detected provider's enabled
// state (global, overlaid with the project override). POST writes the project
// override; `?scope=global` clears it (preserving coexisting overrides).
// ---------------------------------------------------------------------------

pub(crate) fn metadata_savings(raw: &str, expected_source: &str) -> Option<(i64, i64, i64)> {
    let value: serde_json::Value = serde_json::from_str(raw).ok()?;
    let obj = value.as_object()?;
    if obj.get("source")?.as_str()? != expected_source {
        return None;
    }
    let original_chars = json_i64(obj.get("compressed_from_chars")?)?.max(0);
    let compressed_to_chars = obj.get("compressed_to_chars").and_then(json_i64);
    // The stored `saved_chars` field is unreliable (observed 0 for a real
    // 309->117 compression, and 81 for a 68-char input). Always derive the
    // delta from compressed_from/to when `to` is present; only fall back to the
    // stored field when `to` is missing.
    let (saved_chars, with_rtrt_chars) = match compressed_to_chars {
        Some(to_chars) => ((original_chars - to_chars).max(0), to_chars.max(0)),
        None => {
            let stored = obj.get("saved_chars").and_then(json_i64)?.max(0);
            (stored, original_chars.saturating_sub(stored).max(0))
        }
    };
    Some((saved_chars, original_chars, with_rtrt_chars))
}

pub(crate) fn json_i64(value: &serde_json::Value) -> Option<i64> {
    if let Some(n) = value.as_i64() {
        return Some(n);
    }
    value.as_str()?.parse::<i64>().ok()
}

pub(crate) fn estimate_saved_tokens(saved_chars: i64) -> i64 {
    saved_chars / 4
}

pub(crate) fn saved_pct(saved_chars: i64, original_chars: i64) -> Option<f64> {
    if original_chars <= 0 {
        return None;
    }
    Some(saved_chars.max(0) as f64 / original_chars as f64 * 100.0)
}

pub(crate) fn saved_pct_or_zero(saved_chars: i64, original_chars: i64) -> f64 {
    saved_pct(saved_chars, original_chars).unwrap_or(0.0)
}

pub(crate) fn proxy_stats_path() -> PathBuf {
    std::env::var_os("HOME")
        .or_else(|| std::env::var_os("USERPROFILE"))
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".rtrt")
        .join("proxy-stats.sqlite")
}

pub(crate) fn normalize_project(project: Option<String>) -> String {
    let project = project.unwrap_or_default();
    let project = project.trim();
    if project.is_empty() {
        "(unknown)".to_string()
    } else {
        project.to_string()
    }
}

pub(crate) const SECS_PER_HOUR: i64 = 60 * 60;
pub(crate) const SECS_PER_DAY: i64 = SECS_PER_HOUR * 24;

/// Is `path` a SPA HTML-shell route (served either by `GET /` or the catch-all
/// fallback)? Everything outside `/api` is public bootstrap content and carries
/// no dashboard token or API data.
pub(crate) fn is_spa_shell_path(path: &str) -> bool {
    !(path.starts_with("/api/") || path == "/api")
}

pub(crate) async fn bearer_guard(
    expected: Option<Arc<String>>,
    req: axum::extract::Request,
    next: axum::middleware::Next,
) -> axum::response::Response {
    use axum::http::{HeaderValue, header::AUTHORIZATION};
    let path = req.uri().path().to_string();
    // Always allow the SPA HTML shell and its fixed compiled-in assets so the UI
    // can bootstrap. Deep SPA routes (e.g. /memory/search) are served by the
    // catch-all as the same shell as `/`, so browser navigation cannot attach a
    // bearer header. Never extend this exemption beyond non-API paths and the
    // exact POST-only bootstrap exchange below.
    if is_spa_shell_path(&path)
        || (path == "/api/auth/bootstrap" && req.method() == axum::http::Method::POST)
    {
        return next.run(req).await;
    }
    let Some(expected) = expected else {
        return unauthorized();
    };
    let presented = req
        .headers()
        .get(AUTHORIZATION)
        .and_then(|v| v.to_str().ok())
        .and_then(|raw| raw.strip_prefix("Bearer "))
        .map(str::to_string);
    let ok = presented
        .as_deref()
        .is_some_and(|tok| constant_time_eq(tok.as_bytes(), expected.as_bytes()));
    if ok {
        return next.run(req).await;
    }
    unauthorized()
}

fn unauthorized() -> axum::response::Response {
    let mut resp = axum::response::Response::new(axum::body::Body::from(
        "unauthorized: bearer token missing or invalid",
    ));
    *resp.status_mut() = StatusCode::UNAUTHORIZED;
    resp.headers_mut().insert(
        "WWW-Authenticate",
        axum::http::HeaderValue::from_static("Bearer realm=\"rtrt-dashboard\""),
    );
    resp
}

pub(crate) fn constant_time_eq(a: &[u8], b: &[u8]) -> bool {
    let mut diff = a.len() ^ b.len();
    for index in 0..a.len().max(b.len()) {
        diff |=
            usize::from(a.get(index).copied().unwrap_or(0) ^ b.get(index).copied().unwrap_or(0));
    }
    diff == 0
}

pub(crate) fn walk_files(root: &std::path::Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let mut stack = vec![root.to_path_buf()];
    while let Some(p) = stack.pop() {
        let Ok(rd) = std::fs::read_dir(&p) else {
            continue;
        };
        for entry in rd.flatten() {
            let path = entry.path();
            if let Ok(ft) = entry.file_type() {
                if ft.is_dir() {
                    let name = entry.file_name();
                    let nstr = name.to_string_lossy();
                    if nstr == "target" || nstr.starts_with('.') {
                        continue;
                    }
                    stack.push(path);
                } else if ft.is_file() {
                    out.push(path);
                }
            }
        }
    }
    out
}

#[derive(Debug, Serialize)]
pub(crate) struct ApiError {
    error: String,
}

pub(crate) type DashboardJsonResult<T> = std::result::Result<Json<T>, (StatusCode, Json<ApiError>)>;

pub(crate) fn api_error(
    status: StatusCode,
    message: impl Into<String>,
) -> (StatusCode, Json<ApiError>) {
    (
        status,
        Json(ApiError {
            error: message.into(),
        }),
    )
}

pub(crate) fn write_config_file(
    cfg: &rtrt_core::Config,
) -> std::result::Result<String, (StatusCode, String)> {
    let _guard = CONFIG_WRITE_LOCK.lock().map_err(|_| {
        (
            StatusCode::INTERNAL_SERVER_ERROR,
            "config writer lock poisoned".into(),
        )
    })?;
    write_config_file_locked(cfg)
}

/// Serialize a complete read-modify-write transaction. Handlers using PATCH
/// semantics must load under this lock, otherwise two individually atomic
/// writes can still lose each other's fields.
pub(crate) fn update_config_file(
    mutate: impl FnOnce(&mut rtrt_core::Config) -> std::result::Result<(), (StatusCode, String)>,
) -> std::result::Result<(rtrt_core::Config, String), (StatusCode, String)> {
    let _guard = CONFIG_WRITE_LOCK.lock().map_err(|_| {
        (
            StatusCode::INTERNAL_SERVER_ERROR,
            "config writer lock poisoned".into(),
        )
    })?;
    let path = rtrt_core::Config::default_path().ok_or((
        StatusCode::INTERNAL_SERVER_ERROR,
        "cannot determine config path".into(),
    ))?;
    reject_unsafe_target(&path, false)?;
    let mut cfg = rtrt_core::Config::load()
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
    mutate(&mut cfg)?;
    let path = write_config_file_locked(&cfg)?;
    Ok((cfg, path))
}

/// Serialize and atomically persist a project override with same path-safety
/// checks as global config writes.
pub(crate) fn write_project_config(
    repo: &std::path::Path,
    project: &rtrt_core::config::ProjectConfig,
) -> rtrt_core::Result<()> {
    let _guard = CONFIG_WRITE_LOCK
        .lock()
        .map_err(|_| rtrt_core::Error::Config("config writer lock poisoned".into()))?;
    let path = rtrt_core::Config::project_config_path(repo);
    reject_unsafe_target_io(&path, false)
        .map_err(|error| rtrt_core::Error::Config(error.to_string()))?;
    if project.is_empty() {
        match std::fs::remove_file(&path) {
            Ok(()) => return Ok(()),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(()),
            Err(error) => return Err(rtrt_core::Error::Config(error.to_string())),
        }
    }
    let parent = path
        .parent()
        .ok_or_else(|| rtrt_core::Error::Config("project config has no parent".into()))?;
    ensure_safe_dir(parent).map_err(|error| rtrt_core::Error::Config(error.to_string()))?;
    let body = toml::to_string_pretty(project)
        .map_err(|error| rtrt_core::Error::Config(error.to_string()))?;
    atomic_write(&path, body.as_bytes())
        .map_err(|error| rtrt_core::Error::Config(error.to_string()))
}

fn write_config_file_locked(
    cfg: &rtrt_core::Config,
) -> std::result::Result<String, (StatusCode, String)> {
    let path = rtrt_core::Config::default_path().ok_or((
        StatusCode::INTERNAL_SERVER_ERROR,
        "cannot determine config path".into(),
    ))?;

    if let Some(parent) = path.parent() {
        ensure_safe_dir(parent).map_err(|e| {
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("create dir {}: {e}", parent.display()),
            )
        })?;
    }

    reject_unsafe_target(&path, false)?;

    let toml_str = toml::to_string_pretty(cfg)
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
    atomic_write(&path, toml_str.as_bytes()).map_err(|e| {
        (
            StatusCode::INTERNAL_SERVER_ERROR,
            format!("write {}: {e}", path.display()),
        )
    })?;
    Ok(path.to_string_lossy().into_owned())
}

/// Atomic writer shared with security profiles. Existing symlinks are rejected
/// rather than followed; on Unix, targets/directories owned by another user are
/// rejected using the current HOME owner as the trusted uid.
pub(crate) fn atomic_write(path: &std::path::Path, bytes: &[u8]) -> std::io::Result<()> {
    reject_unsafe_target_io(path, false)?;
    let parent = path
        .parent()
        .ok_or_else(|| std::io::Error::other("target has no parent"))?;
    reject_unsafe_target_io(parent, true)?;
    let n = TEMP_COUNTER.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    let file_name = path
        .file_name()
        .and_then(|v| v.to_str())
        .unwrap_or("config");
    let tmp = parent.join(format!(".{file_name}.{}.{}.tmp", std::process::id(), n));
    let mut options = std::fs::OpenOptions::new();
    options.write(true).create_new(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        options.mode(0o600);
    }
    let result = (|| {
        use std::io::Write;
        let mut file = options.open(&tmp)?;
        file.write_all(bytes)?;
        file.sync_all()?;
        std::fs::rename(&tmp, path)?;
        if let Ok(dir) = std::fs::File::open(parent) {
            let _ = dir.sync_all();
        }
        Ok(())
    })();
    if result.is_err() {
        let _ = std::fs::remove_file(&tmp);
    }
    result
}

/// Create a private write directory only after checking every existing path
/// component. This prevents `create_dir_all` from traversing a planted symlink.
pub(crate) fn ensure_safe_dir(path: &std::path::Path) -> std::io::Result<()> {
    reject_unsafe_target_io(path, false)?;
    std::fs::create_dir_all(path)?;
    reject_unsafe_target_io(path, true)
}

fn reject_unsafe_target(
    path: &std::path::Path,
    must_exist: bool,
) -> std::result::Result<(), (StatusCode, String)> {
    reject_unsafe_target_io(path, must_exist).map_err(|e| (StatusCode::BAD_REQUEST, e.to_string()))
}

fn reject_unsafe_target_io(path: &std::path::Path, must_exist: bool) -> std::io::Result<()> {
    // Inspect components themselves: metadata on only the final path would
    // follow an intermediate symlink and miss the traversal.
    for component in path.ancestors().collect::<Vec<_>>().into_iter().rev() {
        if component.as_os_str().is_empty() {
            continue;
        }
        match std::fs::symlink_metadata(component) {
            Ok(metadata) if metadata.file_type().is_symlink() => {
                return Err(std::io::Error::other(format!(
                    "refusing symlink component {}",
                    component.display()
                )));
            }
            Ok(_) => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(error) => return Err(error),
        }
    }
    match std::fs::symlink_metadata(path) {
        Ok(metadata) => {
            if metadata.file_type().is_symlink() {
                return Err(std::io::Error::other(format!(
                    "refusing symlink target {}",
                    path.display()
                )));
            }
            #[cfg(unix)]
            {
                use std::os::unix::fs::MetadataExt;
                let trusted = std::env::var_os("HOME")
                    .and_then(|home| std::fs::metadata(home).ok())
                    .map(|home| home.uid());
                if trusted.is_some_and(|uid| uid != metadata.uid()) {
                    return Err(std::io::Error::other(format!(
                        "refusing unsafe ownership for {}",
                        path.display()
                    )));
                }
            }
            Ok(())
        }
        Err(e) if !must_exist && e.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(e),
    }
}

// ---------------------------------------------------------------------------
// POST /api/config
// ---------------------------------------------------------------------------
