//! (generated by module split — pure refactor, behavior identical)
#![allow(unused_imports)]

use std::collections::BTreeMap;
use std::path::PathBuf;
use std::process::Stdio;
use std::sync::Arc;

use anyhow::Result;
use axum::{
    Json, Router,
    extract::{Path as AxPath, State},
    http::StatusCode,
    response::{Html, IntoResponse},
    routing::{delete, get, post},
};
use rtrt_core::{
    OutputStyleLevel, read_output_style_level, read_output_style_level_for,
    write_output_style_level_for,
};
use rtrt_memory::{
    ClusterIndex, ConceptHierarchy, DetailedRecord, Embedder, MemoryStore, PayloadFilter,
    Summariser,
};
use rtrt_providers::{
    ChatMessage, ChatRequest, ChatResponse, Gateway, MetricsView, Prefer, Provider, RequestMetric,
    Role, RouteAlternative, RouteRequest, UsageSnapshot, select_route,
};
use rtrt_security::{Profile, ScanReport};
use rtrt_templates::{Prompt, PromptRegistry};
use serde::{Deserialize, Serialize};
use tokio::io::AsyncWriteExt;
use tokio::sync::Mutex;
use tokio::sync::broadcast;

use crate::prelude::*;

pub(crate) async fn healthz() -> &'static str {
    "ok"
}

pub(crate) async fn stats() -> Json<serde_json::Value> {
    Json(serde_json::json!({
        "input_saved": 0,
        "output_saved": 0,
        "provider": null,
    }))
}

/// Shared error reply for the project-aware config handlers.
pub(crate) fn clear_field_error(e: rtrt_core::Error) -> axum::response::Response {
    (
        StatusCode::INTERNAL_SERVER_ERROR,
        Json(serde_json::json!({ "error": e.to_string() })),
    )
        .into_response()
}

// ---------------------------------------------------------------------------
// GET/POST /api/providers/config
//
// Per-project active-provider + enabled overlay (`ProjectConfig.providers`).
// GET reports the effective active provider + each detected provider's enabled
// state (global, overlaid with the project override). POST writes the project
// override; `?scope=global` clears it (preserving coexisting overrides).
// ---------------------------------------------------------------------------

pub(crate) fn metadata_savings(raw: &str, expected_source: &str) -> Option<(i64, i64, i64)> {
    let value: serde_json::Value = serde_json::from_str(raw).ok()?;
    let obj = value.as_object()?;
    if obj.get("source")?.as_str()? != expected_source {
        return None;
    }
    let original_chars = json_i64(obj.get("compressed_from_chars")?)?.max(0);
    let compressed_to_chars = obj.get("compressed_to_chars").and_then(json_i64);
    // The stored `saved_chars` field is unreliable (observed 0 for a real
    // 309->117 compression, and 81 for a 68-char input). Always derive the
    // delta from compressed_from/to when `to` is present; only fall back to the
    // stored field when `to` is missing.
    let (saved_chars, with_rtrt_chars) = match compressed_to_chars {
        Some(to_chars) => ((original_chars - to_chars).max(0), to_chars.max(0)),
        None => {
            let stored = obj.get("saved_chars").and_then(json_i64)?.max(0);
            (stored, original_chars.saturating_sub(stored).max(0))
        }
    };
    Some((saved_chars, original_chars, with_rtrt_chars))
}

pub(crate) fn json_i64(value: &serde_json::Value) -> Option<i64> {
    if let Some(n) = value.as_i64() {
        return Some(n);
    }
    value.as_str()?.parse::<i64>().ok()
}

pub(crate) fn estimate_saved_tokens(saved_chars: i64) -> i64 {
    saved_chars / 4
}

pub(crate) fn saved_pct(saved_chars: i64, original_chars: i64) -> Option<f64> {
    if original_chars <= 0 {
        return None;
    }
    Some(saved_chars.max(0) as f64 / original_chars as f64 * 100.0)
}

pub(crate) fn saved_pct_or_zero(saved_chars: i64, original_chars: i64) -> f64 {
    saved_pct(saved_chars, original_chars).unwrap_or(0.0)
}

pub(crate) fn proxy_stats_path() -> PathBuf {
    std::env::var_os("HOME")
        .or_else(|| std::env::var_os("USERPROFILE"))
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".rtrt")
        .join("proxy-stats.sqlite")
}

pub(crate) fn normalize_project(project: Option<String>) -> String {
    let project = project.unwrap_or_default();
    let project = project.trim();
    if project.is_empty() {
        "(unknown)".to_string()
    } else {
        project.to_string()
    }
}

pub(crate) const SECS_PER_HOUR: i64 = 60 * 60;
pub(crate) const SECS_PER_DAY: i64 = SECS_PER_HOUR * 24;

pub(crate) async fn bearer_guard(
    expected: Option<Arc<String>>,
    req: axum::extract::Request,
    next: axum::middleware::Next,
) -> axum::response::Response {
    use axum::http::{HeaderValue, header::AUTHORIZATION};
    let path = req.uri().path().to_string();
    // Always allow the bundled HTML, health probe, and favicon so the UI can
    // bootstrap; the API routes still require the token.
    if matches!(path.as_str(), "/" | "/healthz" | "/favicon.ico") {
        return next.run(req).await;
    }
    let Some(expected) = expected else {
        return next.run(req).await;
    };
    let presented = req
        .headers()
        .get(AUTHORIZATION)
        .and_then(|v| v.to_str().ok())
        .and_then(|raw| raw.strip_prefix("Bearer "))
        .map(str::to_string);
    let ok = presented
        .as_deref()
        .is_some_and(|tok| constant_time_eq(tok.as_bytes(), expected.as_bytes()));
    if ok {
        return next.run(req).await;
    }
    let mut resp = axum::response::Response::new(axum::body::Body::from(
        "unauthorized: bearer token missing or invalid",
    ));
    *resp.status_mut() = StatusCode::UNAUTHORIZED;
    resp.headers_mut().insert(
        "WWW-Authenticate",
        HeaderValue::from_static("Bearer realm=\"rtrt-dashboard\""),
    );
    resp
}

pub(crate) fn constant_time_eq(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    let mut diff = 0u8;
    for (x, y) in a.iter().zip(b.iter()) {
        diff |= x ^ y;
    }
    diff == 0
}

pub(crate) fn walk_files(root: &std::path::Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let mut stack = vec![root.to_path_buf()];
    while let Some(p) = stack.pop() {
        let Ok(rd) = std::fs::read_dir(&p) else {
            continue;
        };
        for entry in rd.flatten() {
            let path = entry.path();
            if let Ok(ft) = entry.file_type() {
                if ft.is_dir() {
                    let name = entry.file_name();
                    let nstr = name.to_string_lossy();
                    if nstr == "target" || nstr.starts_with('.') {
                        continue;
                    }
                    stack.push(path);
                } else if ft.is_file() {
                    out.push(path);
                }
            }
        }
    }
    out
}

#[derive(Debug, Serialize)]
pub(crate) struct ApiError {
    error: String,
}

pub(crate) type DashboardJsonResult<T> = std::result::Result<Json<T>, (StatusCode, Json<ApiError>)>;

pub(crate) fn api_error(
    status: StatusCode,
    message: impl Into<String>,
) -> (StatusCode, Json<ApiError>) {
    (
        status,
        Json(ApiError {
            error: message.into(),
        }),
    )
}

pub(crate) fn write_config_file(
    cfg: &rtrt_core::Config,
) -> std::result::Result<String, (StatusCode, String)> {
    let path = rtrt_core::Config::default_path().ok_or((
        StatusCode::INTERNAL_SERVER_ERROR,
        "cannot determine config path".into(),
    ))?;

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| {
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("create dir {}: {e}", parent.display()),
            )
        })?;
    }

    let toml_str = toml::to_string_pretty(cfg)
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
    std::fs::write(&path, toml_str).map_err(|e| {
        (
            StatusCode::INTERNAL_SERVER_ERROR,
            format!("write {}: {e}", path.display()),
        )
    })?;
    Ok(path.to_string_lossy().into_owned())
}

// ---------------------------------------------------------------------------
// POST /api/config
// ---------------------------------------------------------------------------
