//! (generated by module split — pure refactor, behavior identical)
#![allow(unused_imports)]

use std::collections::BTreeMap;
use std::path::PathBuf;
use std::process::Stdio;
use std::sync::Arc;

use anyhow::Result;
use axum::{
    Json, Router,
    extract::{Path as AxPath, State},
    http::StatusCode,
    response::{Html, IntoResponse},
    routing::{delete, get, post},
};
use rtrt_core::{
    OutputStyleLevel, read_output_style_level, read_output_style_level_for,
    write_output_style_level_for,
};
use rtrt_memory::{
    ClusterIndex, ConceptHierarchy, DetailedRecord, Embedder, MemoryStore, PayloadFilter,
    Summariser,
};
use rtrt_providers::{
    ChatMessage, ChatRequest, ChatResponse, Gateway, MetricsView, Prefer, Provider, RequestMetric,
    Role, RouteAlternative, RouteRequest, UsageSnapshot, select_route,
};
use rtrt_security::{Profile, ScanReport};
use rtrt_templates::{Prompt, PromptRegistry};
use serde::{Deserialize, Serialize};
use tokio::io::AsyncWriteExt;
use tokio::sync::Mutex;
use tokio::sync::broadcast;

use crate::prelude::*;

#[derive(Debug, Deserialize)]
pub(crate) struct CompressRequest {
    text: String,
    #[serde(default)]
    level: Option<String>,
    #[serde(default)]
    ml: bool,
    #[serde(default)]
    ratio: Option<f32>,
    #[serde(default)]
    format: Option<String>,
    /// Engine selector: "rules" (default), "ml", or "llm".
    /// When "llm", `model` must be set; the gateway's configured base URL is used.
    #[serde(default)]
    engine: Option<String>,
    /// Model id passed to the gateway when `engine = "llm"`.
    #[serde(default)]
    model: Option<String>,
}

#[derive(Debug, Deserialize)]
pub(crate) struct ProxyRequest {
    /// Optional command label (e.g. `git status`, `cargo build`).
    #[serde(default)]
    command: Option<String>,
    /// Raw captured output to filter.
    raw: String,
    /// Filter mode: `command` (default — picks `filter_for(command)`),
    /// `errors_only`, or `ultra_compact`.
    #[serde(default)]
    mode: Option<String>,
    /// Context-line count for `errors_only` (default 3).
    #[serde(default = "default_context")]
    context: usize,
}

pub(crate) fn default_context() -> usize {
    3
}

pub(crate) async fn proxy_filter(
    State(state): State<AppState>,
    Json(req): Json<ProxyRequest>,
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    let mode = req.mode.as_deref().unwrap_or("command");
    let original = req.raw.chars().count();
    let out = match mode {
        "command" => {
            let cmd = req.command.as_deref().ok_or((
                StatusCode::BAD_REQUEST,
                "command required for command-mode".into(),
            ))?;
            match rtrt_proxy::filter_for(cmd) {
                Some(f) => f.apply(&req.raw),
                None => req.raw.clone(),
            }
        }
        "errors_only" => rtrt_proxy::errors_only(&req.raw, req.context),
        "ultra_compact" => rtrt_proxy::ultra_compact(&req.raw),
        other => return Err((StatusCode::BAD_REQUEST, format!("unknown mode: {other}"))),
    };
    let filtered = out.chars().count();
    let mut meta = BTreeMap::new();
    meta.insert("source".into(), "proxy".into());
    meta.insert("mode".into(), mode.to_string());
    if let Some(cmd) = req.command.as_deref() {
        meta.insert("command".into(), cmd.to_string());
    }
    meta.insert(
        "saved_chars".into(),
        original.saturating_sub(filtered).to_string(),
    );
    state.capture("proxy", &out, &meta).await;
    let saved_pct = if original > 0 {
        ((original.saturating_sub(filtered)) as f64 / original as f64 * 100.0 * 10.0).round() / 10.0
    } else {
        0.0
    };
    Ok(Json(serde_json::json!({
        "filtered": out,
        "mode": mode,
        "original_len": original,
        "filtered_len": filtered,
        "saved_chars": original.saturating_sub(filtered),
        "saved_pct": saved_pct,
    })))
}

#[derive(Debug, Deserialize)]
pub(crate) struct DiagnoseRequest {
    /// Raw captured output (typically build/test failure).
    raw: String,
    /// Model id to send to the gateway.
    model: String,
    /// errors_only context-line count.
    #[serde(default = "default_context")]
    context: usize,
    /// Optional system prompt override; defaults to the rtrt-cli triage prompt.
    #[serde(default)]
    system: Option<String>,
}

pub(crate) const DIAGNOSE_SYS: &str = "You are a senior engineer triaging a build / test failure. \
Read the captured error output and respond with: (1) one-sentence root cause; \
(2) the smallest concrete fix (file + change). No filler. Cite line numbers when present.";

pub(crate) async fn diagnose(
    State(state): State<AppState>,
    Json(req): Json<DiagnoseRequest>,
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    let filtered = rtrt_proxy::errors_only(&req.raw, req.context);
    let chat_req = ChatRequest {
        model: req.model.clone(),
        messages: vec![
            ChatMessage {
                role: Role::System,
                content: req.system.unwrap_or_else(|| DIAGNOSE_SYS.into()),
            },
            ChatMessage {
                role: Role::User,
                content: filtered.clone(),
            },
        ],
        max_tokens: Some(512),
        temperature: Some(0.1),
    };
    let resp = state
        .gateway
        .chat(chat_req)
        .await
        .map_err(|e| (StatusCode::BAD_GATEWAY, e.to_string()))?;
    let mut meta = BTreeMap::new();
    meta.insert("source".into(), "diagnose".into());
    meta.insert("provider".into(), resp.provider.clone());
    meta.insert("model".into(), resp.model.clone());
    state.capture("diagnose", &resp.content, &meta).await;
    Ok(Json(serde_json::json!({
        "diagnosis": resp.content,
        "filtered": filtered,
        "provider": resp.provider,
        "model": resp.model,
        "input_tokens": resp.usage.input_tokens,
        "output_tokens": resp.usage.output_tokens,
    })))
}

#[derive(Debug, Deserialize)]
pub(crate) struct RepoMapRequest {
    root: PathBuf,
    #[serde(default = "default_ext")]
    ext: String,
    #[serde(default = "default_max_bytes")]
    max_bytes: u64,
}

pub(crate) fn default_ext() -> String {
    // Empty = auto-detect via `Language::from_filename` (.rs / .py / .ts / .tsx).
    String::new()
}
pub(crate) fn default_max_bytes() -> u64 {
    524_288
}

pub(crate) async fn repo_map(
    Json(req): Json<RepoMapRequest>,
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    if !req.root.exists() {
        return Err((
            StatusCode::NOT_FOUND,
            format!("root not found: {}", req.root.display()),
        ));
    }
    let mut entries = Vec::new();
    let mut total_bytes: u64 = 0;
    let mut signature_chars: usize = 0;
    let restrict_ext = req.ext.trim();
    for entry in walk_files(&req.root) {
        let name = entry.to_string_lossy();
        if !restrict_ext.is_empty() && !name.ends_with(restrict_ext) {
            continue;
        }
        let Some(lang) = rtrt_compress::Language::from_filename(&name) else {
            continue;
        };
        let size = std::fs::metadata(&entry).map(|m| m.len()).unwrap_or(0);
        if size > req.max_bytes {
            continue;
        }
        let Ok(src) = std::fs::read_to_string(&entry) else {
            continue;
        };
        let extractor = rtrt_compress::SignatureExtractor::new(lang);
        let Ok(sig) = extractor.extract(&src) else {
            continue;
        };
        total_bytes += src.len() as u64;
        signature_chars += sig.chars().count();
        let rel = entry
            .strip_prefix(&req.root)
            .unwrap_or(&entry)
            .display()
            .to_string();
        entries.push(serde_json::json!({
            "path": rel,
            "language": format!("{lang:?}"),
            "signatures": sig,
            "original_bytes": src.len(),
            "signature_bytes": sig.len(),
        }));
    }
    Ok(Json(serde_json::json!({
        "files": entries.len(),
        "total_bytes": total_bytes,
        "signature_chars": signature_chars,
        "entries": entries,
    })))
}

#[derive(Debug, Deserialize)]
pub(crate) struct SetupRequest {
    agent: String,
    #[serde(default)]
    memory: Option<String>,
    #[serde(default)]
    binary: Option<String>,
}

pub(crate) async fn setup_snippet(
    Json(req): Json<SetupRequest>,
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    let binary = req.binary.clone().unwrap_or_else(|| "rtrt-mcp".to_string());
    let memory = req
        .memory
        .clone()
        .unwrap_or_else(|| ".rtrt/memory.sqlite".to_string());
    let (target_path, snippet) = match req.agent.as_str() {
        "claude-code" => (
            "~/.claude/mcp.json".to_string(),
            serde_json::to_string_pretty(&serde_json::json!({
                "mcpServers": {
                    "rtrt": {
                        "command": binary,
                        "args": ["--memory", memory]
                    }
                }
            }))
            .unwrap(),
        ),
        "cursor" => (
            "~/.cursor/mcp.json".to_string(),
            serde_json::to_string_pretty(&serde_json::json!({
                "mcpServers": {
                    "rtrt": {
                        "command": binary,
                        "args": ["--memory", memory]
                    }
                }
            }))
            .unwrap(),
        ),
        "codex" => (
            "~/.codex/config.toml".to_string(),
            format!(
                "[mcp.rtrt]\ncommand = \"{}\"\nargs = [\"--memory\", \"{}\"]\n",
                binary, memory
            ),
        ),
        other => {
            return Err((
                StatusCode::BAD_REQUEST,
                format!("unknown agent: {other} (try claude-code / cursor / codex)"),
            ));
        }
    };
    Ok(Json(serde_json::json!({
        "agent": req.agent,
        "target_path": target_path,
        "snippet": snippet,
    })))
}

pub(crate) const LLM_COMPRESS_SYS: &str = "You are a lossless-meaning compressor. Rewrite the user message \
in the shortest form that preserves every fact, decision, file path, identifier, command, and \
number. Drop filler, hedging, headings, and greetings. Plain text only. No commentary, no \
preamble, no quotes — emit only the compressed text.";

pub(crate) async fn compress(
    State(state): State<AppState>,
    Json(req): Json<CompressRequest>,
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    use rtrt_core::CompressionLevel;
    let original = req.text.chars().count();

    // Resolve the effective engine: explicit `engine` field wins; fall back to
    // the legacy `ml: true` boolean for backward compat.
    let engine = req
        .engine
        .as_deref()
        .unwrap_or(if req.ml { "ml" } else { "rules" });

    match engine {
        "llm" => {
            let model = req.model.clone().ok_or((
                StatusCode::BAD_REQUEST,
                "llm engine requires a `model` field".into(),
            ))?;
            // Build a request-scoped gateway that honours Config::auto_compress.base_url
            // when neither RTRT_PROVIDER_BASE_URL nor RTRT_OPENAI_COMPAT_URL is set —
            // the same resolution order used by run_hook_compress in rtrt-cli. state.gateway
            // was constructed at startup before config base_url was available, so we rebuild
            // here. When the env vars are absent we temporarily set RTRT_PROVIDER_BASE_URL
            // from config so Gateway::from_env registers the openai-compat provider.
            let llm_gateway = {
                let env_has_url = std::env::var_os("RTRT_PROVIDER_BASE_URL").is_some()
                    || std::env::var_os("RTRT_OPENAI_COMPAT_URL").is_some();
                if env_has_url {
                    rtrt_providers::Gateway::from_env()
                } else {
                    let cfg_url = rtrt_core::Config::load()
                        .ok()
                        .and_then(|c| c.auto_compress.base_url);
                    if let Some(url) = cfg_url {
                        // SAFETY: no await between set_var and remove_var; the var was
                        // absent before this block so concurrent handlers that reach this
                        // branch independently each set-and-remove their own value.
                        unsafe { std::env::set_var("RTRT_PROVIDER_BASE_URL", &url) };
                        let gw = rtrt_providers::Gateway::from_env();
                        unsafe { std::env::remove_var("RTRT_PROVIDER_BASE_URL") };
                        gw
                    } else {
                        rtrt_providers::Gateway::from_env()
                    }
                }
            };
            let chat_req = ChatRequest {
                model: model.clone(),
                messages: vec![
                    ChatMessage {
                        role: Role::System,
                        content: LLM_COMPRESS_SYS.to_string(),
                    },
                    ChatMessage {
                        role: Role::User,
                        content: req.text.clone(),
                    },
                ],
                max_tokens: Some(
                    // Cap at 4× the original char count but at least 128 tokens.
                    (original as u32).saturating_mul(4).clamp(128, 4096),
                ),
                temperature: Some(0.0),
            };
            let resp = llm_gateway
                .chat(chat_req)
                .await
                .map_err(|e| (StatusCode::BAD_GATEWAY, e.to_string()))?;
            let out = resp.content.trim().to_string();
            let compressed = out.chars().count();
            let mut meta = BTreeMap::new();
            meta.insert("source".into(), "compress".into());
            meta.insert("mode".into(), "llm".into());
            meta.insert("model".into(), model.clone());
            meta.insert(
                "saved_chars".into(),
                original.saturating_sub(compressed).to_string(),
            );
            state.capture("compress", &out, &meta).await;
            let saved = original.saturating_sub(compressed);
            let saved_pct = if original > 0 {
                (saved as f64 / original as f64 * 100.0 * 10.0).round() / 10.0
            } else {
                0.0
            };
            Ok(Json(serde_json::json!({
                "compressed": out,
                "mode": "llm",
                "model": model,
                "original_len": original,
                "compressed_len": compressed,
                "saved": saved,
                "saved_chars": saved,
                "saved_pct": saved_pct,
            })))
        }

        "ml" => {
            let target = rtrt_compress::CompressionTarget::new(req.ratio.unwrap_or(0.5))
                .map_err(|e| (StatusCode::BAD_REQUEST, e.to_string()))?;
            let c = rtrt_compress::MlCompressor::heuristic();
            let scorer = c.scorer_name().to_string();
            let out = c.compress(&req.text, target);
            let compressed = out.chars().count();
            let mut meta = BTreeMap::new();
            meta.insert("source".into(), "compress".into());
            meta.insert("mode".into(), "ml".into());
            meta.insert("scorer".into(), scorer.clone());
            meta.insert(
                "saved_chars".into(),
                original.saturating_sub(compressed).to_string(),
            );
            state.capture("compress", &out, &meta).await;
            let saved = original.saturating_sub(compressed);
            let saved_pct = if original > 0 {
                (saved as f64 / original as f64 * 100.0 * 10.0).round() / 10.0
            } else {
                0.0
            };
            Ok(Json(serde_json::json!({
                "compressed": out,
                "mode": "ml",
                "scorer": scorer,
                "original_len": original,
                "compressed_len": compressed,
                "saved": saved,
                "saved_chars": saved,
                "saved_pct": saved_pct,
            })))
        }

        // "rules" or any unrecognised value — run the rule-based compressor.
        _ => {
            let level = match req.level.as_deref().unwrap_or("full") {
                "lite" => CompressionLevel::Lite,
                "full" => CompressionLevel::Full,
                "ultra" => CompressionLevel::Ultra,
                "extreme" => CompressionLevel::Extreme,
                other => {
                    return Err((StatusCode::BAD_REQUEST, format!("unknown level: {other}")));
                }
            };
            let compressor = rtrt_compress::Compressor::new(level);
            let format = req
                .format
                .as_deref()
                .and_then(rtrt_compress::OutputFormat::parse)
                .unwrap_or(rtrt_compress::OutputFormat::Plain);
            let out = compressor.compress_to(&req.text, format);
            let compressed = out.chars().count();
            let mut meta = BTreeMap::new();
            meta.insert("source".into(), "compress".into());
            meta.insert("mode".into(), "rules".into());
            meta.insert(
                "saved_chars".into(),
                original.saturating_sub(compressed).to_string(),
            );
            state.capture("compress", &out, &meta).await;
            let saved = original.saturating_sub(compressed);
            let saved_pct = if original > 0 {
                (saved as f64 / original as f64 * 100.0 * 10.0).round() / 10.0
            } else {
                0.0
            };
            Ok(Json(serde_json::json!({
                "compressed": out,
                "mode": "rules",
                "original_len": original,
                "compressed_len": compressed,
                "saved": saved,
                "saved_chars": saved,
                "saved_pct": saved_pct,
            })))
        }
    }
}
