//! (generated by module split — pure refactor, behavior identical)
#![allow(unused_imports)]

use std::collections::BTreeMap;
use std::path::PathBuf;
use std::process::Stdio;
use std::sync::Arc;

use anyhow::Result;
use axum::{
    Json, Router,
    extract::{Path as AxPath, State},
    http::StatusCode,
    response::{Html, IntoResponse},
    routing::{delete, get, post},
};
use rtrt_core::{
    OutputStyleLevel, read_output_style_level, read_output_style_level_for,
    write_output_style_level_for,
};
use rtrt_memory::{
    ClusterIndex, ConceptHierarchy, DetailedRecord, Embedder, MemoryStore, PayloadFilter,
    Summariser,
};
use rtrt_providers::{
    ChatMessage, ChatRequest, ChatResponse, Gateway, MetricsView, Prefer, Provider, RequestMetric,
    Role, RouteAlternative, RouteRequest, UsageSnapshot, select_route,
};
use rtrt_security::{Profile, ScanReport};
use rtrt_templates::{Prompt, PromptRegistry};
use serde::{Deserialize, Serialize};
use tokio::io::AsyncWriteExt;
use tokio::sync::Mutex;
use tokio::sync::broadcast;

use crate::prelude::*;

#[derive(Debug, Serialize)]
pub(crate) struct ConfigResponse {
    capture: rtrt_core::config::CaptureConfig,
    auto_compress: rtrt_core::config::AutoCompressConfig,
    embeddings: rtrt_core::config::EmbeddingsConfig,
    security: rtrt_core::config::SecurityConfig,
    path: String,
}

pub(crate) async fn get_config() -> std::result::Result<Json<ConfigResponse>, (StatusCode, String)>
{
    let cfg = rtrt_core::Config::load()
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
    let path = rtrt_core::Config::default_path()
        .map(|p| p.to_string_lossy().into_owned())
        .unwrap_or_default();
    Ok(Json(ConfigResponse {
        capture: cfg.capture,
        auto_compress: cfg.auto_compress,
        embeddings: cfg.embeddings,
        security: cfg.security,
        path,
    }))
}

// ---------------------------------------------------------------------------
// GET/POST /api/statusline/config + GET /api/statusline/preview
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
pub(crate) struct ConfigWriteRequest {
    capture: rtrt_core::config::CaptureConfig,
    auto_compress: rtrt_core::config::AutoCompressConfig,
    /// Optional so older dashboard builds (no embeddings UI) still POST cleanly;
    /// when absent the on-disk embeddings section is preserved untouched.
    #[serde(default)]
    embeddings: Option<rtrt_core::config::EmbeddingsConfig>,
    /// Optional global security defaults (default profile). Preserved when absent.
    #[serde(default)]
    security: Option<rtrt_core::config::SecurityConfig>,
}

#[derive(Debug, Serialize)]
pub(crate) struct ConfigWriteResponse {
    ok: bool,
    path: String,
}

pub(crate) async fn post_config(
    Json(req): Json<ConfigWriteRequest>,
) -> std::result::Result<Json<ConfigWriteResponse>, (StatusCode, String)> {
    // Build an updated Config preserving any non-exposed fields from disk.
    let mut cfg = rtrt_core::Config::load()
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
    cfg.capture = req.capture;
    cfg.auto_compress = req.auto_compress;
    if let Some(emb) = req.embeddings {
        cfg.embeddings = emb;
    }
    if let Some(sec) = req.security {
        cfg.security = sec;
    }

    let path = rtrt_core::Config::default_path().ok_or((
        StatusCode::INTERNAL_SERVER_ERROR,
        "cannot determine config path".into(),
    ))?;

    // Create parent directory if needed.
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| {
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("create dir {}: {e}", parent.display()),
            )
        })?;
    }

    // Back up the existing file before overwriting.
    if path.exists() {
        let bak = path.with_extension("toml.bak");
        std::fs::copy(&path, &bak).map_err(|e| {
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("backup {}: {e}", path.display()),
            )
        })?;
    }

    let toml_str = toml::to_string_pretty(&cfg)
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
    std::fs::write(&path, toml_str).map_err(|e| {
        (
            StatusCode::INTERNAL_SERVER_ERROR,
            format!("write {}: {e}", path.display()),
        )
    })?;

    Ok(Json(ConfigWriteResponse {
        ok: true,
        path: path.to_string_lossy().into_owned(),
    }))
}

// ---------------------------------------------------------------------------
// GET/POST /api/memory/settings
//
// Global `[memory]` section: the on-disk memory store `path` and the
// `embed_model` name. Plain global settings (no per-project scope toggle) —
// persisted to `~/.rtrt/config.toml` via `write_config_file`.
//
// `path` is editable but flagged on the client with a warning, because pointing
// it at a different file makes the dashboard/CLI read a *different* store; the
// change only takes effect after a restart (the running server keeps its open
// handle). `embed_model` is a free-text input.
// ---------------------------------------------------------------------------

#[derive(Debug, Serialize)]
pub(crate) struct MemorySettingsResponse {
    /// Memory store path as configured (may be relative, e.g. the default
    /// `.rtrt/memory.sqlite`).
    path: String,
    embed_model: String,
    /// Config file the values live in (so the UI can show provenance).
    config_path: String,
}

fn memory_settings_response(cfg: &rtrt_core::Config) -> MemorySettingsResponse {
    let config_path = rtrt_core::Config::default_path()
        .map(|p| p.to_string_lossy().into_owned())
        .unwrap_or_default();
    MemorySettingsResponse {
        path: cfg.memory.path.to_string_lossy().into_owned(),
        embed_model: cfg.memory.embed_model.clone(),
        config_path,
    }
}

pub(crate) async fn get_memory_settings()
-> std::result::Result<Json<MemorySettingsResponse>, (StatusCode, String)> {
    let cfg = rtrt_core::Config::load()
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
    Ok(Json(memory_settings_response(&cfg)))
}

#[derive(Debug, Deserialize)]
pub(crate) struct SetMemorySettingsRequest {
    /// New memory store path. Absent/empty keeps the existing path.
    #[serde(default)]
    path: Option<String>,
    /// New embedding model name. Absent/empty keeps the existing model.
    #[serde(default)]
    embed_model: Option<String>,
}

pub(crate) async fn post_memory_settings(
    Json(req): Json<SetMemorySettingsRequest>,
) -> std::result::Result<Json<MemorySettingsResponse>, (StatusCode, String)> {
    let mut cfg = rtrt_core::Config::load()
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
    if let Some(path) = req.path.as_deref().map(str::trim).filter(|s| !s.is_empty()) {
        cfg.memory.path = std::path::PathBuf::from(path);
    }
    if let Some(model) = req
        .embed_model
        .as_deref()
        .map(str::trim)
        .filter(|s| !s.is_empty())
    {
        cfg.memory.embed_model = model.to_string();
    }
    write_config_file(&cfg)?;
    Ok(Json(memory_settings_response(&cfg)))
}

// ---------------------------------------------------------------------------
// GET /api/models
// ---------------------------------------------------------------------------

#[derive(Debug, Serialize)]
pub(crate) struct ModelEntry {
    id: String,
    source: &'static str,
}

#[derive(Debug, Serialize)]
pub(crate) struct ModelsResponse {
    models: Vec<ModelEntry>,
}

pub(crate) async fn get_models() -> Json<ModelsResponse> {
    let cfg = rtrt_core::Config::load().unwrap_or_default();
    // Derive the Ollama host root: strip a trailing `/v1` (OpenAI-compat
    // path prefix) and any trailing slash so `/api/tags` lands at the right
    // place regardless of how base_url was configured.
    let ollama_host = cfg
        .auto_compress
        .base_url
        .as_deref()
        .unwrap_or("http://127.0.0.1:11434")
        .trim_end_matches('/')
        .trim_end_matches("/v1")
        .trim_end_matches('/')
        .to_string();

    let mut models: Vec<ModelEntry> = Vec::new();

    // Attempt to list Ollama models; any failure is silently ignored.
    let ollama_url = format!("{ollama_host}/api/tags");
    if let Ok(resp) = reqwest::Client::new()
        .get(&ollama_url)
        .timeout(std::time::Duration::from_secs(3))
        .send()
        .await
    {
        if let Ok(body) = resp.json::<serde_json::Value>().await {
            if let Some(arr) = body.get("models").and_then(|v| v.as_array()) {
                for m in arr {
                    if let Some(name) = m.get("name").and_then(|v| v.as_str()) {
                        models.push(ModelEntry {
                            id: name.to_string(),
                            source: "ollama",
                        });
                    }
                }
            }
        }
    }

    // Always append the cloud defaults.
    models.push(ModelEntry {
        id: "claude-haiku-4-5".to_string(),
        source: "cloud",
    });
    models.push(ModelEntry {
        id: "gpt-5.4-mini".to_string(),
        source: "cloud",
    });

    Json(ModelsResponse { models })
}

// ---------------------------------------------------------------------------
// POST /api/memory/compress
// ---------------------------------------------------------------------------
