//! (generated by module split — pure refactor, behavior identical)
#![allow(unused_imports)]

use std::collections::BTreeMap;
use std::path::PathBuf;
use std::process::Stdio;
use std::sync::Arc;

use anyhow::Result;
use axum::{
    Json, Router,
    extract::{Path as AxPath, State},
    http::StatusCode,
    response::{Html, IntoResponse},
    routing::{delete, get, post},
};
use rtrt_core::{
    OutputStyleLevel, read_output_style_level, read_output_style_level_for,
    write_output_style_level_for,
};
use rtrt_memory::{
    ClusterIndex, ConceptHierarchy, DetailedRecord, Embedder, MemoryStore, PayloadFilter,
    Summariser,
};
use rtrt_providers::{
    ChatMessage, ChatRequest, ChatResponse, Gateway, MetricsView, Prefer, Provider, RequestMetric,
    Role, RouteAlternative, RouteRequest, UsageSnapshot, select_route,
};
use rtrt_security::{Profile, ScanReport};
use rtrt_templates::{Prompt, PromptRegistry};
use serde::{Deserialize, Serialize};
use tokio::io::AsyncWriteExt;
use tokio::sync::Mutex;
use tokio::sync::broadcast;

use crate::prelude::*;

#[derive(Debug, Deserialize)]
pub(crate) struct MemoryGraphQuery {
    #[serde(default)]
    project: String,
    #[serde(default = "default_graph_limit")]
    limit: usize,
    /// `similarity` (default — memory↔memory, no LLM), `entity` (bipartite
    /// memory↔entity, requires entity extraction), or `overview` (LOD cluster
    /// bubbles for large graphs).
    #[serde(default)]
    mode: Option<String>,
    /// Top-level grouping basis for `mode=overview`: `context` (semantic,
    /// default) | `file` | `kind` | `session` | `source`.
    #[serde(default)]
    group: Option<String>,
    /// Multi-level drill token (opaque, server-minted). Takes precedence over
    /// every other param: the server resolves it to a member-id set and either
    /// re-subclusters (deeper `group` level) or returns a `leaf`.
    #[serde(default)]
    token: Option<String>,
    /// Legacy drill-down by cluster root id (kept for the old frontend path);
    /// superseded by `token`.
    #[serde(default)]
    cluster: Option<i64>,
    /// Clustering basis the user picked on the map for `group=context`:
    /// `auto` (default — coverage decides) | `vector` (force semantic/embeddings)
    /// | `lexical` (force keyword). Overrides the per-project default.
    #[serde(default)]
    basis: Option<String>,
    /// Granularity ("세밀도"): overview bubble target. More bubbles = a smaller
    /// unclustered/"미분류" catch-all. Clamped server-side. `None` = default.
    #[serde(default)]
    target: Option<usize>,
    /// Drill depth ("깊이"): leaf cutoff — a bubble at/under this many members
    /// renders individual nodes. `None`/`0` = dynamic (~√total).
    #[serde(default)]
    leaf: Option<usize>,
    /// `mode=brain` concept drill: when set, return the memories containing this
    /// concept token (the `brain-concept` response) instead of the brain graph.
    #[serde(default)]
    concept: Option<String>,
    /// `mode=brain` community drill: the stable community id (the `mode=brain`
    /// community-level node's numeric id). When set — and `concept` is not — the
    /// response is that community's CONCEPT sub-graph (`level:"concept"`) instead
    /// of the top-level community overview.
    #[serde(default)]
    community: Option<i64>,
}

pub(crate) fn default_graph_limit() -> usize {
    // Keep the default modest: a force-directed graph past ~80 nodes is a
    // hairball, and the BM25 fallback path costs one FTS query per node.
    80
}

pub(crate) async fn memory_graph(
    State(state): State<AppState>,
    axum::extract::Query(q): axum::extract::Query<MemoryGraphQuery>,
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    let store = state
        .memory
        .as_ref()
        .ok_or((StatusCode::SERVICE_UNAVAILABLE, "memory disabled".into()))?;

    // ── Token drill (highest precedence) ────────────────────────────────────
    // A drill token resolves to a member-id set. Tiny sets render as a `leaf`
    // (individual memory nodes); larger sets re-subcluster into sub-bubbles
    // (each minted a fresh child token). All resolved before holding the
    // `!Send` store guard across an `.await`.
    if let Some(tok) = q.token.clone() {
        return memory_graph_drill(&state, store, tok, q.leaf).await;
    }

    // LOD drill-down (`cluster=<root>`): return the members of one cluster from
    // the cached index. Rebuilds the index if missing/expired. Checked before
    // `mode` so a drill-down request needs no extra `mode=` param. Resolved
    // before the long-lived store guard below so the `!Send` store reference is
    // never held across an `.await`. Superseded by `token`, kept for the old UI.
    if let Some(root_id) = q.cluster {
        let index = cluster_index_cached(&state, store, &q.project).await?;
        let members = {
            let guard = store.lock().await;
            guard
                .cluster_members(&q.project, root_id, &index)
                .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?
        };
        let nodes: Vec<serde_json::Value> = members
            .nodes
            .iter()
            .map(|m| {
                serde_json::json!({
                    "id": format!("m{}", m.id),
                    "node_type": "memory",
                    "label": m.preview,
                    "kind": m.kind,
                    "source_kind": m.source_kind,
                })
            })
            .collect();
        let edges: Vec<serde_json::Value> = members
            .edges
            .iter()
            .map(|(a, b, w)| serde_json::json!({"src": format!("m{a}"), "dst": format!("m{b}"), "weight": w}))
            .collect();
        return Ok(Json(serde_json::json!({
            "mode": "cluster",
            "root": root_id,
            "nodes": nodes,
            "edges": edges,
        })));
    }

    // LOD overview (`mode=overview&group=<basis>`): server-side top-level
    // grouping of the whole project. Returns ONLY bubble summaries (each with a
    // drill token) + aggregated inter-cluster edges, never individual nodes —
    // this scales to hundreds of thousands of rows. `group=context` (default)
    // clusters semantically; any other basis buckets by a metadata facet.
    if q.mode.as_deref() == Some("overview") {
        let group = q.group.as_deref().unwrap_or("context");
        let basis = q.basis.as_deref().unwrap_or("auto");
        return memory_graph_overview(&state, store, &q.project, group, basis, q.target).await;
    }

    // Brain mode (`mode=brain`): the three-level "digital brain" map. Scope
    // resolves the same way the project selector does — a present, non-sentinel
    // project is one project's brain; an empty string or the `__global__`
    // sentinel is the GLOBAL brain (all projects merged by concept token). Drill
    // precedence (per contract):
    //   1. `concept=TOKEN` → that concept's MEMORIES   (`mode:"brain-concept"`)
    //   2. `community=ID`   → that community's CONCEPTS (`level:"concept"`)
    //   3. neither          → TOP-LEVEL communities     (`level:"community"`)
    if q.mode.as_deref() == Some("brain") {
        let scope: Option<&str> = brain_scope(&q.project);
        if let Some(concept) = q.concept.as_deref().filter(|c| !c.is_empty()) {
            return memory_graph_brain_concept(store, scope, concept).await;
        }
        if let Some(community_id) = q.community {
            return memory_graph_brain_community(store, scope, community_id).await;
        }
        return memory_graph_brain(&state, store, &q.project, scope).await;
    }

    let guard = store.lock().await;

    // Entity mode: bipartite memory↔entity graph (needs extracted entities).
    if q.mode.as_deref() == Some("entity") {
        let graph = guard
            .graph_bipartite(&q.project, q.limit)
            .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
        let mut nodes: Vec<serde_json::Value> =
            Vec::with_capacity(graph.memories.len() + graph.entities.len());
        for m in &graph.memories {
            nodes.push(serde_json::json!({
                "id": format!("m{}", m.id),
                "node_type": "memory",
                "label": m.preview,
                "kind": m.kind,
                "source_kind": m.source_kind,
            }));
        }
        for e in &graph.entities {
            nodes.push(serde_json::json!({
                "id": format!("e{}", e.id),
                "node_type": "entity",
                "label": e.name,
                "degree": e.degree,
            }));
        }
        let edges: Vec<serde_json::Value> = graph
            .links
            .iter()
            .map(|(mem_id, ent_id)| serde_json::json!({"src": format!("m{mem_id}"), "dst": format!("e{ent_id}")}))
            .collect();
        return Ok(Json(serde_json::json!({
            "mode": "entity",
            "nodes": nodes,
            "edges": edges,
        })));
    }

    // Default similarity mode: memory↔memory, no generative LLM (cosine over
    // stored embeddings, or BM25 lexical fallback).
    let graph = guard
        .graph_similarity(&q.project, q.limit, 4, 0.15)
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
    let nodes: Vec<serde_json::Value> = graph
        .memories
        .iter()
        .map(|m| {
            serde_json::json!({
                "id": format!("m{}", m.id),
                "node_type": "memory",
                "label": m.preview,
                "kind": m.kind,
                "source_kind": m.source_kind,
            })
        })
        .collect();
    let edges: Vec<serde_json::Value> = graph
        .edges
        .iter()
        .map(|(a, b, w)| serde_json::json!({"src": format!("m{a}"), "dst": format!("m{b}"), "weight": w}))
        .collect();
    Ok(Json(serde_json::json!({
        "mode": "similarity",
        "basis": graph.basis,
        "nodes": nodes,
        "edges": edges,
    })))
}

/// LOD parameters for whole-project clustering. `max_nodes` is a safety bound
/// (newest first); `top_k` peers per node feed union-find; `min_weight` is the
/// candidate-edge threshold for joining two nodes into one cluster.
pub(crate) const CLUSTER_MAX_NODES: usize = 200_000;

pub(crate) const CLUSTER_TOP_K: usize = 4;
pub(crate) const CLUSTER_MIN_WEIGHT: f32 = 0.15;

/// "Digital brain" min co-occurrence (`mode=brain`): 2 just means "co-occurred
/// in at least two memories" — a property, not a cap. The concept/edge budget
/// and the community-fold target are sized dynamically by rtrt-memory (AUTO).
pub(crate) const BRAIN_MIN_COOCCUR: usize = 2;

/// The global-scope sentinel value the project selector sends for "all projects
/// merged into one brain" (mirrors `GLOBAL_PROJECT_VALUE` in the frontend). An
/// empty project string is treated as global too.
pub(crate) const GLOBAL_PROJECT_SENTINEL: &str = "__global__";

/// Map a raw `project` query param to a [`MemoryStore::concept_graph`] scope:
/// `None` (GLOBAL, all projects merged) for an empty string or the global
/// sentinel, else `Some(project)` for one project's brain.
pub(crate) fn brain_scope(project: &str) -> Option<&str> {
    if project.is_empty() || project == GLOBAL_PROJECT_SENTINEL {
        None
    } else {
        Some(project)
    }
}

/// TOP LEVEL of the brain (`mode=brain`, no `community`/`concept` param): build
/// (or serve from the 60s cache) the per-scope TOPIC-COMMUNITY hierarchy and
/// return the documented `level:"community"` JSON. A few dozen super-nodes
/// (`kind:"community"`) replace the hundreds-of-concepts hairball; drilling a
/// node (`community=ID`) yields its concepts. Cached in
/// [`AppState::brainh_cache`] under `"brainh\x1f<scope>"`, the same TTL + style
/// as the LOD cluster cache.
///
/// The store is `!Send`, so the build runs inside a synchronous block with no
/// `.await` while the guard is held — keeping the future `Send` for axum.
pub(crate) async fn memory_graph_brain(
    state: &AppState,
    store: &Arc<Mutex<MemoryStore>>,
    project: &str,
    scope: Option<&str>,
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    let hierarchy = brain_hierarchy_cached(state, store, project, scope).await?;

    let nodes: Vec<serde_json::Value> = hierarchy
        .communities
        .iter()
        .map(|c| {
            serde_json::json!({
                "id": format!("k:{}", c.id),
                "label": c.label,
                "size": c.size,
                "concept_count": c.concept_count,
                "top_concepts": c.top_concepts,
                "kind": "community",
            })
        })
        .collect();
    let edges: Vec<serde_json::Value> = hierarchy
        .edges
        .iter()
        .map(|(a, b, w)| {
            serde_json::json!({"src": format!("k:{a}"), "dst": format!("k:{b}"), "weight": w})
        })
        .collect();
    Ok(Json(serde_json::json!({
        "mode": "brain",
        "level": "community",
        "scope": if scope.is_none() { "global" } else { "project" },
        "total_memories": hierarchy.total_memories,
        "total_concepts": hierarchy.total_concepts,
        "nodes": nodes,
        "edges": edges,
    })))
}

/// Build (or serve from the 60s cache) the per-scope [`ConceptHierarchy`].
/// Cached in [`AppState::brainh_cache`] under `"brainh\x1f<scope>"`, the same
/// TTL + style as the LOD cluster + flat-brain caches.
///
/// The store is `!Send`, so the build runs inside a synchronous block with no
/// `.await` while the guard is held — keeping the future `Send` for axum.
pub(crate) async fn brain_hierarchy_cached(
    state: &AppState,
    store: &Arc<Mutex<MemoryStore>>,
    project: &str,
    scope: Option<&str>,
) -> std::result::Result<ConceptHierarchy, (StatusCode, String)> {
    let scope_key = if scope.is_none() {
        GLOBAL_PROJECT_SENTINEL
    } else {
        project
    };
    let cache_key = format!("brainh\x1f{scope_key}");

    // Fast path: serve a still-fresh cached hierarchy.
    let cached = {
        let cache = state.brainh_cache.lock().await;
        match cache.get(&cache_key) {
            Some((built_at, h)) if built_at.elapsed() < CLUSTER_INDEX_TTL => Some(h.clone()),
            _ => None,
        }
    };
    if let Some(h) = cached {
        return Ok(h);
    }

    // Miss / expired: rebuild under the store lock (no await inside).
    let hierarchy = {
        let guard = store.lock().await;
        guard
            .concept_communities(scope, BRAIN_MIN_COOCCUR)
            .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?
    };
    let mut cache = state.brainh_cache.lock().await;
    cache.insert(cache_key, (std::time::Instant::now(), hierarchy.clone()));
    Ok(hierarchy)
}

/// MIDDLE LEVEL of the brain (`mode=brain&community=ID`): the concept sub-graph
/// for ONE topic community — its member concepts + the intra-community edges,
/// via [`MemoryStore::community_concepts`]. Returns the documented
/// `level:"concept"` JSON (concept nodes keyed `c:<token>`). An unknown id
/// yields an empty graph (the memory layer's contract), rendered as zero nodes.
pub(crate) async fn memory_graph_brain_community(
    store: &Arc<Mutex<MemoryStore>>,
    scope: Option<&str>,
    community_id: i64,
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    let graph = {
        let guard = store.lock().await;
        guard
            .community_concepts(scope, community_id, BRAIN_MIN_COOCCUR)
            .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?
    };

    let nodes: Vec<serde_json::Value> = graph
        .nodes
        .iter()
        .map(|c| {
            serde_json::json!({
                "id": format!("c:{}", c.name),
                "label": c.name,
                "degree": c.degree,
                "freq": c.freq,
                "projects": c.projects,
            })
        })
        .collect();
    let edges: Vec<serde_json::Value> = graph
        .edges
        .iter()
        .map(|(a, b, w)| {
            serde_json::json!({"src": format!("c:{a}"), "dst": format!("c:{b}"), "weight": w})
        })
        .collect();
    Ok(Json(serde_json::json!({
        "mode": "brain",
        "level": "concept",
        "community": community_id,
        "nodes": nodes,
        "edges": edges,
    })))
}

/// Drill one concept: return the memories containing `concept` (newest first,
/// capped) as the documented `mode=brain-concept` JSON.
pub(crate) async fn memory_graph_brain_concept(
    store: &Arc<Mutex<MemoryStore>>,
    scope: Option<&str>,
    concept: &str,
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    // Show ALL of a concept's memories — the count is naturally its frequency,
    // not an arbitrary cap. usize::MAX = "no limit".
    let rows = {
        let guard = store.lock().await;
        guard
            .concept_memories(scope, concept, usize::MAX)
            .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?
    };
    let nodes: Vec<serde_json::Value> = rows
        .iter()
        .map(|(m, project)| {
            serde_json::json!({
                "id": format!("m{}", m.id),
                "node_type": "memory",
                "label": m.preview,
                "kind": m.kind,
                "source_kind": m.source_kind,
                "project": project,
            })
        })
        .collect();
    Ok(Json(serde_json::json!({
        "mode": "brain-concept",
        "concept": concept,
        "nodes": nodes,
        "edges": [],
    })))
}

/// Return a fresh [`ClusterIndex`] for `project`, served from the per-project
/// cache when the entry is younger than [`CLUSTER_INDEX_TTL`]; otherwise rebuild
/// it via [`MemoryStore::graph_clusters`] and refresh the cache.
///
/// The store is `!Send` (it wraps a `rusqlite::Connection`), so the build runs
/// inside a synchronous block with no `.await` while the store guard is held —
/// keeping the returned future `Send` for axum.
pub(crate) async fn cluster_index_cached(
    state: &AppState,
    store: &Arc<Mutex<MemoryStore>>,
    project: &str,
) -> std::result::Result<ClusterIndex, (StatusCode, String)> {
    // Fast path: serve a still-fresh cached index.
    {
        let cache = state.cluster_cache.lock().await;
        if let Some((built_at, index)) = cache.get(project)
            && built_at.elapsed() < CLUSTER_INDEX_TTL
        {
            return Ok(index.clone());
        }
    }
    // Miss / expired: rebuild under the store lock (no await inside this block).
    let index = {
        let guard = store.lock().await;
        guard
            .graph_clusters(
                project,
                CLUSTER_MAX_NODES,
                CLUSTER_TOP_K,
                CLUSTER_MIN_WEIGHT,
            )
            .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?
    };
    let mut cache = state.cluster_cache.lock().await;
    cache.insert(
        project.to_string(),
        (std::time::Instant::now(), index.clone()),
    );
    Ok(index)
}

/// Cache-key separator for the `(project, group)` overview cache.
pub(crate) const CACHE_KEY_SEP: char = '\u{1f}';

/// Build (or serve cached) a top-level overview keyed by `(project, group)`.
///
/// `group=context` clusters semantically via [`MemoryStore::graph_clusters`];
/// any other valid basis (`file`/`kind`/`session`/`source`) buckets by that
/// metadata facet via [`MemoryStore::group_meta`]. Each emitted bubble is
/// minted a fresh drill token (mapping to its member ids) so the client can
/// drill arbitrarily deep without ever shipping id lists. Expired tokens (and
/// stale tokens of this same project) are pruned on every build to bound growth.
pub(crate) async fn memory_graph_overview(
    state: &AppState,
    store: &Arc<Mutex<MemoryStore>>,
    project: &str,
    group: &str,
    basis_pref: &str,
    target_pref: Option<usize>,
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    // `context` is semantic; everything else is a metadata facet. Reject an
    // unknown basis up front (group_meta also rejects, but a 400 is clearer).
    let is_context = group == "context";
    if !is_context && !matches!(group, "file" | "kind" | "session" | "source" | "time") {
        return Err((
            StatusCode::BAD_REQUEST,
            format!("unknown group `{group}` (expected context|file|kind|session|source|time)"),
        ));
    }

    // 자동 default = per-project embedding toggle else global `[embeddings] enabled`.
    let allow_vector_default = {
        let cfg = rtrt_core::Config::load().unwrap_or_default();
        cfg.project(project)
            .and_then(|p| p.embeddings_enabled)
            .unwrap_or_else(|| cfg.embeddings.is_enabled())
    };
    // The map's 기준 selector: auto | vector(의미) | lexical(어휘).
    let basis_pref = match basis_pref {
        "vector" | "lexical" => basis_pref,
        _ => "auto",
    };
    // 세밀도(granularity): bubble target. Explicit value (clamped) wins; otherwise
    // default to a clean, airy count — Memory stays uncluttered by distilling
    // to few-but-meaningful nodes, so scale gently with project size (~sqrt(n))
    // and clamp low: a 20k project lands ~140 bubbles, a small project ~60.
    let target = match target_pref {
        Some(t) => t.clamp(24, 1000),
        None => {
            let n = {
                let guard = store.lock().await;
                guard.count_by_project(project).unwrap_or(0)
            };
            (n as f64).sqrt().round().clamp(60.0, 200.0) as usize
        }
    };

    // Key the cache on every knob so a different selection never serves a stale
    // opposite-basis / opposite-granularity index.
    let cache_key = format!(
        "{project}{CACHE_KEY_SEP}{group}{CACHE_KEY_SEP}{basis_pref}{CACHE_KEY_SEP}{target}{CACHE_KEY_SEP}{}",
        allow_vector_default as u8
    );

    // Fast path: serve a still-fresh cached index (re-mint tokens against it).
    let cached = {
        let cache = state.cluster_cache.lock().await;
        cache.get(&cache_key).and_then(|(built_at, index)| {
            (built_at.elapsed() < CLUSTER_INDEX_TTL).then(|| index.clone())
        })
    };
    let index = match cached {
        Some(idx) => idx,
        None => {
            // Miss / expired: rebuild under the store lock (no await inside).
            let idx = {
                let guard = store.lock().await;
                if is_context {
                    match basis_pref {
                        // Force semantic: cluster on vectors even at low coverage
                        // (the map then covers only the embedded rows).
                        "vector" => guard
                            .graph_clusters_vec(project, CLUSTER_MAX_NODES, CLUSTER_TOP_K, target)
                            .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?,
                        // Force keyword.
                        "lexical" => guard
                            .graph_clusters_opt(
                                project,
                                CLUSTER_MAX_NODES,
                                CLUSTER_TOP_K,
                                CLUSTER_MIN_WEIGHT,
                                false,
                                target,
                            )
                            .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?,
                        // Auto: coverage decides (honours the per-project toggle).
                        _ => guard
                            .graph_clusters_opt(
                                project,
                                CLUSTER_MAX_NODES,
                                CLUSTER_TOP_K,
                                CLUSTER_MIN_WEIGHT,
                                allow_vector_default,
                                target,
                            )
                            .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?,
                    }
                } else {
                    guard
                        .group_meta(project, CLUSTER_MAX_NODES, group, target)
                        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?
                }
            };
            let mut cache = state.cluster_cache.lock().await;
            cache.insert(cache_key, (std::time::Instant::now(), idx.clone()));
            idx
        }
    };

    // Invert `node_cluster` (member -> root) into `root -> member_ids`.
    let total_nodes = index.node_cluster.len();
    let mut members_by_root: std::collections::HashMap<i64, Vec<i64>> =
        std::collections::HashMap::new();
    for (&mem_id, &root) in &index.node_cluster {
        members_by_root.entry(root).or_default().push(mem_id);
    }

    // Prune expired tokens + stale tokens of this same project, then mint one
    // token per bubble.
    let clusters = {
        let mut tokens = state.level_tokens.lock().await;
        tokens.retain(|_, (built_at, entry)| {
            built_at.elapsed() < LEVEL_TOKEN_TTL && entry.project != project
        });
        index
            .clusters
            .iter()
            .map(|c| {
                let member_ids = members_by_root.remove(&c.id).unwrap_or_default();
                let token = mint_level_token();
                tokens.insert(
                    token.clone(),
                    (
                        std::time::Instant::now(),
                        TokenEntry {
                            project: project.to_string(),
                            member_ids,
                            total_n: total_nodes,
                            label: c.label.clone(),
                        },
                    ),
                );
                serde_json::json!({
                    "id": c.id,
                    "token": token,
                    "size": c.size,
                    "label": c.label,
                    "dominant_source": c.dominant_source,
                    // Every bubble opens: > leaf_cut -> sub-bubbles, else a leaf
                    // of its members. Only a size-1 bubble is a dead end.
                    "drillable": c.size > 1,
                })
            })
            .collect::<Vec<_>>()
    };

    let cluster_edges: Vec<serde_json::Value> = index
        .cluster_edges
        .iter()
        .map(|(a, b, w)| serde_json::json!({"src": a, "dst": b, "weight": w}))
        .collect();

    // Report which signal the map is actually using so the UI can badge it:
    // a context overview is "vector" (semantic, embeddings) when the project is
    // mostly embedded — matching graph_clusters' own auto-dispatch — else
    // "lexical" (keyword fallback); metadata facets are neither.
    let (embedded, total_rows) = {
        let guard = store.lock().await;
        guard.embedding_coverage(project).unwrap_or((0, 0))
    };
    let basis = if !is_context {
        "metadata"
    } else {
        match basis_pref {
            "vector" => "vector",
            "lexical" => "lexical",
            // auto: coverage decides (honours the per-project toggle).
            _ if allow_vector_default && embedded > 0 && embedded * 2 >= total_rows => "vector",
            _ => "lexical",
        }
    };

    Ok(Json(serde_json::json!({
        "mode": "overview",
        "group": group,
        "total_nodes": total_nodes,
        "clusters": clusters,
        "cluster_edges": cluster_edges,
        "basis": basis,
        "embedded": embedded,
        "total_rows": total_rows,
    })))
}

/// Resolve a drill `token` to its member-id set and render the next level.
///
/// * missing / expired token  -> `410 stale` (client refetches the overview).
/// * `ids.len() <= LEAF_THRESHOLD` -> `leaf` (individual memory nodes).
/// * otherwise re-subcluster; if the subset does not split
///   (`clusters.len() <= 1`, e.g. all highly similar) fall back to a `leaf`
///   (anti-stall guard); else emit a `group` of sub-bubbles, each minted a
///   fresh child token.
pub(crate) async fn memory_graph_drill(
    state: &AppState,
    store: &Arc<Mutex<MemoryStore>>,
    token: String,
    leaf_pref: Option<usize>,
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    // Resolve the token (honouring TTL) and clone out its payload.
    let entry = {
        let tokens = state.level_tokens.lock().await;
        match tokens.get(&token) {
            Some((built_at, entry)) if built_at.elapsed() < LEVEL_TOKEN_TTL => entry.clone(),
            _ => return Err((StatusCode::GONE, "stale".into())),
        }
    };
    let total_n = entry.total_n;
    let project = entry.project.clone();
    let ids = entry.member_ids;
    // 깊이(depth): an explicit leaf cutoff from the map control, else dynamic.
    // A larger cutoff bottoms out sooner (shallower); smaller drills deeper.
    let leaf_cut = leaf_pref
        .filter(|&l| l > 0)
        .map(|l| l.clamp(8, 2000))
        .unwrap_or_else(|| dynamic_leaf(total_n));

    // Leaf: small enough to render individual memory nodes.
    if ids.len() <= leaf_cut {
        return memory_graph_leaf(store, &token, &ids).await;
    }

    // Deeper level: semantic re-cluster of the subset. Branch width scales with
    // the bucket size so drill depth grows with quantity.
    let branch = dynamic_branch(ids.len());
    let idx2 = {
        let guard = store.lock().await;
        guard
            .subcluster(&ids, CLUSTER_TOP_K, CLUSTER_MIN_WEIGHT, branch)
            .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?
    };

    // Anti-stall: if the semantic split did not actually break the set up — one
    // dominant child still holds most of it (a lexically-disjoint "unclustered"
    // mass) — recursing on it would peel only a few rows per level (the 90-deep
    // pathology). Re-partition by a metadata facet (session) so the mass becomes
    // navigable sub-bubbles instead of one blob.
    let largest = idx2.clusters.iter().map(|c| c.size).max().unwrap_or(0);
    let stalled = idx2.clusters.len() <= 1 || largest as f64 >= ids.len() as f64 * STALL_DOMINANCE;
    let level = if stalled {
        // Try metadata facets in turn until one actually distributes the mass
        // (more than one bucket, no single bucket still holding ~everything).
        // session -> time(hour) -> kind. `time` almost always splits a
        // same-session lexical mass chronologically, avoiding a truncated leaf.
        let chosen = {
            let guard = store.lock().await;
            let mut found: Option<ClusterIndex> = None;
            for facet in ["session", "time", "kind"] {
                let meta = guard
                    .group_meta_ids(&ids, facet, branch)
                    .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
                let ml = meta.clusters.iter().map(|c| c.size).max().unwrap_or(0);
                if meta.clusters.len() > 1 && (ml as f64) < ids.len() as f64 * 0.9 {
                    found = Some(meta);
                    break;
                }
            }
            found
        };
        // No facet helped (a truly homogeneous mass). Rather than truncate it to
        // a capped leaf (silent node loss), split it into ordinal time-ordered
        // PAGE buckets of <= leaf_cut, each of which opens to a full leaf. This
        // guarantees every memory stays reachable while the graph never has to
        // render thousands of points at once.
        match chosen {
            Some(m) => m,
            None => {
                let pages = page_buckets(&ids, leaf_cut);
                return Ok(emit_group_response(
                    state,
                    &pages,
                    &project,
                    total_n,
                    &token,
                    ids.len(),
                    true,
                )
                .await);
            }
        }
    } else {
        idx2
    };

    Ok(emit_group_response(state, &level, &project, total_n, &token, ids.len(), false).await)
}

/// Last-resort partition for a homogeneous mass no facet could split: sort by id
/// (≈ chronological) and cut into ordinal pages of `page` members each. Each page
/// is its own cluster (root = min id) so it opens to a complete leaf — no node is
/// ever dropped.
pub(crate) fn page_buckets(ids: &[i64], page: usize) -> ClusterIndex {
    let page = page.max(1);
    let mut sorted = ids.to_vec();
    sorted.sort_unstable();
    let mut clusters = Vec::new();
    let mut node_cluster = std::collections::HashMap::new();
    for (ci, chunk) in sorted.chunks(page).enumerate() {
        let root = *chunk.iter().min().expect("non-empty chunk");
        for &id in chunk {
            node_cluster.insert(id, root);
        }
        let start = ci * page + 1;
        clusters.push(rtrt_memory::ClusterSummary {
            id: root,
            size: chunk.len(),
            label: format!("{}–{} (시간순)", start, start + chunk.len() - 1),
            dominant_source: "mixed".to_string(),
        });
    }
    ClusterIndex {
        clusters,
        cluster_edges: Vec::new(),
        node_cluster,
    }
}

/// Mint a child drill token per sub-bubble of `index` and render a `group`
/// level. Shared by the semantic and metadata-fallback drill paths. Prunes
/// expired tokens before minting so the cache stays bounded on deep drills
/// (overviews are not always rebuilt between drills).
pub(crate) async fn emit_group_response(
    state: &AppState,
    index: &ClusterIndex,
    project: &str,
    total_n: usize,
    parent: &str,
    parent_size: usize,
    force_drillable: bool,
) -> Json<serde_json::Value> {
    let mut members_by_root: std::collections::HashMap<i64, Vec<i64>> =
        std::collections::HashMap::new();
    for (&mem_id, &root) in &index.node_cluster {
        members_by_root.entry(root).or_default().push(mem_id);
    }
    let clusters = {
        let mut tokens = state.level_tokens.lock().await;
        tokens.retain(|_, (built_at, _)| built_at.elapsed() < LEVEL_TOKEN_TTL);
        index
            .clusters
            .iter()
            .map(|c| {
                let member_ids = members_by_root.remove(&c.id).unwrap_or_default();
                let child = mint_level_token();
                tokens.insert(
                    child.clone(),
                    (
                        std::time::Instant::now(),
                        TokenEntry {
                            project: project.to_string(),
                            member_ids,
                            total_n,
                            label: c.label.clone(),
                        },
                    ),
                );
                serde_json::json!({
                    "id": c.id,
                    "token": child,
                    "size": c.size,
                    "label": c.label,
                    "dominant_source": c.dominant_source,
                    // Every bubble opens (sub-bubbles or a member leaf); only a
                    // size-1 bubble is a dead end. (force_drillable kept for
                    // symmetry with the overview path / page buckets.)
                    "drillable": force_drillable || c.size > 1,
                })
            })
            .collect::<Vec<_>>()
    };
    let cluster_edges: Vec<serde_json::Value> = index
        .cluster_edges
        .iter()
        .map(|(a, b, w)| serde_json::json!({"src": a, "dst": b, "weight": w}))
        .collect();

    Json(serde_json::json!({
        "mode": "group",
        "parent": parent,
        "total_nodes": parent_size,
        "clusters": clusters,
        "cluster_edges": cluster_edges,
    }))
}

/// Leaf render shared by the token-drill paths: load `ids` as individual
/// memory nodes + their intra-set edges (capped by the store).
pub(crate) async fn memory_graph_leaf(
    store: &Arc<Mutex<MemoryStore>>,
    parent: &str,
    ids: &[i64],
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    let members = {
        let guard = store.lock().await;
        guard
            .members_for_ids(ids)
            .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?
    };
    let nodes: Vec<serde_json::Value> = members
        .nodes
        .iter()
        .map(|n| {
            serde_json::json!({
                "id": format!("m{}", n.id),
                "node_type": "memory",
                "label": n.preview,
                "kind": n.kind,
                "source_kind": n.source_kind,
            })
        })
        .collect();
    let edges: Vec<serde_json::Value> = members
        .edges
        .iter()
        .map(|(a, b, w)| serde_json::json!({"src": format!("m{a}"), "dst": format!("m{b}"), "weight": w}))
        .collect();
    Ok(Json(serde_json::json!({
        "mode": "leaf",
        "parent": parent,
        "nodes": nodes,
        "edges": edges,
    })))
}
