//! (generated by module split — pure refactor, behavior identical)
#![allow(unused_imports)]

use std::collections::BTreeMap;
use std::path::PathBuf;
use std::process::Stdio;
use std::sync::Arc;

use anyhow::Result;
use axum::{
    Json, Router,
    extract::{Path as AxPath, State},
    http::StatusCode,
    response::{Html, IntoResponse},
    routing::{delete, get, post},
};
use rtrt_core::{
    OutputStyleLevel, read_output_style_level, read_output_style_level_for,
    write_output_style_level_for,
};
use rtrt_memory::{
    ClusterIndex, ConceptHierarchy, DetailedRecord, Embedder, MemoryStore, PayloadFilter,
    Summariser,
};
use rtrt_providers::{
    ChatMessage, ChatRequest, ChatResponse, Gateway, MetricsView, Prefer, Provider, RequestMetric,
    Role, RouteAlternative, RouteRequest, UsageSnapshot, select_route,
};
use rtrt_security::{Profile, ScanReport};
use rtrt_templates::{Prompt, PromptRegistry};
use serde::{Deserialize, Serialize};
use tokio::io::AsyncWriteExt;
use tokio::sync::Mutex;
use tokio::sync::broadcast;

use crate::prelude::*;

#[derive(Debug, Deserialize)]
pub(crate) struct MemoryRecallRequest {
    project: String,
    query: String,
    #[serde(default = "default_recall_limit")]
    limit: u32,
    #[serde(default)]
    filter: Option<String>,
    /// `bm25` (default) — plain BM25; `hybrid` — BM25 + graph-neighbour blend.
    /// True dense-vector hybrid requires the `embeddings` feature; this path
    /// uses `recall_bm25_graph_blend` which needs no separate model.
    /// TODO: wire fastembed / Ollama bge-m3 for full vector hybrid.
    #[serde(default)]
    mode: Option<String>,
}

pub(crate) fn default_recall_limit() -> u32 {
    10
}

pub(crate) async fn memory_recall(
    State(state): State<AppState>,
    Json(req): Json<MemoryRecallRequest>,
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    let store = state
        .memory
        .as_ref()
        .ok_or((StatusCode::SERVICE_UNAVAILABLE, "memory disabled".into()))?;
    let guard = store.lock().await;

    let mode = req.mode.as_deref().unwrap_or("bm25");

    match mode {
        "hybrid" => {
            // When an Ollama embedder is wired, run true BM25 + dense-vector
            // RRF. Otherwise fall back to the graph-blended BM25 path so the
            // endpoint stays usable without an embedding server.
            let (scored, effective_mode) = if let Some(emb) = state.embedder.as_ref() {
                let s = guard
                    .recall_hybrid(&req.project, &req.query, req.limit as usize, emb.as_ref())
                    .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
                (s, "hybrid-vector")
            } else {
                // No embedder available — use graph-blended BM25 as a
                // graceful degradation.
                let s = guard
                    .recall_bm25_graph_blend(&req.project, &req.query, req.limit as usize)
                    .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
                (s, "hybrid-graph")
            };
            let hits: Vec<serde_json::Value> = scored
                .into_iter()
                .map(|sr| {
                    serde_json::json!({
                        "id": sr.record.id,
                        "project": sr.record.project,
                        "kind": sr.record.kind,
                        "body": sr.record.body,
                        "created_at": sr.record.created_at,
                        "scope": sr.record.scope,
                        "score": sr.score,
                    })
                })
                .collect();
            Ok(Json(
                serde_json::json!({ "hits": hits, "mode": effective_mode }),
            ))
        }
        // "bm25" or any unrecognised value falls through to plain BM25.
        _ => {
            let hits = match req.filter.as_deref() {
                Some(spec) if !spec.is_empty() => {
                    let f = PayloadFilter::parse(spec)
                        .map_err(|e| (StatusCode::BAD_REQUEST, e.to_string()))?;
                    guard
                        .recall_bm25_with_filter(&req.project, &req.query, req.limit as usize, &f)
                        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?
                }
                _ => guard
                    .recall_bm25(&req.project, &req.query, req.limit as usize)
                    .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?,
            };
            Ok(Json(serde_json::json!({ "hits": hits, "mode": "bm25" })))
        }
    }
}

pub(crate) async fn memory_projects(
    State(state): State<AppState>,
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    let store = state
        .memory
        .as_ref()
        .ok_or((StatusCode::SERVICE_UNAVAILABLE, "memory disabled".into()))?;
    let guard = store.lock().await;
    let rows = guard
        .projects()
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
    let projects: Vec<serde_json::Value> = rows
        .into_iter()
        .map(|(name, count, latest)| {
            serde_json::json!({ "project": name, "count": count, "latest_ts": latest })
        })
        .collect();
    Ok(Json(serde_json::json!({ "projects": projects })))
}

#[derive(Debug, Deserialize)]
pub(crate) struct MemoryTimelineQuery {
    project: String,
    #[serde(default = "default_timeline_limit")]
    limit: usize,
    #[serde(default)]
    offset: usize,
    /// `recent` (default) — newest first; `importance` — deterministic score descending.
    #[serde(default)]
    sort: Option<String>,
    /// Restrict to a `source_kind` (`main` / `subagent`). Absent = all rows.
    #[serde(default)]
    source_kind: Option<String>,
}

pub(crate) fn default_timeline_limit() -> usize {
    50
}

pub(crate) async fn memory_timeline(
    State(state): State<AppState>,
    axum::extract::Query(q): axum::extract::Query<MemoryTimelineQuery>,
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    let store = state
        .memory
        .as_ref()
        .ok_or((StatusCode::SERVICE_UNAVAILABLE, "memory disabled".into()))?;
    let guard = store.lock().await;

    let sort = q.sort.as_deref().unwrap_or("recent");
    let sk = q.source_kind.as_deref().filter(|s| !s.is_empty());
    let total = guard
        .count_by_project_filtered(&q.project, sk)
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;

    let items: Vec<serde_json::Value> = if sort == "importance" {
        // Importance sort — returns DetailedRecord which already includes
        // body_full, metadata, and a pre-computed score.
        let rows = guard
            .recent_paged_by_importance_filtered(&q.project, q.limit, q.offset, sk)
            .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
        rows.into_iter()
            .map(|r| {
                let saved_pct = compress_saved_pct_from_meta(Some(&r.metadata));
                serde_json::json!({
                    "id": r.id,
                    "kind": r.kind,
                    "scope": r.scope,
                    "body": r.body,
                    "body_full": r.body_full,
                    "compressed": r.compressed,
                    "created_at": r.created_at,
                    "importance": r.importance,
                    "metadata": r.metadata,
                    "saved_pct": saved_pct,
                })
            })
            .collect()
    } else {
        // Default: newest-first paged view.
        let rows = guard
            .recent_paged_filtered(&q.project, q.limit, q.offset, sk)
            .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
        rows.into_iter()
            .map(|r| {
                // `body_full` is the preserved pre-compression original (None
                // when the row was never compressed). `body` is what recall
                // uses (terse when compressed).
                let full = guard.full_body(r.id).ok().flatten();
                let compressed = full.is_some();
                let meta = guard.get_metadata(r.id).ok();
                let saved_pct = if compressed {
                    compress_saved_pct_from_meta(meta.as_ref())
                } else {
                    None
                };
                // main | subagent — lets the UI split a project's own work from
                // its subagent / teammate captures.
                let source_kind = meta.as_ref().and_then(|m| m.get("source_kind")).cloned();
                serde_json::json!({
                    "id": r.id,
                    "kind": r.kind,
                    "scope": r.scope,
                    "body": r.body,
                    "body_full": full,
                    "compressed": compressed,
                    "created_at": r.created_at,
                    "saved_pct": saved_pct,
                    "source_kind": source_kind,
                })
            })
            .collect()
    };

    Ok(Json(serde_json::json!({
        "items": items,
        "total": total,
        "limit": q.limit,
        "offset": q.offset,
        "sort": sort,
    })))
}

#[derive(Debug, Deserialize)]
pub(crate) struct MemoryExportQuery {
    project: String,
}

pub(crate) async fn memory_export(
    State(state): State<AppState>,
    axum::extract::Query(q): axum::extract::Query<MemoryExportQuery>,
) -> std::result::Result<axum::response::Response, (StatusCode, String)> {
    use axum::http::header;
    let store = state
        .memory
        .as_ref()
        .ok_or((StatusCode::SERVICE_UNAVAILABLE, "memory disabled".into()))?;
    let guard = store.lock().await;
    let mut buf = Vec::new();
    guard
        .export_jsonl(&q.project, &mut buf)
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
    let filename = format!("{}.jsonl", q.project.replace(['/', '\\'], "_"));
    let disposition = format!("attachment; filename=\"{filename}\"");
    let resp = axum::response::Response::builder()
        .status(StatusCode::OK)
        .header(header::CONTENT_TYPE, "application/x-ndjson")
        .header(header::CONTENT_DISPOSITION, disposition)
        .body(axum::body::Body::from(buf))
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
    Ok(resp)
}

#[derive(Debug, Deserialize)]
pub(crate) struct MemorySaveRequest {
    project: String,
    #[serde(default = "default_kind")]
    kind: String,
    body: String,
    #[serde(default)]
    metadata: BTreeMap<String, String>,
}

pub(crate) fn default_kind() -> String {
    "note".into()
}

#[derive(Debug, Deserialize)]
pub(crate) struct SetBlockRequest {
    project: String,
    name: String,
    body: String,
}

#[derive(Debug, Deserialize)]
pub(crate) struct ListBlocksQuery {
    project: String,
}

pub(crate) async fn list_blocks(
    State(state): State<AppState>,
    axum::extract::Query(q): axum::extract::Query<ListBlocksQuery>,
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    let store = state
        .memory
        .as_ref()
        .ok_or((StatusCode::SERVICE_UNAVAILABLE, "memory disabled".into()))?;
    let guard = store.lock().await;
    let blocks = guard
        .list_blocks(&q.project)
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
    Ok(Json(serde_json::json!({ "blocks": blocks })))
}

pub(crate) async fn set_block(
    State(state): State<AppState>,
    Json(req): Json<SetBlockRequest>,
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    let store = state
        .memory
        .as_ref()
        .ok_or((StatusCode::SERVICE_UNAVAILABLE, "memory disabled".into()))?;
    let guard = store.lock().await;
    let id = guard
        .set_block(&req.project, &req.name, &req.body)
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
    Ok(Json(serde_json::json!({ "id": id })))
}

#[derive(Debug, Deserialize)]
pub(crate) struct GetBlockQuery {
    project: String,
}

pub(crate) async fn get_block(
    State(state): State<AppState>,
    axum::extract::Path(name): axum::extract::Path<String>,
    axum::extract::Query(q): axum::extract::Query<GetBlockQuery>,
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    let store = state
        .memory
        .as_ref()
        .ok_or((StatusCode::SERVICE_UNAVAILABLE, "memory disabled".into()))?;
    let guard = store.lock().await;
    let block = guard
        .get_block(&q.project, &name)
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
    match block {
        Some(b) => {
            Ok(Json(serde_json::to_value(&b).map_err(|e| {
                (StatusCode::INTERNAL_SERVER_ERROR, e.to_string())
            })?))
        }
        None => Err((StatusCode::NOT_FOUND, format!("block not found: {name}"))),
    }
}

pub(crate) async fn memory_save(
    State(state): State<AppState>,
    Json(req): Json<MemorySaveRequest>,
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    let store = state
        .memory
        .as_ref()
        .ok_or((StatusCode::SERVICE_UNAVAILABLE, "memory disabled".into()))?;
    let guard = store.lock().await;
    let id = if req.metadata.is_empty() {
        guard
            .save(&req.project, &req.kind, &req.body)
            .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?
    } else {
        guard
            .save_with_metadata(&req.project, &req.kind, &req.body, &req.metadata)
            .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?
    };
    Ok(Json(serde_json::json!({ "id": id })))
}

#[derive(Debug, Deserialize)]
pub(crate) struct MemoryCompressRequest {
    project: String,
    #[serde(default)]
    model: Option<String>,
}

#[derive(Debug, Serialize)]
pub(crate) struct MemoryCompressResponse {
    compressed: usize,
    skipped: usize,
    saved_chars: i64,
    /// Aggregate % reduction across the batch (0.0 when nothing was compressed).
    saved_pct: f64,
}

pub(crate) async fn memory_compress(
    State(state): State<AppState>,
    Json(req): Json<MemoryCompressRequest>,
) -> std::result::Result<Json<MemoryCompressResponse>, (StatusCode, String)> {
    let store = state
        .memory
        .as_ref()
        .ok_or((StatusCode::SERVICE_UNAVAILABLE, "memory disabled".into()))?;

    let cfg = rtrt_core::Config::load()
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
    let ac = &cfg.auto_compress;

    let age_sec: i64 = ac.age_sec;
    let min_chars: usize = ac.min_chars;
    let batch: usize = ac.batch;
    let max_tokens: u32 = ac.max_tokens;
    let model = req.model.clone().unwrap_or_else(|| ac.model.clone());

    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0);
    let cutoff = now - age_sec;

    let candidates = {
        let guard = store.lock().await;
        guard
            .compress_candidates(&req.project, cutoff, min_chars, batch)
            .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?
    };

    let mut compressed_count = 0usize;
    let mut skipped_count = 0usize;
    let mut total_from_chars: i64 = 0;
    let mut total_saved_chars: i64 = 0;

    for (id, body) in candidates {
        let chat_req = ChatRequest {
            model: model.clone(),
            messages: vec![
                ChatMessage {
                    role: Role::System,
                    content: "You are a lossless-meaning compressor. Rewrite the user message in the shortest form that preserves every fact, decision, file path, identifier, command, and number. Drop filler, hedging, headings, and greetings. Plain text only. No commentary, no preamble, no quotes — emit only the compressed text.".to_string(),
                },
                ChatMessage {
                    role: Role::User,
                    content: body.clone(),
                },
            ],
            max_tokens: Some(max_tokens),
            temperature: Some(0.0),
        };
        let resp = match state.gateway.chat(chat_req).await {
            Ok(r) => r,
            Err(e) => {
                tracing::warn!("memory_compress {project}#{id}: {e}", project = req.project);
                skipped_count += 1;
                continue;
            }
        };
        let new_body = resp.content.trim().to_string();
        if new_body.is_empty() || new_body.len() >= body.len() {
            // No compression win; mark so the next sweep skips this row.
            let guard = store.lock().await;
            let mut meta = guard.get_metadata(id).unwrap_or_default();
            meta.insert("compressed_at".into(), now.to_string());
            meta.insert("compressed_skip".into(), "no-shrink".into());
            let _ = guard.set_metadata(id, &meta);
            skipped_count += 1;
            continue;
        }
        let guard = store.lock().await;
        if let Err(e) = guard.compress_in_place(id, &new_body) {
            tracing::warn!(
                "memory_compress {project}#{id}: compress_in_place: {e}",
                project = req.project
            );
            skipped_count += 1;
            continue;
        }
        let mut meta = guard.get_metadata(id).unwrap_or_default();
        meta.insert("compressed_at".into(), now.to_string());
        meta.insert("compressed_model".into(), model.clone());
        let from_chars = body.len() as i64;
        let to_chars = new_body.len() as i64;
        meta.insert("compressed_from_chars".into(), from_chars.to_string());
        meta.insert("compressed_to_chars".into(), to_chars.to_string());
        let _ = guard.set_metadata(id, &meta);
        total_from_chars += from_chars;
        total_saved_chars += (from_chars - to_chars).max(0);
        compressed_count += 1;
        tracing::info!(
            project = %req.project,
            id,
            from = body.len(),
            to = new_body.len(),
            "manual compress sweep"
        );
    }

    let saved_pct = if total_from_chars > 0 {
        (total_saved_chars as f64 / total_from_chars as f64 * 100.0 * 10.0).round() / 10.0
    } else {
        0.0
    };
    Ok(Json(MemoryCompressResponse {
        compressed: compressed_count,
        skipped: skipped_count,
        saved_chars: total_saved_chars,
        saved_pct,
    }))
}

// ---------------------------------------------------------------------------
// GET /api/memory/stats?project=X
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
pub(crate) struct MemoryStatsQuery {
    project: String,
}

#[derive(Debug, Serialize)]
pub(crate) struct KindCount {
    kind: String,
    count: i64,
}

#[derive(Debug, Serialize)]
pub(crate) struct DayCount {
    day: String,
    count: i64,
}

#[derive(Debug, Serialize)]
pub(crate) struct MemoryStatsResponse {
    total: i64,
    by_kind: Vec<KindCount>,
    compressed_count: i64,
    saved_chars: i64,
    /// Average % reduction across compressed rows (0.0 when none compressed).
    saved_pct: f64,
    by_day: Vec<DayCount>,
}

pub(crate) async fn memory_stats(
    axum::extract::Query(q): axum::extract::Query<MemoryStatsQuery>,
) -> std::result::Result<Json<MemoryStatsResponse>, (StatusCode, String)> {
    // Open a direct rusqlite connection to the same path used by open_memory_store().
    let path = std::env::var("RTRT_MEMORY_PATH")
        .ok()
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from(".rtrt/memory.sqlite"));

    let conn = rusqlite::Connection::open(&path).map_err(|e| {
        (
            StatusCode::SERVICE_UNAVAILABLE,
            format!("memory store: {e}"),
        )
    })?;

    // Total row count for the project.
    let total: i64 = conn
        .query_row(
            "SELECT COUNT(*) FROM memories WHERE project = ?1",
            rusqlite::params![q.project],
            |row| row.get(0),
        )
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;

    // Per-kind breakdown.
    let by_kind = {
        let mut stmt = conn
            .prepare(
                "SELECT kind, COUNT(*) AS cnt FROM memories WHERE project = ?1 GROUP BY kind ORDER BY cnt DESC",
            )
            .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
        let rows = stmt
            .query_map(rusqlite::params![q.project], |row| {
                Ok(KindCount {
                    kind: row.get(0)?,
                    count: row.get(1)?,
                })
            })
            .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
        rows.collect::<std::result::Result<Vec<_>, _>>()
            .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?
    };

    // compressed_count / saved_chars / saved_pct:
    //   Source of truth = actual body vs body_full lengths for rows where
    //   body_full IS NOT NULL (the pre-compression original is stored there).
    //   saved_pct = 1 - sum(len(body)) / sum(len(body_full)) over those rows.
    let (compressed_count, saved_chars, saved_pct) = {
        let mut stmt = conn
            .prepare(
                "SELECT LENGTH(body), LENGTH(body_full) FROM memories \
                  WHERE project = ?1 AND body_full IS NOT NULL",
            )
            .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
        let rows = stmt
            .query_map(rusqlite::params![q.project], |row| {
                Ok((row.get::<_, i64>(0)?, row.get::<_, i64>(1)?))
            })
            .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
        let mut count: i64 = 0;
        let mut sum_body: i64 = 0;
        let mut sum_full: i64 = 0;
        for r in rows.flatten() {
            let (body_len, full_len) = r;
            if full_len > 0 {
                count += 1;
                sum_body += body_len;
                sum_full += full_len;
            }
        }
        let saved = (sum_full - sum_body).max(0);
        let pct = if sum_full > 0 {
            ((1.0 - sum_body as f64 / sum_full as f64) * 100.0 * 10.0).round() / 10.0
        } else {
            0.0
        };
        (count, saved, pct)
    };

    // by_day: group created_at (Unix timestamp integer) by calendar date (YYYY-MM-DD).
    let by_day = {
        let mut stmt = conn
            .prepare(
                "SELECT date(datetime(created_at, 'unixepoch')) AS day, COUNT(*) AS cnt \
                 FROM memories WHERE project = ?1 GROUP BY day ORDER BY day",
            )
            .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
        let rows = stmt
            .query_map(rusqlite::params![q.project], |row| {
                Ok(DayCount {
                    day: row.get(0)?,
                    count: row.get(1)?,
                })
            })
            .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
        rows.collect::<std::result::Result<Vec<_>, _>>()
            .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?
    };

    Ok(Json(MemoryStatsResponse {
        total,
        by_kind,
        compressed_count,
        saved_chars,
        saved_pct,
        by_day,
    }))
}

#[derive(Debug, Deserialize)]
pub(crate) struct MemoryQueueQuery {
    project: String,
}

/// Compression queue: rows that are eligible for LLM compression (body
/// length >= configured min_chars, not yet compressed) but haven't been
/// done. `ready` = the cool-off age has also passed, so the daemon /
/// "compress now" will pick it up; `waiting` rows are still too recent.
pub(crate) async fn memory_queue(
    axum::extract::Query(q): axum::extract::Query<MemoryQueueQuery>,
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    let path = std::env::var("RTRT_MEMORY_PATH")
        .ok()
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from(".rtrt/memory.sqlite"));
    let cfg = rtrt_core::Config::load().unwrap_or_default().auto_compress;
    let conn = rusqlite::Connection::open(&path).map_err(|e| {
        (
            StatusCode::SERVICE_UNAVAILABLE,
            format!("memory store: {e}"),
        )
    })?;
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0);
    let cutoff = now - cfg.age_sec;
    let mut stmt = conn
        .prepare(
            "SELECT id, kind, LENGTH(body), created_at FROM memories \
              WHERE project = ?1 AND LENGTH(body) >= ?2 \
                AND (metadata IS NULL OR metadata NOT LIKE '%compressed_at%') \
              ORDER BY created_at ASC LIMIT 200",
        )
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
    let rows = stmt
        .query_map(rusqlite::params![q.project, cfg.min_chars as i64], |row| {
            let id: i64 = row.get(0)?;
            let kind: String = row.get(1)?;
            let chars: i64 = row.get(2)?;
            let created_at: i64 = row.get(3)?;
            Ok((id, kind, chars, created_at))
        })
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
    let mut items = Vec::new();
    let (mut ready, mut waiting) = (0i64, 0i64);
    for r in rows.flatten() {
        let (id, kind, chars, created_at) = r;
        let is_ready = created_at < cutoff;
        if is_ready {
            ready += 1;
        } else {
            waiting += 1;
        }
        // Queue rows are not yet compressed; saved_pct is null (pending).
        items.push(serde_json::json!({
            "id": id,
            "kind": kind,
            "chars": chars,
            "age_min": (now - created_at) / 60,
            "ready": is_ready,
            "saved_pct": serde_json::Value::Null,
        }));
    }
    Ok(Json(serde_json::json!({
        "items": items,
        "ready": ready,
        "waiting": waiting,
        "min_chars": cfg.min_chars,
        "age_sec": cfg.age_sec,
        "enabled": cfg.enabled,
        "model": cfg.model,
    })))
}

// ---------------------------------------------------------------------------
// GET /api/memory/{id}  — full detail for a single memory row
// ---------------------------------------------------------------------------

pub(crate) async fn memory_detail(
    State(state): State<AppState>,
    axum::extract::Path(id): axum::extract::Path<i64>,
) -> std::result::Result<Json<DetailedRecord>, (StatusCode, String)> {
    let store = state
        .memory
        .as_ref()
        .ok_or((StatusCode::SERVICE_UNAVAILABLE, "memory disabled".into()))?;
    let guard = store.lock().await;
    match guard
        .get_row(id)
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?
    {
        Some(r) => Ok(Json(r)),
        None => Err((StatusCode::NOT_FOUND, format!("memory {id} not found"))),
    }
}

// ---------------------------------------------------------------------------
// DELETE /api/memory/{id}  — governance delete for a single row
// ---------------------------------------------------------------------------

#[derive(Debug, Serialize)]
pub(crate) struct DeleteOneResponse {
    deleted: bool,
    id: i64,
}

pub(crate) async fn memory_delete_one(
    State(state): State<AppState>,
    axum::extract::Path(id): axum::extract::Path<i64>,
) -> std::result::Result<Json<DeleteOneResponse>, (StatusCode, String)> {
    let store = state
        .memory
        .as_ref()
        .ok_or((StatusCode::SERVICE_UNAVAILABLE, "memory disabled".into()))?;
    let guard = store.lock().await;
    let deleted = guard
        .delete_row(id)
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
    if deleted {
        broadcast_event(
            &state.events,
            serde_json::json!({ "type": "memory.delete", "id": id }),
        );
        Ok(Json(DeleteOneResponse { deleted: true, id }))
    } else {
        Err((StatusCode::NOT_FOUND, format!("memory {id} not found")))
    }
}

// ---------------------------------------------------------------------------
// POST /api/memory/delete  — governance batch delete
// Body: { "ids": [i64, …] }
// Response: { "deleted": N }
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
pub(crate) struct DeleteBatchRequest {
    ids: Vec<i64>,
}

#[derive(Debug, Serialize)]
pub(crate) struct DeleteBatchResponse {
    deleted: usize,
}

pub(crate) async fn memory_delete_batch(
    State(state): State<AppState>,
    Json(req): Json<DeleteBatchRequest>,
) -> std::result::Result<Json<DeleteBatchResponse>, (StatusCode, String)> {
    if req.ids.is_empty() {
        return Ok(Json(DeleteBatchResponse { deleted: 0 }));
    }
    let store = state
        .memory
        .as_ref()
        .ok_or((StatusCode::SERVICE_UNAVAILABLE, "memory disabled".into()))?;
    let guard = store.lock().await;
    let deleted = guard
        .delete_rows(&req.ids)
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
    broadcast_event(
        &state.events,
        serde_json::json!({ "type": "memory.delete_batch", "ids": req.ids, "deleted": deleted }),
    );
    Ok(Json(DeleteBatchResponse { deleted }))
}

// ---------------------------------------------------------------------------
// POST /api/memory/embed
// Body:  { "project": "…" }
// Response: { "embedded": N }
//
// Backfills embeddings for every memory row in `project` that does not yet
// have an entry in the `embeddings` table. Requires embeddings to be enabled
// in the config / env. Returns 503 when no embedder is available.
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
pub(crate) struct MemoryEmbedRequest {
    project: String,
}

// Kicks off a NON-BLOCKING background backfill. A big project (20k rows) takes
// many minutes of Ollama calls; doing that under the shared store mutex would
// freeze the whole dashboard. Instead a dedicated thread opens its OWN SQLite
// connection (WAL mode = concurrent with the main one) and backfills there, so
// the UI stays live and `embedding_coverage` reflects progress as rows commit.
pub(crate) async fn memory_embed(
    State(state): State<AppState>,
    Json(req): Json<MemoryEmbedRequest>,
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    if state.embedder.is_none() {
        return Err((
            StatusCode::SERVICE_UNAVAILABLE,
            "embeddings not enabled".into(),
        ));
    }
    // Dedup: refuse a second concurrent job for the same project.
    {
        let mut jobs = state.embedding_jobs.lock().unwrap();
        if jobs.contains(&req.project) {
            return Ok(Json(
                serde_json::json!({ "started": false, "running": true }),
            ));
        }
        jobs.insert(req.project.clone());
    }

    let path = state.memory_path.clone();
    let project = req.project.clone();
    let jobs = state.embedding_jobs.clone();
    // Resolve embed config for the worker's own embedder.
    let ecfg = rtrt_core::Config::load().unwrap_or_default().embeddings;
    let base_url = ecfg.resolved_base_url(
        rtrt_core::Config::load()
            .ok()
            .and_then(|c| c.auto_compress.base_url)
            .as_deref(),
    );
    let model = ecfg.effective_model();

    std::thread::spawn(move || {
        match MemoryStore::open(&path) {
            Ok(store) => {
                let embedder = rtrt_memory::OllamaEmbedder::new(base_url, model);
                match store.backfill_embeddings(&project, &embedder) {
                    Ok(n) => tracing::info!("embedding backfill done: {project} (+{n})"),
                    Err(e) => tracing::warn!("embedding backfill failed for {project}: {e}"),
                }
            }
            Err(e) => tracing::warn!("embedding backfill: open store failed: {e}"),
        }
        jobs.lock().unwrap().remove(&project);
    });

    Ok(Json(
        serde_json::json!({ "started": true, "running": true }),
    ))
}

#[derive(Debug, Deserialize)]
pub(crate) struct MemoryCoverageQuery {
    project: String,
}

// GET /api/memory/coverage?project=X -> { embedded, total, running }
// Lets the UI poll embedding progress while a background backfill runs.
pub(crate) async fn memory_coverage(
    State(state): State<AppState>,
    axum::extract::Query(q): axum::extract::Query<MemoryCoverageQuery>,
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    let store = state
        .memory
        .as_ref()
        .ok_or((StatusCode::SERVICE_UNAVAILABLE, "memory disabled".into()))?;
    let (embedded, total) = {
        let guard = store.lock().await;
        guard
            .embedding_coverage(&q.project)
            .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?
    };
    let running = state.embedding_jobs.lock().unwrap().contains(&q.project);
    Ok(Json(
        serde_json::json!({ "embedded": embedded, "total": total, "running": running }),
    ))
}

// ---------------------------------------------------------------------------
// POST /api/memory/entities
// Body:  { "project": "…", "model": "…" }  (model is optional)
// Response: { "edges": N }
//
// Runs the LLM-driven entity-extraction + edge-linking pass for `project`.
// The gateway's configured model (or the explicit `model` field) is used.
// Returns 503 when no gateway provider is available.
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
pub(crate) struct MemoryEntitiesRequest {
    project: String,
    #[serde(default)]
    model: Option<String>,
}

pub(crate) async fn memory_entities(
    State(state): State<AppState>,
    Json(req): Json<MemoryEntitiesRequest>,
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    let store = state
        .memory
        .as_ref()
        .ok_or((StatusCode::SERVICE_UNAVAILABLE, "memory disabled".into()))?;

    // Resolve the model: explicit arg → config auto_compress model → fallback.
    let model = req.model.clone().unwrap_or_else(|| {
        rtrt_core::Config::load()
            .ok()
            .map(|c| c.auto_compress.model)
            .unwrap_or_else(|| "claude-haiku-4-5".to_string())
    });

    // Build a per-request gateway the same way the auto-compress daemon does,
    // so the config base_url is honoured even when env vars are absent.
    let llm_gateway = {
        let env_has_url = std::env::var_os("RTRT_PROVIDER_BASE_URL").is_some()
            || std::env::var_os("RTRT_OPENAI_COMPAT_URL").is_some();
        if env_has_url {
            Arc::new(rtrt_providers::Gateway::from_env())
        } else {
            let cfg_url = rtrt_core::Config::load()
                .ok()
                .and_then(|c| c.auto_compress.base_url);
            Arc::new(if let Some(url) = cfg_url {
                unsafe { std::env::set_var("RTRT_PROVIDER_BASE_URL", &url) };
                let gw = rtrt_providers::Gateway::from_env();
                unsafe { std::env::remove_var("RTRT_PROVIDER_BASE_URL") };
                gw
            } else {
                rtrt_providers::Gateway::from_env()
            })
        }
    };

    let summariser = rtrt_memory::LlmSummariser::new(Box::new(GatewayAdapter(llm_gateway)), model);

    // `MemoryStore` is `!Sync` (rusqlite `Connection`), so no `&MemoryStore`
    // borrow may live across an `.await`. Mirror the auto-compress daemon: do
    // the SQLite reads under the lock, drop it for the async LLM extraction,
    // then re-lock for the synchronous edge writes.
    let sources: Vec<(i64, String)> = {
        let guard = store.lock().await;
        guard
            .list_by_project(&req.project, 10_000)
            .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?
            .into_iter()
            .map(|m| (m.id, m.body))
            .collect()
    };

    let mut extracted: Vec<(i64, Vec<String>)> = Vec::with_capacity(sources.len());
    for (id, body) in &sources {
        let entities = summariser
            .extract_entities(body)
            .await
            .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
        extracted.push((*id, entities));
    }

    let new_edges = {
        let guard = store.lock().await;
        guard
            .link_extracted_bipartite(&req.project, &extracted)
            .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?
    };
    Ok(Json(serde_json::json!({ "edges": new_edges })))
}

// ---------------------------------------------------------------------------
// Ollama model management  (/api/ollama/*)
//
// All endpoints resolve the Ollama base URL via `ollama_base()`:
//   embeddings.base_url → auto_compress.base_url → http://127.0.0.1:11434
// Trailing `/v1` is stripped so the same URL works for both the
// OpenAI-compat chat path and the native Ollama API.
// ---------------------------------------------------------------------------
