//! (generated by module split — pure refactor, behavior identical)
#![allow(unused_imports)]

use std::collections::BTreeMap;
use std::path::PathBuf;
use std::process::Stdio;
use std::sync::Arc;

use anyhow::Result;
use axum::{
    Json, Router,
    extract::{Path as AxPath, State},
    http::StatusCode,
    response::{Html, IntoResponse},
    routing::{delete, get, post},
};
use rtrt_core::{
    OutputStyleLevel, read_output_style_level, read_output_style_level_for,
    write_output_style_level_for,
};
use rtrt_memory::{
    ClusterIndex, ConceptHierarchy, DetailedRecord, Embedder, MemoryStore, PayloadFilter,
    Summariser,
};
use rtrt_providers::{
    ChatMessage, ChatRequest, ChatResponse, Gateway, MetricsView, Prefer, Provider, RequestMetric,
    Role, RouteAlternative, RouteRequest, UsageSnapshot, select_route,
};
use rtrt_security::{Profile, ScanReport};
use rtrt_templates::{Prompt, PromptRegistry};
use serde::{Deserialize, Serialize};
use tokio::io::AsyncWriteExt;
use tokio::sync::Mutex;
use tokio::sync::broadcast;

use crate::prelude::*;

/// Resolve and normalise the Ollama base URL (no trailing slash, no `/v1`).
pub(crate) fn ollama_base() -> String {
    let cfg = rtrt_core::Config::load().unwrap_or_default();
    let raw = cfg
        .embeddings
        .resolved_base_url(cfg.auto_compress.base_url.as_deref());
    let mut url = raw.trim_end_matches('/').to_string();
    if url.ends_with("/v1") {
        url.truncate(url.len() - 3);
    }
    url.trim_end_matches('/').to_string()
}

// ---------------------------------------------------------------------------
// GET /api/ollama/models  →  GET {base}/api/tags
// Response: [{ "name": String, "size_bytes": u64, "family": String, "modified_at": String }]
// ---------------------------------------------------------------------------

pub(crate) async fn ollama_models()
-> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    let url = format!("{}/api/tags", ollama_base());
    let resp = reqwest::get(&url)
        .await
        .map_err(|e| (StatusCode::BAD_GATEWAY, format!("ollama unreachable: {e}")))?;
    if !resp.status().is_success() {
        let code = resp.status().as_u16();
        let body = resp.text().await.unwrap_or_default();
        return Err((
            StatusCode::BAD_GATEWAY,
            format!("ollama /api/tags {code}: {body}"),
        ));
    }
    let raw: serde_json::Value = resp
        .json()
        .await
        .map_err(|e| (StatusCode::BAD_GATEWAY, format!("ollama decode: {e}")))?;
    let models: Vec<serde_json::Value> = raw
        .get("models")
        .and_then(|v| v.as_array())
        .cloned()
        .unwrap_or_default()
        .into_iter()
        .map(|m| {
            let family = m
                .get("details")
                .and_then(|d| d.get("family"))
                .and_then(|f| f.as_str())
                .unwrap_or("")
                .to_string();
            serde_json::json!({
                "name":        m.get("name").cloned().unwrap_or(serde_json::Value::Null),
                "size_bytes":  m.get("size").cloned().unwrap_or(serde_json::Value::Null),
                "family":      family,
                "modified_at": m.get("modified_at").cloned().unwrap_or(serde_json::Value::Null),
            })
        })
        .collect();
    Ok(Json(serde_json::json!({ "models": models })))
}

// ---------------------------------------------------------------------------
// GET /api/ollama/ps  →  GET {base}/api/ps
// Response: [{ "name": String, "size_bytes": u64, "size_vram_bytes": u64, "until": String }]
// ---------------------------------------------------------------------------

pub(crate) async fn ollama_ps() -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)>
{
    let url = format!("{}/api/ps", ollama_base());
    let resp = reqwest::get(&url)
        .await
        .map_err(|e| (StatusCode::BAD_GATEWAY, format!("ollama unreachable: {e}")))?;
    if !resp.status().is_success() {
        let code = resp.status().as_u16();
        let body = resp.text().await.unwrap_or_default();
        return Err((
            StatusCode::BAD_GATEWAY,
            format!("ollama /api/ps {code}: {body}"),
        ));
    }
    let raw: serde_json::Value = resp
        .json()
        .await
        .map_err(|e| (StatusCode::BAD_GATEWAY, format!("ollama decode: {e}")))?;
    let models: Vec<serde_json::Value> = raw
        .get("models")
        .and_then(|v| v.as_array())
        .cloned()
        .unwrap_or_default()
        .into_iter()
        .map(|m| {
            // size_vram is in the `size_vram` field from Ollama /api/ps.
            let size_vram = m
                .get("size_vram")
                .cloned()
                .unwrap_or(serde_json::Value::Null);
            serde_json::json!({
                "name":            m.get("name").cloned().unwrap_or(serde_json::Value::Null),
                "size_bytes":      m.get("size").cloned().unwrap_or(serde_json::Value::Null),
                "size_vram_bytes": size_vram,
                "until":           m.get("expires_at").cloned().unwrap_or(serde_json::Value::Null),
            })
        })
        .collect();
    Ok(Json(serde_json::json!({ "models": models })))
}

// ---------------------------------------------------------------------------
// POST /api/ollama/pull
// Body:    { "name": "bge-m3" }
// Response: { "ok": bool, "status": String }
//
// Uses stream:false — Ollama returns a single JSON object when done.
// Client timeout is intentionally large (pulls take minutes).
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
pub(crate) struct OllamaNameRequest {
    name: String,
}

pub(crate) async fn ollama_pull(
    Json(req): Json<OllamaNameRequest>,
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    let url = format!("{}/api/pull", ollama_base());
    // No timeout — model pulls can take many minutes on slow connections.
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(3600))
        .build()
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
    let body = serde_json::json!({ "name": req.name, "stream": false });
    let resp = client
        .post(&url)
        .json(&body)
        .send()
        .await
        .map_err(|e| (StatusCode::BAD_GATEWAY, format!("ollama unreachable: {e}")))?;
    if !resp.status().is_success() {
        let code = resp.status().as_u16();
        let text = resp.text().await.unwrap_or_default();
        return Err((
            StatusCode::BAD_GATEWAY,
            format!("ollama /api/pull {code}: {text}"),
        ));
    }
    let v: serde_json::Value = resp
        .json()
        .await
        .map_err(|e| (StatusCode::BAD_GATEWAY, format!("ollama decode: {e}")))?;
    if let Some(err) = v.get("error").and_then(|x| x.as_str()) {
        return Err((StatusCode::BAD_GATEWAY, err.to_string()));
    }
    let status = v
        .get("status")
        .and_then(|s| s.as_str())
        .unwrap_or("success")
        .to_string();
    Ok(Json(serde_json::json!({ "ok": true, "status": status })))
}

// ---------------------------------------------------------------------------
// DELETE /api/ollama/{name}
// Path param: model name (URL-encoded, e.g. `bge-m3%3Alatest`).
// Response: { "ok": bool }
// ---------------------------------------------------------------------------

pub(crate) async fn ollama_delete(
    axum::extract::Path(name): axum::extract::Path<String>,
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    let url = format!("{}/api/delete", ollama_base());
    let client = reqwest::Client::new();
    let body = serde_json::json!({ "name": name });
    let resp = client
        .delete(&url)
        .json(&body)
        .send()
        .await
        .map_err(|e| (StatusCode::BAD_GATEWAY, format!("ollama unreachable: {e}")))?;
    if !resp.status().is_success() {
        let code = resp.status().as_u16();
        let text = resp.text().await.unwrap_or_default();
        return Err((
            StatusCode::BAD_GATEWAY,
            format!("ollama /api/delete {code}: {text}"),
        ));
    }
    Ok(Json(serde_json::json!({ "ok": true })))
}
