//! (generated by module split — pure refactor, behavior identical)
#![allow(unused_imports)]

use std::collections::BTreeMap;
use std::path::PathBuf;
use std::process::Stdio;
use std::sync::Arc;

use anyhow::Result;
use axum::{
    Json, Router,
    extract::{Path as AxPath, State},
    http::StatusCode,
    response::{Html, IntoResponse},
    routing::{delete, get, post},
};
use rtrt_core::{
    OutputStyleLevel, read_output_style_level, read_output_style_level_for,
    write_output_style_level_for,
};
use rtrt_memory::{
    ClusterIndex, ConceptHierarchy, DetailedRecord, Embedder, MemoryStore, PayloadFilter,
    Summariser,
};
use rtrt_providers::{
    ChatMessage, ChatRequest, ChatResponse, Gateway, MetricsView, Prefer, Provider, RequestMetric,
    Role, RouteAlternative, RouteRequest, UsageSnapshot, select_route,
};
use rtrt_security::{Profile, ScanReport};
use rtrt_templates::{Prompt, PromptRegistry};
use serde::{Deserialize, Serialize};
use tokio::io::AsyncWriteExt;
use tokio::sync::Mutex;
use tokio::sync::broadcast;

use crate::prelude::*;

#[derive(Debug, Serialize)]
pub(crate) struct DetectedToolResponse {
    #[serde(flatten)]
    tool: rtrt_core::DetectedTool,
    has_api_key: bool,
}

pub(crate) async fn detect_tools_api() -> Json<Vec<DetectedToolResponse>> {
    Json(
        detected_tools_with_config_overrides()
            .into_iter()
            .map(|tool| {
                let has_api_key = provider_api_key_present(&tool);
                DetectedToolResponse { tool, has_api_key }
            })
            .collect(),
    )
}

#[derive(Debug, Deserialize)]
pub(crate) struct RouteQuery {
    prompt: String,
    #[serde(default)]
    prefer: Option<String>,
    #[serde(default)]
    capability: Option<String>,
}

#[derive(Debug, Serialize)]
pub(crate) struct RouteChosen {
    target: String,
    mode: rtrt_providers::Mode,
    model: Option<String>,
    cost_class: rtrt_core::CostClass,
    reason: String,
}

#[derive(Debug, Serialize)]
pub(crate) struct RouteUsageHeadroom {
    sources: Vec<String>,
    by_target: BTreeMap<String, RouteTargetHeadroom>,
}

#[derive(Debug, Serialize)]
pub(crate) struct RouteTargetHeadroom {
    used: Option<u64>,
    limit: Option<u64>,
    remaining: Option<u64>,
    label: String,
}

#[derive(Debug, Serialize)]
pub(crate) struct RouteApiResponse {
    chosen: RouteChosen,
    alternatives: Vec<RouteAlternative>,
    usage_headroom: RouteUsageHeadroom,
}

pub(crate) async fn route_api(
    axum::extract::Query(q): axum::extract::Query<RouteQuery>,
) -> axum::response::Response {
    if q.prompt.trim().is_empty() {
        return route_error(StatusCode::BAD_REQUEST, "prompt is required");
    }

    let prefer = match parse_route_prefer(q.prefer.as_deref()) {
        Ok(prefer) => prefer,
        Err(message) => return route_error(StatusCode::BAD_REQUEST, &message),
    };
    let capability = match parse_route_capability(q.capability.as_deref()) {
        Ok(capability) => capability,
        Err(message) => return route_error(StatusCode::BAD_REQUEST, &message),
    };

    let request = RouteRequest {
        capability,
        prefer,
        target: None,
        model: None,
        mode: None,
    };
    let tools = detected_tools_with_config_overrides();
    let usage = UsageSnapshot::load_best_effort();
    let decision = match select_route(&request, &tools, &usage) {
        Ok(decision) => decision,
        Err(e) => return route_error(StatusCode::BAD_REQUEST, &e.to_string()),
    };
    let usage_headroom = route_usage_headroom(&usage, &tools);
    let response = RouteApiResponse {
        chosen: RouteChosen {
            target: decision.target,
            mode: decision.mode,
            model: decision.model,
            cost_class: decision.cost_class,
            reason: decision.reason,
        },
        alternatives: decision.alternatives,
        usage_headroom,
    };
    Json(response).into_response()
}

pub(crate) fn route_error(status: StatusCode, message: &str) -> axum::response::Response {
    (
        status,
        Json(serde_json::json!({
            "error": message,
        })),
    )
        .into_response()
}

pub(crate) fn parse_route_prefer(value: Option<&str>) -> std::result::Result<Prefer, String> {
    match value
        .unwrap_or("cheapest")
        .trim()
        .to_ascii_lowercase()
        .as_str()
    {
        "" | "cheapest" => Ok(Prefer::Cheapest),
        "local" => Ok(Prefer::Local),
        "quality" => Ok(Prefer::Quality),
        other => Err(format!(
            "unknown prefer '{other}' (expected cheapest, local, or quality)"
        )),
    }
}

pub(crate) fn parse_route_capability(
    value: Option<&str>,
) -> std::result::Result<Option<rtrt_core::Capability>, String> {
    match value
        .unwrap_or_default()
        .trim()
        .to_ascii_lowercase()
        .as_str()
    {
        "" | "chat" | "general" => Ok(None),
        "code" => Ok(Some(rtrt_core::Capability::Code)),
        "reasoning" => Ok(Some(rtrt_core::Capability::Reasoning)),
        "vision" => Ok(Some(rtrt_core::Capability::Vision)),
        "embed" | "embedding" => Ok(Some(rtrt_core::Capability::Embed)),
        "agentic" => Ok(Some(rtrt_core::Capability::Agentic)),
        "summarize" | "summary" | "cheap-bulk" | "cheap_bulk" => {
            Ok(Some(rtrt_core::Capability::CheapBulk))
        }
        other => Err(format!(
            "unknown capability '{other}' (expected code, reasoning, chat, summarize, vision, embed, or agentic)"
        )),
    }
}

pub(crate) fn route_usage_headroom(
    usage: &UsageSnapshot,
    tools: &[rtrt_core::DetectedTool],
) -> RouteUsageHeadroom {
    let mut by_target = BTreeMap::new();
    for tool in tools.iter().filter(|tool| tool.installed && tool.enabled) {
        let headroom = usage.headroom(&tool.name);
        let view = match headroom {
            Some(quota) => RouteTargetHeadroom {
                used: Some(quota.used),
                limit: Some(quota.limit),
                remaining: Some(quota.remaining),
                label: format!("{}/{} tokens remaining", quota.remaining, quota.limit),
            },
            None => RouteTargetHeadroom {
                used: None,
                limit: None,
                remaining: None,
                label: "unknown".to_string(),
            },
        };
        by_target.insert(tool.name.clone(), view);
    }
    RouteUsageHeadroom {
        sources: usage.sources.clone(),
        by_target,
    }
}

pub(crate) fn provider_api_key_present(tool: &rtrt_core::DetectedTool) -> bool {
    matches!(tool.kind, rtrt_core::ToolKind::ProviderApi) && tool.installed && tool.path.is_none()
}

pub(crate) fn detected_tools_with_config_overrides() -> Vec<rtrt_core::DetectedTool> {
    let mut tools = rtrt_core::detect_tools();
    let Ok(cfg) = rtrt_core::Config::load() else {
        return tools;
    };

    for tool in &mut tools {
        let override_value = match tool.kind {
            rtrt_core::ToolKind::ProviderApi => cfg.providers.enabled_override(&tool.name),
            rtrt_core::ToolKind::CodingAgent
            | rtrt_core::ToolKind::LocalRuntime
            | rtrt_core::ToolKind::McpServer => cfg.agents.enabled_override(&tool.name),
        };
        if let Some(enabled) = override_value {
            tool.enabled = enabled;
        }
    }
    tools
}

#[derive(Debug, Deserialize)]
pub(crate) struct DetectToggleRequest {
    name: String,
    enabled: bool,
}

#[derive(Debug, Serialize)]
pub(crate) struct DetectToggleResponse {
    ok: bool,
    name: String,
    enabled: bool,
    section: String,
    path: String,
}

pub(crate) async fn toggle_detected_tool(
    Json(req): Json<DetectToggleRequest>,
) -> std::result::Result<Json<DetectToggleResponse>, (StatusCode, String)> {
    let name = req.name.trim();
    if name.is_empty() {
        return Err((StatusCode::BAD_REQUEST, "name is required".to_string()));
    }

    let detected = rtrt_core::detect_tools()
        .into_iter()
        .find(|tool| tool.name == name)
        .ok_or((StatusCode::NOT_FOUND, format!("tool not detected: {name}")))?;

    let mut cfg = rtrt_core::Config::load()
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
    let section = match detected.kind {
        rtrt_core::ToolKind::ProviderApi => {
            cfg.set_provider_enabled(name, req.enabled);
            "providers"
        }
        rtrt_core::ToolKind::CodingAgent
        | rtrt_core::ToolKind::LocalRuntime
        | rtrt_core::ToolKind::McpServer => {
            cfg.set_agent_enabled(name, req.enabled);
            "agents"
        }
    };

    let path = write_config_file(&cfg)?;
    Ok(Json(DetectToggleResponse {
        ok: true,
        name: name.to_string(),
        enabled: req.enabled,
        section: section.to_string(),
        path,
    }))
}
