//! (generated by module split — pure refactor, behavior identical)
#![allow(unused_imports)]

use std::collections::BTreeMap;
use std::path::PathBuf;
use std::process::Stdio;
use std::sync::Arc;

use anyhow::Result;
use axum::{
    Json, Router,
    extract::{Path as AxPath, State},
    http::StatusCode,
    response::{Html, IntoResponse},
    routing::{delete, get, post},
};
use rtrt_core::{
    OutputStyleLevel, read_output_style_level, read_output_style_level_for,
    write_output_style_level_for,
};
use rtrt_memory::{
    ClusterIndex, ConceptHierarchy, DetailedRecord, Embedder, MemoryStore, PayloadFilter,
    Summariser,
};
use rtrt_providers::{
    ChatMessage, ChatRequest, ChatResponse, Gateway, MetricsView, Prefer, Provider, RequestMetric,
    Role, RouteAlternative, RouteRequest, UsageSnapshot, select_route,
};
use rtrt_security::{Profile, ScanReport};
use rtrt_templates::{Prompt, PromptRegistry};
use serde::{Deserialize, Serialize};
use tokio::io::AsyncWriteExt;
use tokio::sync::Mutex;
use tokio::sync::broadcast;

use crate::prelude::*;

#[derive(Debug, Clone, Serialize)]
pub(crate) struct ProjectView {
    name: String,
    path: Option<String>,
    security_profile: Option<String>,
    /// Per-project embedding override (`None` = inherit global default).
    embeddings_enabled: Option<bool>,
    mem_count: usize,
}

/// `GET /api/projects` — union of registered config entries (path /
/// security_profile) and memory buckets (mem_count), merged by name.
pub(crate) async fn list_projects(
    State(state): State<AppState>,
) -> std::result::Result<Json<Vec<ProjectView>>, (StatusCode, String)> {
    use std::collections::BTreeMap;

    let mut views: BTreeMap<String, ProjectView> = BTreeMap::new();

    // Registered config entries first.
    let cfg = rtrt_core::Config::load()
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
    for entry in &cfg.projects {
        views.insert(
            entry.name.clone(),
            ProjectView {
                name: entry.name.clone(),
                path: entry.path.clone(),
                security_profile: entry.security_profile.clone(),
                embeddings_enabled: entry.embeddings_enabled,
                mem_count: 0,
            },
        );
    }

    // Memory buckets contribute counts (and may introduce memory-only names).
    if let Some(mem) = &state.memory {
        let guard = mem.lock().await;
        let projects = guard
            .projects()
            .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
        drop(guard);
        for (name, count, _last) in projects {
            // No name-pattern filtering: a row's project is decided by the
            // reattribution pass (transcript parent cwd), which folds stray
            // subagent / workflow captures under their real project, leaving
            // those buckets empty so they don't appear here at all.
            views
                .entry(name.clone())
                .and_modify(|v| v.mem_count = count)
                .or_insert(ProjectView {
                    name,
                    path: None,
                    security_profile: None,
                    embeddings_enabled: None,
                    mem_count: count,
                });
        }
    }

    // BTreeMap iteration is already sorted by name.
    Ok(Json(views.into_values().collect()))
}

#[derive(Debug, Deserialize)]
pub(crate) struct ProjectUpsertReq {
    name: String,
    #[serde(default)]
    path: Option<String>,
    #[serde(default)]
    security_profile: Option<String>,
    /// Per-project embedding override as a tri-state string so the handler can
    /// tell "field absent" (preserve existing) from an explicit choice:
    /// `"on"` -> Some(true), `"off"` -> Some(false), `"inherit"` -> None.
    /// (A bare `Option<bool>`/`Option<Option<bool>>` can't distinguish absent
    /// from JSON `null` — serde maps both to `None`.)
    #[serde(default)]
    embeddings_mode: Option<String>,
}

/// `PUT /api/projects` — upsert a project entry into the config registry.
pub(crate) async fn upsert_project(
    Json(req): Json<ProjectUpsertReq>,
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    let mut cfg = rtrt_core::Config::load()
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
    let name = req.name.clone();
    // Explicit choice wins; an absent field preserves the existing override.
    let embeddings_enabled = match req.embeddings_mode.as_deref() {
        Some("on") => Some(true),
        Some("off") => Some(false),
        Some("inherit") => None,
        _ => cfg.project(&name).and_then(|p| p.embeddings_enabled),
    };
    cfg.upsert_project(rtrt_core::ProjectEntry {
        name: req.name,
        path: req.path,
        security_profile: req.security_profile,
        embeddings_enabled,
    });

    let path = rtrt_core::Config::default_path().ok_or((
        StatusCode::INTERNAL_SERVER_ERROR,
        "cannot determine config path".to_string(),
    ))?;
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| {
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("create dir {}: {e}", parent.display()),
            )
        })?;
    }
    let s = toml::to_string_pretty(&cfg)
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
    std::fs::write(&path, s).map_err(|e| {
        (
            StatusCode::INTERNAL_SERVER_ERROR,
            format!("write {}: {e}", path.display()),
        )
    })?;
    Ok(Json(serde_json::json!({ "ok": true, "name": name })))
}
