//! (generated by module split — pure refactor, behavior identical)
#![allow(unused_imports)]

use std::collections::BTreeMap;
use std::path::PathBuf;
use std::process::Stdio;
use std::sync::Arc;

use anyhow::Result;
use axum::{
    Json, Router,
    extract::{Path as AxPath, State},
    http::StatusCode,
    response::{Html, IntoResponse},
    routing::{delete, get, post},
};
use rtrt_core::{
    OutputStyleLevel, read_output_style_level, read_output_style_level_for,
    write_output_style_level_for,
};
use rtrt_memory::{
    ClusterIndex, ConceptHierarchy, DetailedRecord, Embedder, MemoryStore, PayloadFilter,
    Summariser,
};
use rtrt_providers::{
    ChatMessage, ChatRequest, ChatResponse, Gateway, MetricsView, Prefer, Provider, RequestMetric,
    Role, RouteAlternative, RouteRequest, UsageSnapshot, select_route,
};
use rtrt_security::{Profile, ScanReport};
use rtrt_templates::{Prompt, PromptRegistry};
use serde::{Deserialize, Serialize};
use tokio::io::AsyncWriteExt;
use tokio::sync::Mutex;
use tokio::sync::broadcast;

use crate::prelude::*;

#[derive(Debug, Clone, Copy, Serialize)]
pub(crate) struct DashboardWindow {
    label: &'static str,
    since_unix: Option<i64>,
    proxy_modifier: Option<&'static str>,
}

impl DashboardWindow {
    fn parse(raw: Option<&str>) -> Self {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs() as i64)
            .unwrap_or(0);
        match raw.unwrap_or("all").trim().to_ascii_lowercase().as_str() {
            "1h" => Self {
                label: "1h",
                since_unix: Some(now.saturating_sub(SECS_PER_HOUR)),
                proxy_modifier: Some("-1 hours"),
            },
            "6h" => Self {
                label: "6h",
                since_unix: Some(now.saturating_sub(SECS_PER_HOUR * 6)),
                proxy_modifier: Some("-6 hours"),
            },
            "24h" => Self {
                label: "24h",
                since_unix: Some(now.saturating_sub(SECS_PER_DAY)),
                proxy_modifier: Some("-24 hours"),
            },
            "7d" => Self {
                label: "7d",
                since_unix: Some(now.saturating_sub(SECS_PER_DAY * 7)),
                proxy_modifier: Some("-7 days"),
            },
            "30d" => Self {
                label: "30d",
                since_unix: Some(now.saturating_sub(SECS_PER_DAY * 30)),
                proxy_modifier: Some("-30 days"),
            },
            _ => Self {
                label: "all",
                since_unix: None,
                proxy_modifier: None,
            },
        }
    }
}

#[derive(Debug, Clone, Serialize)]
pub(crate) struct SavingsCoverage {
    reduced: i64,
    total: i64,
}

#[derive(Debug, Clone, Serialize)]
pub(crate) struct SavingsProject {
    project: String,
    count: i64,
    reduced_count: i64,
    saved_chars: i64,
    saved_tokens: i64,
    original_chars: i64,
    with_rtrt_chars: i64,
    saved_pct: Option<f64>,
    effective_pct: Option<f64>,
    coverage: SavingsCoverage,
    #[serde(skip)]
    effective_pct_sum: f64,
}

#[derive(Debug, Clone, Serialize)]
pub(crate) struct SavingsSource {
    name: String,
    label: String,
    available: bool,
    count: i64,
    saved_chars: i64,
    saved_tokens: i64,
    original_chars: i64,
    with_rtrt_chars: i64,
    saved_pct: Option<f64>,
    effective_pct: Option<f64>,
    coverage: SavingsCoverage,
    source: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    level: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    active: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    measurement_note: Option<String>,
    by_project: Vec<SavingsProject>,
}

#[derive(Debug, Clone, Serialize)]
pub(crate) struct ProjectSourceRollup {
    count: i64,
    reduced_count: i64,
    saved_chars: i64,
    saved_tokens: i64,
    original_chars: i64,
    with_rtrt_chars: i64,
    saved_pct: Option<f64>,
    effective_pct: Option<f64>,
    coverage: SavingsCoverage,
}

#[derive(Debug, Clone, Serialize)]
pub(crate) struct ProjectRollup {
    project: String,
    saved_chars: i64,
    saved_tokens: i64,
    original_chars: i64,
    with_rtrt_chars: i64,
    saved_pct: Option<f64>,
    by_source: BTreeMap<String, ProjectSourceRollup>,
}

pub(crate) fn savings_source(
    name: &str,
    label: &str,
    source: &str,
    available: bool,
    mut by_project: Vec<SavingsProject>,
) -> SavingsSource {
    by_project.sort_by(|a, b| {
        b.saved_tokens
            .cmp(&a.saved_tokens)
            .then_with(|| b.saved_chars.cmp(&a.saved_chars))
            .then_with(|| a.project.cmp(&b.project))
    });
    let count = by_project.iter().map(|p| p.count).sum();
    let reduced_count = by_project.iter().map(|p| p.reduced_count).sum();
    let saved_chars = by_project.iter().map(|p| p.saved_chars).sum();
    let original_chars = by_project.iter().map(|p| p.original_chars).sum();
    let with_rtrt_chars = by_project.iter().map(|p| p.with_rtrt_chars).sum();
    let effective_pct_sum: f64 = by_project.iter().map(|p| p.effective_pct_sum).sum();
    SavingsSource {
        name: name.to_string(),
        label: label.to_string(),
        available: available && count > 0,
        count,
        saved_chars,
        saved_tokens: estimate_saved_tokens(saved_chars),
        original_chars,
        with_rtrt_chars,
        saved_pct: saved_pct(saved_chars, original_chars),
        effective_pct: (reduced_count > 0).then_some(effective_pct_sum / reduced_count as f64),
        coverage: SavingsCoverage {
            reduced: reduced_count,
            total: count,
        },
        source: source.to_string(),
        level: None,
        active: None,
        measurement_note: None,
        by_project,
    }
}

pub(crate) const OUTPUT_OPTIMIZER_MEASUREMENT_NOTE: &str =
    "Deterministic compress only — terse-mode injection savings are not measurable";

pub(crate) fn output_optimizer_active(level: &str) -> bool {
    !matches!(
        level.trim().to_ascii_lowercase().as_str(),
        "off" | "none" | "disabled"
    )
}

pub(crate) fn projects_rollup(sources: &[SavingsSource]) -> Vec<ProjectRollup> {
    let mut projects: BTreeMap<String, ProjectRollup> = BTreeMap::new();
    for source in sources {
        for item in &source.by_project {
            let entry = projects
                .entry(item.project.clone())
                .or_insert_with(|| ProjectRollup {
                    project: item.project.clone(),
                    saved_chars: 0,
                    saved_tokens: 0,
                    original_chars: 0,
                    with_rtrt_chars: 0,
                    saved_pct: None,
                    by_source: BTreeMap::new(),
                });
            entry.saved_chars += item.saved_chars;
            entry.original_chars += item.original_chars;
            entry.with_rtrt_chars += item.with_rtrt_chars;
            entry.by_source.insert(
                source.name.clone(),
                ProjectSourceRollup {
                    count: item.count,
                    reduced_count: item.reduced_count,
                    saved_chars: item.saved_chars,
                    saved_tokens: item.saved_tokens,
                    original_chars: item.original_chars,
                    with_rtrt_chars: item.with_rtrt_chars,
                    saved_pct: item.saved_pct,
                    effective_pct: item.effective_pct,
                    coverage: item.coverage.clone(),
                },
            );
        }
    }
    for project in projects.values_mut() {
        project.saved_tokens = estimate_saved_tokens(project.saved_chars);
        project.saved_pct = saved_pct(project.saved_chars, project.original_chars);
    }
    let mut projects: Vec<ProjectRollup> = projects.into_values().collect();
    projects.sort_by(|a, b| {
        b.saved_tokens
            .cmp(&a.saved_tokens)
            .then_with(|| b.saved_chars.cmp(&a.saved_chars))
            .then_with(|| a.project.cmp(&b.project))
    });
    projects
}

pub(crate) fn memory_savings_by_project(
    conn: &rusqlite::Connection,
    project: Option<&str>,
    window: DashboardWindow,
    notes: &mut Vec<String>,
) -> (bool, Vec<SavingsProject>) {
    let mut stmt = match conn.prepare(
        "SELECT project, COUNT(*) AS row_count, \
                COALESCE(SUM(CASE WHEN body_full IS NOT NULL AND LENGTH(body_full) > LENGTH(body) THEN 1 ELSE 0 END), 0) AS reduced_count, \
                COALESCE(SUM(CASE WHEN body_full IS NOT NULL AND LENGTH(body_full) > LENGTH(body) THEN LENGTH(body_full) - LENGTH(body) ELSE 0 END), 0) AS saved_chars, \
                COALESCE(SUM(CASE WHEN body_full IS NOT NULL THEN LENGTH(body_full) ELSE LENGTH(body) END), 0) AS original_chars, \
                COALESCE(SUM(LENGTH(body)), 0) AS with_rtrt_chars, \
                COALESCE(SUM(CASE WHEN body_full IS NOT NULL AND LENGTH(body_full) > LENGTH(body) AND LENGTH(body_full) > 0 THEN ((LENGTH(body_full) - LENGTH(body)) * 100.0 / LENGTH(body_full)) ELSE 0 END), 0.0) AS effective_pct_sum \
         FROM memories \
         WHERE (?1 IS NULL OR project = ?1) AND (?2 IS NULL OR created_at >= ?2) \
         GROUP BY project",
    ) {
        Ok(stmt) => stmt,
        Err(e) => {
            notes.push(format!("Memory savings query unavailable: {e}."));
            return (false, Vec::new());
        }
    };
    let rows = match stmt.query_map(rusqlite::params![project, window.since_unix], |row| {
        let project = normalize_project(row.get::<_, Option<String>>(0)?);
        let count = row.get::<_, i64>(1)?;
        let reduced_count = nonnegative_i64(row.get::<_, i64>(2)?);
        let saved_chars = nonnegative_i64(row.get::<_, i64>(3)?);
        let original_chars = nonnegative_i64(row.get::<_, i64>(4)?);
        let with_rtrt_chars = nonnegative_i64(row.get::<_, i64>(5)?);
        let effective_pct_sum = row.get::<_, f64>(6)?.max(0.0);
        Ok(SavingsProject {
            project,
            count,
            reduced_count,
            saved_chars,
            saved_tokens: estimate_saved_tokens(saved_chars),
            original_chars,
            with_rtrt_chars,
            saved_pct: saved_pct(saved_chars, original_chars),
            effective_pct: (reduced_count > 0).then_some(effective_pct_sum / reduced_count as f64),
            coverage: SavingsCoverage {
                reduced: reduced_count,
                total: count,
            },
            effective_pct_sum,
        })
    }) {
        Ok(rows) => rows,
        Err(e) => {
            notes.push(format!("Memory savings query failed: {e}."));
            return (false, Vec::new());
        }
    };
    let mut projects = Vec::new();
    for row in rows {
        match row {
            Ok(project) => projects.push(project),
            Err(e) => {
                notes.push(format!("Memory savings row skipped: {e}."));
                return (false, projects);
            }
        }
    }
    (true, projects)
}

pub(crate) fn output_savings_by_project(
    conn: &rusqlite::Connection,
    project: Option<&str>,
    window: DashboardWindow,
    notes: &mut Vec<String>,
) -> (bool, Vec<SavingsProject>) {
    let mut stmt = match conn.prepare(
        "SELECT project, metadata FROM memories \
         WHERE metadata IS NOT NULL AND (?1 IS NULL OR project = ?1) AND (?2 IS NULL OR created_at >= ?2)",
    ) {
        Ok(stmt) => stmt,
        Err(e) => {
            notes.push(format!("Output Optimizer query unavailable: {e}."));
            return (false, Vec::new());
        }
    };
    let rows = match stmt.query_map(rusqlite::params![project, window.since_unix], |row| {
        Ok((row.get::<_, Option<String>>(0)?, row.get::<_, String>(1)?))
    }) {
        Ok(rows) => rows,
        Err(e) => {
            notes.push(format!("Output Optimizer query failed: {e}."));
            return (false, Vec::new());
        }
    };
    let mut grouped: BTreeMap<String, (i64, i64, i64, i64, i64, f64)> = BTreeMap::new();
    for row in rows {
        match row {
            Ok((project, raw)) => {
                if let Some((saved_chars, original_chars, with_rtrt_chars)) =
                    metadata_savings(&raw, "compress")
                {
                    let entry = grouped
                        .entry(normalize_project(project))
                        .or_insert((0, 0, 0, 0, 0, 0.0));
                    entry.0 += 1;
                    entry.1 += saved_chars;
                    entry.2 += original_chars;
                    entry.3 += with_rtrt_chars;
                    if saved_chars > 0 && original_chars > 0 {
                        entry.4 += 1;
                        entry.5 += saved_chars as f64 / original_chars as f64 * 100.0;
                    }
                }
            }
            Err(e) => {
                notes.push(format!("Output Optimizer row skipped: {e}."));
                return (false, Vec::new());
            }
        }
    }
    let projects = grouped
        .into_iter()
        .map(
            |(
                project,
                (
                    count,
                    saved_chars,
                    original_chars,
                    with_rtrt_chars,
                    reduced_count,
                    effective_pct_sum,
                ),
            )| {
                let saved_chars = nonnegative_i64(saved_chars);
                let original_chars = nonnegative_i64(original_chars);
                let with_rtrt_chars = nonnegative_i64(with_rtrt_chars);
                let reduced_count = nonnegative_i64(reduced_count);
                SavingsProject {
                    project,
                    count,
                    reduced_count,
                    saved_chars,
                    saved_tokens: estimate_saved_tokens(saved_chars),
                    original_chars,
                    with_rtrt_chars,
                    saved_pct: saved_pct(saved_chars, original_chars),
                    effective_pct: (reduced_count > 0)
                        .then_some(effective_pct_sum / reduced_count as f64),
                    coverage: SavingsCoverage {
                        reduced: reduced_count,
                        total: count,
                    },
                    effective_pct_sum,
                }
            },
        )
        .collect();
    (true, projects)
}

pub(crate) fn command_savings_by_project(
    db_path: &std::path::Path,
    project: Option<&str>,
    window: DashboardWindow,
    notes: &mut Vec<String>,
) -> (bool, Vec<SavingsProject>) {
    if !db_path.exists() {
        notes.push(format!(
            "Command Optimizer database not found at {}.",
            db_path.display()
        ));
        return (false, Vec::new());
    }
    let conn = match rusqlite::Connection::open_with_flags(
        db_path,
        rusqlite::OpenFlags::SQLITE_OPEN_READ_ONLY | rusqlite::OpenFlags::SQLITE_OPEN_NO_MUTEX,
    ) {
        Ok(conn) => conn,
        Err(e) => {
            notes.push(format!("Command Optimizer database unavailable: {e}."));
            return (false, Vec::new());
        }
    };
    let mut stmt = match conn.prepare(
        "SELECT project, COUNT(*) AS run_count, COALESCE(SUM(saved_chars), 0) AS saved_chars, \
                COALESCE(SUM(input_chars), 0) AS original_chars, \
                COALESCE(SUM(output_chars), 0) AS with_rtrt_chars, \
                COALESCE(SUM(CASE WHEN saved_chars > 0 THEN 1 ELSE 0 END), 0) AS reduced_count, \
                COALESCE(SUM(CASE WHEN saved_chars > 0 AND input_chars > 0 THEN saved_chars * 100.0 / input_chars ELSE 0 END), 0.0) AS effective_pct_sum \
         FROM proxy_runs \
         WHERE (?1 IS NULL OR project = ?1) AND (?2 IS NULL OR datetime(ts) >= datetime('now', ?2)) \
         GROUP BY project",
    ) {
        Ok(stmt) => stmt,
        Err(e) => {
            notes.push(format!("Command Optimizer stats unavailable: {e}."));
            return (false, Vec::new());
        }
    };
    let rows = match stmt.query_map(rusqlite::params![project, window.proxy_modifier], |row| {
        let project = normalize_project(row.get::<_, Option<String>>(0)?);
        let count = row.get::<_, i64>(1)?;
        let saved_chars = nonnegative_i64(row.get::<_, i64>(2)?);
        let original_chars = nonnegative_i64(row.get::<_, i64>(3)?);
        let with_rtrt_chars = nonnegative_i64(row.get::<_, i64>(4)?);
        let reduced_count = nonnegative_i64(row.get::<_, i64>(5)?);
        let effective_pct_sum = row.get::<_, f64>(6)?.max(0.0);
        Ok(SavingsProject {
            project,
            count,
            reduced_count,
            saved_chars,
            saved_tokens: estimate_saved_tokens(saved_chars),
            original_chars,
            with_rtrt_chars,
            saved_pct: saved_pct(saved_chars, original_chars),
            effective_pct: (reduced_count > 0).then_some(effective_pct_sum / reduced_count as f64),
            coverage: SavingsCoverage {
                reduced: reduced_count,
                total: count,
            },
            effective_pct_sum,
        })
    }) {
        Ok(rows) => rows,
        Err(e) => {
            notes.push(format!("Command Optimizer stats query failed: {e}."));
            return (false, Vec::new());
        }
    };
    let mut projects = Vec::new();
    for row in rows {
        match row {
            Ok(project) => projects.push(project),
            Err(e) => {
                notes.push(format!("Command Optimizer stats row skipped: {e}."));
                return (false, projects);
            }
        }
    }
    (true, projects)
}

pub(crate) const GAIN_MIN_ROWS: usize = 5;
pub(crate) const GAIN_MAX_ROWS: usize = 50;

pub(crate) fn integer_sqrt_ceil(n: u64) -> u64 {
    let mut root = 0u64;
    while root.saturating_mul(root) < n {
        root = root.saturating_add(1);
    }
    root
}

pub(crate) fn dynamic_gain_count(total_runs: i64) -> usize {
    let total = u64::try_from(total_runs.max(1)).unwrap_or(1);
    usize::try_from(integer_sqrt_ceil(total))
        .unwrap_or(GAIN_MAX_ROWS)
        .clamp(GAIN_MIN_ROWS, GAIN_MAX_ROWS)
}

pub(crate) fn usize_to_i64(value: usize) -> i64 {
    i64::try_from(value).unwrap_or(i64::MAX)
}

pub(crate) fn nonnegative_i64(value: i64) -> i64 {
    value.max(0)
}

#[derive(Debug, Clone, Serialize)]
pub(crate) struct GainCommand {
    command: String,
    runs: i64,
    reduced_runs: i64,
    input_chars: i64,
    output_chars: i64,
    saved_chars: i64,
    saved_tokens: i64,
    saved_pct: f64,
    effective_pct: Option<f64>,
    coverage: SavingsCoverage,
}

#[derive(Debug, Clone, Serialize)]
pub(crate) struct GainProject {
    project: String,
    runs: i64,
    reduced_runs: i64,
    input_chars: i64,
    output_chars: i64,
    saved_chars: i64,
    saved_tokens: i64,
    saved_pct: f64,
    effective_pct: Option<f64>,
    coverage: SavingsCoverage,
}

#[derive(Debug, Clone, Serialize)]
pub(crate) struct GainRun {
    ts: String,
    project: String,
    original_cmd: String,
    mode: String,
    input_chars: i64,
    output_chars: i64,
    saved_chars: i64,
    saved_tokens: i64,
    saved_pct: f64,
    exec_ms: i64,
}

#[derive(Debug, Deserialize)]
pub(crate) struct GainQuery {
    project: Option<String>,
    window: Option<String>,
}

pub(crate) async fn gain(
    axum::extract::Query(q): axum::extract::Query<GainQuery>,
) -> Json<serde_json::Value> {
    let project = q.project.as_deref().filter(|p| !p.trim().is_empty());
    let window = DashboardWindow::parse(q.window.as_deref());
    let db_path = proxy_stats_path();
    if !db_path.exists() {
        return Json(serde_json::json!({
            "available": false,
            "reason": "database_missing",
            "path": db_path.display().to_string(),
        }));
    }

    let conn = match rusqlite::Connection::open_with_flags(
        &db_path,
        rusqlite::OpenFlags::SQLITE_OPEN_READ_ONLY | rusqlite::OpenFlags::SQLITE_OPEN_NO_MUTEX,
    ) {
        Ok(conn) => conn,
        Err(e) => {
            return Json(serde_json::json!({
                "available": false,
                "reason": "database_unavailable",
                "error": e.to_string(),
                "path": db_path.display().to_string(),
            }));
        }
    };

    let (total_runs, total_input_chars, total_output_chars, total_saved_chars, reduced_runs, effective_pct_sum) = match conn.query_row(
        "SELECT COUNT(*), COALESCE(SUM(input_chars), 0), COALESCE(SUM(output_chars), 0), \
                COALESCE(SUM(saved_chars), 0), \
                COALESCE(SUM(CASE WHEN saved_chars > 0 THEN 1 ELSE 0 END), 0), \
                COALESCE(SUM(CASE WHEN saved_chars > 0 AND input_chars > 0 THEN saved_chars * 100.0 / input_chars ELSE 0 END), 0.0) \
         FROM proxy_runs WHERE (?1 IS NULL OR project = ?1) AND (?2 IS NULL OR datetime(ts) >= datetime('now', ?2))",
        rusqlite::params![project, window.proxy_modifier],
        |row| {
            Ok((
                row.get::<_, i64>(0)?,
                row.get::<_, i64>(1)?,
                row.get::<_, i64>(2)?,
                row.get::<_, i64>(3)?,
                row.get::<_, i64>(4)?,
                row.get::<_, f64>(5)?,
            ))
        },
    ) {
        Ok(row) => row,
        Err(e) => {
            return Json(serde_json::json!({
                "available": false,
                "reason": "table_unavailable",
                "error": e.to_string(),
                "path": db_path.display().to_string(),
            }));
        }
    };

    let total_runs = nonnegative_i64(total_runs);
    let total_input_chars = nonnegative_i64(total_input_chars);
    let total_output_chars = nonnegative_i64(total_output_chars);
    let total_saved_chars = nonnegative_i64(total_saved_chars);
    let reduced_runs = nonnegative_i64(reduced_runs);
    if total_runs == 0 {
        return Json(serde_json::json!({
            "available": false,
            "reason": "no_data_in_window",
            "scope": project.unwrap_or("all"),
            "window": window.label,
            "path": db_path.display().to_string(),
            "top_commands": [],
            "per_project": [],
            "recent_history": [],
        }));
    }
    let display_count = dynamic_gain_count(total_runs);
    let display_count_i64 = usize_to_i64(display_count);

    let top_commands = match load_gain_top_commands(&conn, project, window, display_count_i64) {
        Ok(rows) => rows,
        Err(e) => {
            return Json(serde_json::json!({
                "available": false,
                "reason": "top_commands_unavailable",
                "error": e.to_string(),
                "path": db_path.display().to_string(),
            }));
        }
    };
    let per_project = match load_gain_projects(&conn, project, window) {
        Ok(rows) => rows,
        Err(e) => {
            return Json(serde_json::json!({
                "available": false,
                "reason": "projects_unavailable",
                "error": e.to_string(),
                "path": db_path.display().to_string(),
            }));
        }
    };
    let recent_history = match load_gain_recent(&conn, project, window, display_count_i64) {
        Ok(rows) => rows,
        Err(e) => {
            return Json(serde_json::json!({
                "available": false,
                "reason": "history_unavailable",
                "error": e.to_string(),
                "path": db_path.display().to_string(),
            }));
        }
    };

    Json(serde_json::json!({
        "available": true,
        "scope": project.unwrap_or("all"),
        "window": window.label,
        "path": db_path.display().to_string(),
        "total_runs": total_runs,
        "reduced_runs": reduced_runs,
        "input_chars": total_input_chars,
        "total_input_chars": total_input_chars,
        "output_chars": total_output_chars,
        "total_output_chars": total_output_chars,
        "total_saved_chars": total_saved_chars,
        "total_saved_tokens": estimate_saved_tokens(total_saved_chars),
        "saved_pct": saved_pct_or_zero(total_saved_chars, total_input_chars),
        "effective_pct": (reduced_runs > 0).then_some(effective_pct_sum / reduced_runs as f64),
        "coverage": SavingsCoverage { reduced: reduced_runs, total: total_runs },
        "token_estimate": "chars/4",
        "display_count": display_count,
        "top_commands": top_commands,
        "per_project": per_project,
        "recent_history": recent_history,
    }))
}

pub(crate) fn load_gain_top_commands(
    conn: &rusqlite::Connection,
    project: Option<&str>,
    window: DashboardWindow,
    limit: i64,
) -> rusqlite::Result<Vec<GainCommand>> {
    let mut stmt = conn.prepare(
        "SELECT original_cmd, COUNT(*), COALESCE(SUM(input_chars), 0), COALESCE(SUM(output_chars), 0), \
                COALESCE(SUM(saved_chars), 0), \
                COALESCE(SUM(CASE WHEN saved_chars > 0 THEN 1 ELSE 0 END), 0), \
                COALESCE(SUM(CASE WHEN saved_chars > 0 AND input_chars > 0 THEN saved_chars * 100.0 / input_chars ELSE 0 END), 0.0) \
         FROM proxy_runs \
         WHERE (?1 IS NULL OR project = ?1) AND (?2 IS NULL OR datetime(ts) >= datetime('now', ?2)) \
         GROUP BY original_cmd \
         ORDER BY COALESCE(SUM(saved_chars), 0) DESC, COUNT(*) DESC, original_cmd ASC \
         LIMIT ?3",
    )?;
    let rows = stmt.query_map(
        rusqlite::params![project, window.proxy_modifier, limit],
        |row| {
            let input_chars = nonnegative_i64(row.get::<_, i64>(2)?);
            let output_chars = nonnegative_i64(row.get::<_, i64>(3)?);
            let saved_chars = nonnegative_i64(row.get::<_, i64>(4)?);
            let reduced_runs = nonnegative_i64(row.get::<_, i64>(5)?);
            let effective_pct_sum = row.get::<_, f64>(6)?.max(0.0);
            let pct = saved_pct_or_zero(saved_chars, input_chars);
            let runs = nonnegative_i64(row.get::<_, i64>(1)?);
            Ok(GainCommand {
                command: row.get(0)?,
                runs,
                reduced_runs,
                input_chars,
                output_chars,
                saved_chars,
                saved_tokens: estimate_saved_tokens(saved_chars),
                saved_pct: pct,
                effective_pct: (reduced_runs > 0)
                    .then_some(effective_pct_sum / reduced_runs as f64),
                coverage: SavingsCoverage {
                    reduced: reduced_runs,
                    total: runs,
                },
            })
        },
    )?;
    rows.collect()
}

pub(crate) fn load_gain_projects(
    conn: &rusqlite::Connection,
    project: Option<&str>,
    window: DashboardWindow,
) -> rusqlite::Result<Vec<GainProject>> {
    let mut stmt = conn.prepare(
        "SELECT project, COUNT(*), COALESCE(SUM(input_chars), 0), COALESCE(SUM(output_chars), 0), \
                COALESCE(SUM(saved_chars), 0), \
                COALESCE(SUM(CASE WHEN saved_chars > 0 THEN 1 ELSE 0 END), 0), \
                COALESCE(SUM(CASE WHEN saved_chars > 0 AND input_chars > 0 THEN saved_chars * 100.0 / input_chars ELSE 0 END), 0.0) \
         FROM proxy_runs \
         WHERE (?1 IS NULL OR project = ?1) AND (?2 IS NULL OR datetime(ts) >= datetime('now', ?2)) \
         GROUP BY project \
         ORDER BY COALESCE(SUM(saved_chars), 0) DESC, COUNT(*) DESC, project ASC",
    )?;
    let rows = stmt.query_map(rusqlite::params![project, window.proxy_modifier], |row| {
        let input_chars = nonnegative_i64(row.get::<_, i64>(2)?);
        let output_chars = nonnegative_i64(row.get::<_, i64>(3)?);
        let saved_chars = nonnegative_i64(row.get::<_, i64>(4)?);
        let reduced_runs = nonnegative_i64(row.get::<_, i64>(5)?);
        let effective_pct_sum = row.get::<_, f64>(6)?.max(0.0);
        let runs = nonnegative_i64(row.get::<_, i64>(1)?);
        Ok(GainProject {
            project: normalize_project(row.get::<_, Option<String>>(0)?),
            runs,
            reduced_runs,
            input_chars,
            output_chars,
            saved_chars,
            saved_tokens: estimate_saved_tokens(saved_chars),
            saved_pct: saved_pct_or_zero(saved_chars, input_chars),
            effective_pct: (reduced_runs > 0).then_some(effective_pct_sum / reduced_runs as f64),
            coverage: SavingsCoverage {
                reduced: reduced_runs,
                total: runs,
            },
        })
    })?;
    rows.collect()
}

pub(crate) fn load_gain_recent(
    conn: &rusqlite::Connection,
    project: Option<&str>,
    window: DashboardWindow,
    limit: i64,
) -> rusqlite::Result<Vec<GainRun>> {
    let mut stmt = conn.prepare(
        "SELECT ts, project, original_cmd, mode, input_chars, output_chars, saved_chars, saved_pct, exec_ms \
         FROM proxy_runs \
         WHERE (?1 IS NULL OR project = ?1) AND (?2 IS NULL OR datetime(ts) >= datetime('now', ?2)) \
         ORDER BY id DESC \
         LIMIT ?3",
    )?;
    let rows = stmt.query_map(
        rusqlite::params![project, window.proxy_modifier, limit],
        |row| {
            let input_chars = nonnegative_i64(row.get::<_, i64>(4)?);
            let saved_chars = nonnegative_i64(row.get::<_, i64>(6)?);
            Ok(GainRun {
                ts: row.get(0)?,
                project: normalize_project(row.get::<_, Option<String>>(1)?),
                original_cmd: row.get(2)?,
                mode: row.get(3)?,
                input_chars,
                output_chars: nonnegative_i64(row.get::<_, i64>(5)?),
                saved_chars,
                saved_tokens: estimate_saved_tokens(saved_chars),
                saved_pct: saved_pct_or_zero(saved_chars, input_chars),
                exec_ms: nonnegative_i64(row.get::<_, i64>(8)?),
            })
        },
    )?;
    rows.collect()
}

#[derive(Debug, Deserialize)]
pub(crate) struct OverviewQuery {
    project: Option<String>,
    window: Option<String>,
}

/// Effective Command Optimizer reduction over the REDUCED runs only (those that
/// actually filtered output, `saved_chars > 0`), returned as
/// `(saved_chars, input_chars)`. Passthroughs are excluded so they do not dilute
/// the agent-token rate toward zero — this mirrors the status line's
/// `load_effective_reduction`. Scoped to `project` when given, else global.
pub(crate) fn command_effective_reduction(
    db_path: &std::path::Path,
    project: Option<&str>,
    window: DashboardWindow,
) -> (i64, i64) {
    if !db_path.exists() {
        return (0, 0);
    }
    let Ok(conn) = rusqlite::Connection::open_with_flags(
        db_path,
        rusqlite::OpenFlags::SQLITE_OPEN_READ_ONLY | rusqlite::OpenFlags::SQLITE_OPEN_NO_MUTEX,
    ) else {
        return (0, 0);
    };
    conn.query_row(
        "SELECT COALESCE(SUM(saved_chars), 0), COALESCE(SUM(input_chars), 0) \
         FROM proxy_runs \
         WHERE saved_chars > 0 \
           AND (?1 IS NULL OR project = ?1) \
           AND (?2 IS NULL OR datetime(ts) >= datetime('now', ?2))",
        rusqlite::params![project, window.proxy_modifier],
        |row| Ok((nonnegative_i64(row.get(0)?), nonnegative_i64(row.get(1)?))),
    )
    .unwrap_or((0, 0))
}

/// Total recall-reuse chars from `~/.rtrt/recall-savings.tsv` (lines
/// `project\tchars`). Summed for `project` when scoped, else across all
/// projects. Mirrors the CLI's `read_recall_savings`. Recalled context is reused
/// instead of being re-derived from source, so it counts as agent-token savings.
pub(crate) fn read_recall_savings(project: Option<&str>) -> i64 {
    let path = std::env::var_os("HOME")
        .or_else(|| std::env::var_os("USERPROFILE"))
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".rtrt")
        .join("recall-savings.tsv");
    let Ok(content) = std::fs::read_to_string(&path) else {
        return 0;
    };
    let mut total: i64 = 0;
    for line in content.lines() {
        let mut fields = line.split('\t');
        if let (Some(p), Some(c)) = (fields.next(), fields.next())
            && project.is_none_or(|scope| scope == p)
        {
            total = total.saturating_add(c.trim().parse::<i64>().unwrap_or(0).max(0));
        }
    }
    total
}

pub(crate) async fn optimizer_overview(
    State(state): State<AppState>,
    axum::extract::Query(q): axum::extract::Query<OverviewQuery>,
) -> Json<serde_json::Value> {
    let project = q.project.as_deref().filter(|p| !p.is_empty());
    let window = DashboardWindow::parse(q.window.as_deref());
    let mut notes = Vec::new();

    let (memory_available, memory_by_project, output_available, output_by_project) =
        if !state.memory_path.exists() {
            notes.push(format!(
                "Memory database not found at {}.",
                state.memory_path.display()
            ));
            (false, Vec::new(), false, Vec::new())
        } else {
            match rusqlite::Connection::open(&state.memory_path) {
                Ok(conn) => {
                    let (memory_available, memory_by_project) =
                        memory_savings_by_project(&conn, project, window, &mut notes);
                    let (output_available, output_by_project) =
                        output_savings_by_project(&conn, project, window, &mut notes);
                    (
                        memory_available,
                        memory_by_project,
                        output_available,
                        output_by_project,
                    )
                }
                Err(e) => {
                    notes.push(format!("Memory database unavailable: {e}."));
                    (false, Vec::new(), false, Vec::new())
                }
            }
        };

    let proxy_path = proxy_stats_path();
    let (command_available, command_by_project) =
        command_savings_by_project(&proxy_path, project, window, &mut notes);

    let output_level = read_output_style_level().as_str().to_string();
    let mut output_source = savings_source(
        "output_optimizer",
        "Output Optimizer",
        "memories metadata source=compress saved_chars",
        output_available,
        output_by_project,
    );
    output_source.level = Some(output_level.clone());
    output_source.active = Some(output_optimizer_active(&output_level));
    output_source.measurement_note = Some(OUTPUT_OPTIMIZER_MEASUREMENT_NOTE.to_string());

    let sources = vec![
        savings_source(
            "memory",
            "Memory",
            "SUM(length(body_full) - length(body)) from memories",
            memory_available,
            memory_by_project,
        ),
        output_source,
        savings_source(
            "command_optimizer",
            "Command Optimizer",
            "~/.rtrt/proxy-stats.sqlite proxy_runs saved_chars",
            command_available,
            command_by_project,
        ),
    ];
    let total_saved_chars: i64 = sources.iter().map(|source| source.saved_chars).sum();
    let total_original_chars: i64 = sources.iter().map(|source| source.original_chars).sum();
    let total_with_rtrt_chars: i64 = sources.iter().map(|source| source.with_rtrt_chars).sum();
    let total_saved_tokens = estimate_saved_tokens(total_saved_chars);
    let projects = projects_rollup(&sources);
    let available = sources.iter().any(|source| source.available);

    // Σ = AGENT-TOKEN savings: tokens kept OUT of the model context = effective
    // Command Optimizer filtering (reduced runs only) + Memory recall reuse.
    // Memory STORAGE compression is excluded — it is internal (not model tokens)
    // and its volume would otherwise bury the real number — and terse mode is
    // unmeasured. This mirrors the status line's `compute_statusline_savings`.
    let (cmd_effective_saved, cmd_effective_input) =
        command_effective_reduction(&proxy_path, project, window);
    let recall_reuse = read_recall_savings(project);
    let agent_token_saved_chars = cmd_effective_saved.saturating_add(recall_reuse);
    let agent_token_base_chars = cmd_effective_input.saturating_add(recall_reuse);
    let agent_token_saved_tokens = estimate_saved_tokens(agent_token_saved_chars);
    let agent_token_saved_pct = saved_pct(agent_token_saved_chars, agent_token_base_chars);

    Json(serde_json::json!({
        "available": available,
        "scope": project.unwrap_or("all"),
        "window": window.label,
        "total_saved_chars": total_saved_chars,
        "total_saved_tokens": total_saved_tokens,
        "total_original_chars": total_original_chars,
        "total_with_rtrt_chars": total_with_rtrt_chars,
        "total_saved_pct": saved_pct(total_saved_chars, total_original_chars),
        "agent_token_saved_chars": agent_token_saved_chars,
        "agent_token_saved_tokens": agent_token_saved_tokens,
        "agent_token_saved_pct": agent_token_saved_pct,
        "token_estimate": "chars/4",
        "sources": sources,
        "projects": projects,
        "note": notes.join(" "),
    }))
}
