//! (generated by module split — pure refactor, behavior identical)
#![allow(unused_imports)]

use std::collections::BTreeMap;
use std::path::PathBuf;
use std::process::Stdio;
use std::sync::Arc;

use anyhow::Result;
use axum::{
    Json, Router,
    extract::{Path as AxPath, State},
    http::StatusCode,
    response::{Html, IntoResponse},
    routing::{delete, get, post},
};
use rtrt_core::{
    OutputStyleLevel, read_output_style_level, read_output_style_level_for,
    write_output_style_level_for,
};
use rtrt_memory::{
    ClusterIndex, ConceptHierarchy, DetailedRecord, Embedder, MemoryStore, PayloadFilter,
    Summariser,
};
use rtrt_providers::{
    ChatMessage, ChatRequest, ChatResponse, Gateway, MetricsView, Prefer, Provider, RequestMetric,
    Role, RouteAlternative, RouteRequest, UsageSnapshot, select_route,
};
use rtrt_security::{Profile, ScanReport};
use rtrt_templates::{Prompt, PromptRegistry};
use serde::{Deserialize, Serialize};
use tokio::io::AsyncWriteExt;
use tokio::sync::Mutex;
use tokio::sync::broadcast;

use crate::prelude::*;

#[derive(Debug, Deserialize)]
pub(crate) struct SetLevelRequest {
    level: String,
}

/// Optional `?project=<name>` selector shared by the project-aware endpoints.
/// An absent value, the empty string, or the literal `"global"` all resolve to
/// the global scope (back-compat with existing UI calls).
#[derive(Debug, Deserialize, Default)]
pub(crate) struct ProjectQuery {
    #[serde(default)]
    pub(crate) project: Option<String>,
    /// Optional scope hint for project-aware writes. The statusline POST honours
    /// `scope=global` (a.k.a. "Follow global") to CLEAR a project's own override
    /// so it inherits the global config again. Absent/`custom` writes the
    /// per-project override as before. Other endpoints ignore this field.
    #[serde(default)]
    pub(crate) scope: Option<String>,
}

/// Resolve a `?project=` selector to an on-disk repo path.
///
/// Returns `Some(path)` only when the named project exists in the global config
/// and carries an absolute `.path` (a real, on-disk repo). `None` (the global
/// scope) is returned for the `"global"`/empty sentinel, an unknown project, or
/// a memory-only project with no path.
pub(crate) fn resolve_project_repo(project: Option<&str>) -> Option<PathBuf> {
    let name = project.map(str::trim).filter(|n| !n.is_empty())?;
    if name.eq_ignore_ascii_case("global") {
        return None;
    }
    let cfg = rtrt_core::Config::load().ok()?;
    let path = cfg.project(name)?.path.as_deref()?;
    if path.is_empty() {
        return None;
    }
    Some(PathBuf::from(path))
}

/// Resolve a `?project=` selector to a registered project NAME (not a repo
/// path). The per-project `embeddings_enabled` / `security_profile` overrides
/// live on the `ProjectEntry` in the GLOBAL config keyed by name, so these two
/// endpoints need the name — unlike the `.rtrt/config.toml`-backed settings
/// that go through `resolve_project_repo`. Returns `None` for the
/// `global`/empty sentinel.
pub(crate) fn resolve_project_name(project: Option<&str>) -> Option<String> {
    let name = project.map(str::trim).filter(|n| !n.is_empty())?;
    if name.eq_ignore_ascii_case("global") {
        return None;
    }
    Some(name.to_string())
}

/// Load the global config, run `mutate` on the named project's entry (creating
/// it if absent, preserving its other fields), then persist. Shared by the
/// embeddings + security_profile per-project writers. The error is boxed so the
/// `Err` variant stays small (clippy `result_large_err`).
fn upsert_project_field(
    name: &str,
    mutate: impl FnOnce(&mut rtrt_core::ProjectEntry),
) -> std::result::Result<(), Box<axum::response::Response>> {
    let mut cfg = rtrt_core::Config::load().map_err(|e| Box::new(clear_field_error(e)))?;
    let mut entry = cfg
        .project(name)
        .cloned()
        .unwrap_or(rtrt_core::ProjectEntry {
            name: name.to_string(),
            path: None,
            security_profile: None,
            embeddings_enabled: None,
        });
    mutate(&mut entry);
    cfg.upsert_project(entry);
    if let Err((status, msg)) = write_config_file(&cfg) {
        return Err(Box::new(
            (status, Json(serde_json::json!({ "error": msg }))).into_response(),
        ));
    }
    Ok(())
}

pub(crate) async fn get_optimizer_level(
    axum::extract::Query(q): axum::extract::Query<ProjectQuery>,
) -> impl IntoResponse {
    let repo = resolve_project_repo(q.project.as_deref());
    let level = read_output_style_level_for(repo.as_deref());
    // `custom` is true when THIS project carries its own `output_level` override
    // in `<repo>/.rtrt/config.toml`; otherwise it inherits the global level.
    // `scope`/`custom`/`inherited` mirror the statusline endpoint so the UI's
    // "Follow global / Custom (this project)" helper can be shared between them.
    let custom = match &repo {
        Some(path) => rtrt_core::Config::load_project(path)
            .map(|p| p.output_level.is_some())
            .unwrap_or(false),
        None => false,
    };
    let scope = if custom { "custom" } else { "global" };
    Json(serde_json::json!({
        "level": level.as_str(),
        "active": level.is_active(),
        "scope": scope,
        "custom": custom,
        // `inherited` is the inverse of `custom` for a project scope; always
        // false for the global scope (there is nothing to inherit from).
        "inherited": repo.is_some() && !custom,
    }))
}

pub(crate) async fn post_optimizer_level(
    axum::extract::Query(q): axum::extract::Query<ProjectQuery>,
    // Optional: the "Follow global" clear path (`?scope=global`) carries no body,
    // so a missing/empty JSON payload must be tolerated. A level write supplies it.
    body: Option<Json<SetLevelRequest>>,
) -> impl IntoResponse {
    let repo = resolve_project_repo(q.project.as_deref());

    // "Follow global" action: `?scope=global` CLEARS this project's
    // `output_level` override so it inherits the global level again. Only
    // meaningful for a resolved project; ignored for the global scope.
    let follow_global = q
        .scope
        .as_deref()
        .is_some_and(|s| s.eq_ignore_ascii_case("global"));
    if follow_global {
        if let Some(path) = repo.as_deref() {
            // Clear only the output_level field; load → set None → save_project.
            // `save_project` re-serializes the whole ProjectConfig, so a
            // coexisting `[statusline]` override is preserved (and the file is
            // removed only when the ProjectConfig becomes entirely empty).
            let mut project = match rtrt_core::Config::load_project(path) {
                Ok(p) => p,
                Err(e) => {
                    return (
                        StatusCode::INTERNAL_SERVER_ERROR,
                        Json(serde_json::json!({ "error": e.to_string() })),
                    )
                        .into_response();
                }
            };
            project.output_level = None;
            if let Err(e) = rtrt_core::Config::save_project(path, &project) {
                return (
                    StatusCode::INTERNAL_SERVER_ERROR,
                    Json(serde_json::json!({ "error": e.to_string() })),
                )
                    .into_response();
            }
            let level = read_output_style_level_for(repo.as_deref());
            return Json(serde_json::json!({
                "level": level.as_str(),
                "active": level.is_active(),
                "scope": "global",
                "custom": false,
                "inherited": true,
            }))
            .into_response();
        }
        // No project to clear in the global scope — fall through to a normal
        // write below, which keeps the existing global-level behaviour.
    }

    let Some(Json(body)) = body else {
        return (
            StatusCode::BAD_REQUEST,
            Json(serde_json::json!({ "error": "missing level" })),
        )
            .into_response();
    };
    let Some(level) = OutputStyleLevel::parse(&body.level) else {
        return (
            StatusCode::BAD_REQUEST,
            Json(serde_json::json!({ "error": "unknown level" })),
        )
            .into_response();
    };
    if let Err(e) = write_output_style_level_for(repo.as_deref(), level) {
        return (
            StatusCode::INTERNAL_SERVER_ERROR,
            Json(serde_json::json!({ "error": e.to_string() })),
        )
            .into_response();
    }
    // A project write persists the project's own override (Custom scope);
    // the global write edits the global level (no inheritance).
    let custom = repo.is_some();
    Json(serde_json::json!({
        "level": level.as_str(),
        "active": level.is_active(),
        "scope": if custom { "custom" } else { "global" },
        "custom": custom,
        "inherited": false,
    }))
    .into_response()
}

// ---------------------------------------------------------------------------
// GET/POST /api/compression/config
//
// The `rtrt compress` default compression level (off | lite | full | ultra |
// extreme) + enabled flag, distinct from the terse Output-Optimizer level.
// `off` is represented by `enabled = false`; the underlying [compression]
// section keeps `level` so a re-enable restores the chosen level. Project-aware
// and mirrors the optimizer-level scope contract exactly.
// ---------------------------------------------------------------------------

/// Map a `CompressionConfig` to the UI's level string. `off` is the
/// "disabled" pseudo-level so the four-button UX matches the optimizer level.
pub(crate) fn compression_level_label(c: &rtrt_core::config::CompressionConfig) -> &'static str {
    if !c.enabled {
        return "off";
    }
    match c.level {
        rtrt_core::CompressionLevel::Lite => "lite",
        rtrt_core::CompressionLevel::Full => "full",
        rtrt_core::CompressionLevel::Ultra => "ultra",
        rtrt_core::CompressionLevel::Extreme => "extreme",
    }
}

/// Parse a UI level string into a `CompressionConfig`. `off` disables
/// compression while keeping a sensible default level for a later re-enable.
pub(crate) fn parse_compression_level(value: &str) -> Option<rtrt_core::config::CompressionConfig> {
    let (enabled, level) = match value.trim().to_ascii_lowercase().as_str() {
        "off" => (false, rtrt_core::CompressionLevel::default()),
        "lite" => (true, rtrt_core::CompressionLevel::Lite),
        "full" => (true, rtrt_core::CompressionLevel::Full),
        "ultra" => (true, rtrt_core::CompressionLevel::Ultra),
        "extreme" => (true, rtrt_core::CompressionLevel::Extreme),
        _ => return None,
    };
    Some(rtrt_core::config::CompressionConfig { level, enabled })
}

#[derive(Debug, Deserialize)]
pub(crate) struct SetCompressionRequest {
    level: String,
}

pub(crate) async fn get_compression_config(
    axum::extract::Query(q): axum::extract::Query<ProjectQuery>,
) -> impl IntoResponse {
    let repo = resolve_project_repo(q.project.as_deref());
    // `custom` is true when THIS project carries its own `compression` override.
    let custom = match &repo {
        Some(path) => rtrt_core::Config::load_project(path)
            .map(|p| p.compression.is_some())
            .unwrap_or(false),
        None => false,
    };
    // Effective compression: global, overlaid with the project override when set.
    let cfg = rtrt_core::Config::load_effective(repo.as_deref()).unwrap_or_default();
    let label = compression_level_label(&cfg.compression);
    Json(serde_json::json!({
        "level": label,
        "enabled": cfg.compression.enabled,
        "scope": if custom { "custom" } else { "global" },
        "custom": custom,
        "inherited": repo.is_some() && !custom,
    }))
}

pub(crate) async fn post_compression_config(
    axum::extract::Query(q): axum::extract::Query<ProjectQuery>,
    body: Option<Json<SetCompressionRequest>>,
) -> impl IntoResponse {
    let repo = resolve_project_repo(q.project.as_deref());
    let follow_global = q
        .scope
        .as_deref()
        .is_some_and(|s| s.eq_ignore_ascii_case("global"));

    // "Follow global" action: CLEAR this project's `compression` override only,
    // preserving any coexisting overrides (statusline / output_level / providers
    // / agents) in the same `<repo>/.rtrt/config.toml`.
    if follow_global {
        if let Some(path) = repo.as_deref() {
            let mut project = match rtrt_core::Config::load_project(path) {
                Ok(p) => p,
                Err(e) => return clear_field_error(e),
            };
            project.compression = None;
            if let Err(e) = rtrt_core::Config::save_project(path, &project) {
                return clear_field_error(e);
            }
            let cfg = rtrt_core::Config::load_effective(Some(path)).unwrap_or_default();
            return Json(serde_json::json!({
                "level": compression_level_label(&cfg.compression),
                "enabled": cfg.compression.enabled,
                "scope": "global",
                "custom": false,
                "inherited": true,
            }))
            .into_response();
        }
        // No project to clear — fall through to a normal (global) write.
    }

    let Some(Json(body)) = body else {
        return (
            StatusCode::BAD_REQUEST,
            Json(serde_json::json!({ "error": "missing level" })),
        )
            .into_response();
    };
    let Some(compression) = parse_compression_level(&body.level) else {
        return (
            StatusCode::BAD_REQUEST,
            Json(serde_json::json!({ "error": "unknown level" })),
        )
            .into_response();
    };

    if let Some(path) = repo.as_deref() {
        // Per-project override.
        let mut project = match rtrt_core::Config::load_project(path) {
            Ok(p) => p,
            Err(e) => return clear_field_error(e),
        };
        project.compression = Some(compression.clone());
        if let Err(e) = rtrt_core::Config::save_project(path, &project) {
            return clear_field_error(e);
        }
        return Json(serde_json::json!({
            "level": compression_level_label(&compression),
            "enabled": compression.enabled,
            "scope": "custom",
            "custom": true,
            "inherited": false,
        }))
        .into_response();
    }

    // Global write.
    let mut cfg = match rtrt_core::Config::load() {
        Ok(c) => c,
        Err(e) => return clear_field_error(e),
    };
    cfg.compression = compression.clone();
    if let Err((status, msg)) = write_config_file(&cfg) {
        return (status, Json(serde_json::json!({ "error": msg }))).into_response();
    }
    Json(serde_json::json!({
        "level": compression_level_label(&compression),
        "enabled": compression.enabled,
        "scope": "global",
        "custom": false,
        "inherited": false,
    }))
    .into_response()
}

/// Effective provider list (detected ProviderApi tools) with enabled state
/// resolved against the effective config (global ⊕ project override).
pub(crate) fn effective_provider_tools(
    repo: Option<&std::path::Path>,
) -> (Option<String>, Vec<serde_json::Value>) {
    let cfg = rtrt_core::Config::load_effective(repo).unwrap_or_default();
    let tools = rtrt_core::detect_tools();
    let providers: Vec<serde_json::Value> = tools
        .iter()
        .filter(|t| matches!(t.kind, rtrt_core::ToolKind::ProviderApi))
        .map(|t| {
            let enabled = cfg.providers.enabled_override(&t.name).unwrap_or(t.enabled);
            serde_json::json!({
                "name": t.name,
                "enabled": enabled,
                "installed": t.installed,
                "has_api_key": provider_api_key_present(t),
            })
        })
        .collect();
    (cfg.providers.active.clone(), providers)
}

#[derive(Debug, Deserialize)]
pub(crate) struct SetProvidersRequest {
    /// Active provider name; empty/absent leaves the active provider unset.
    #[serde(default)]
    active: Option<String>,
    /// Per-provider enable map to persist for the project override.
    #[serde(default)]
    enabled: std::collections::BTreeMap<String, bool>,
}

pub(crate) async fn get_providers_config(
    axum::extract::Query(q): axum::extract::Query<ProjectQuery>,
) -> impl IntoResponse {
    let repo = resolve_project_repo(q.project.as_deref());
    let custom = match &repo {
        Some(path) => rtrt_core::Config::load_project(path)
            .map(|p| p.providers.is_some())
            .unwrap_or(false),
        None => false,
    };
    let (active, providers) = effective_provider_tools(repo.as_deref());
    Json(serde_json::json!({
        "active": active,
        "providers": providers,
        "scope": if custom { "custom" } else { "global" },
        "custom": custom,
        "inherited": repo.is_some() && !custom,
    }))
}

pub(crate) async fn post_providers_config(
    axum::extract::Query(q): axum::extract::Query<ProjectQuery>,
    body: Option<Json<SetProvidersRequest>>,
) -> impl IntoResponse {
    let repo = resolve_project_repo(q.project.as_deref());
    let follow_global = q
        .scope
        .as_deref()
        .is_some_and(|s| s.eq_ignore_ascii_case("global"));

    if follow_global {
        if let Some(path) = repo.as_deref() {
            let mut project = match rtrt_core::Config::load_project(path) {
                Ok(p) => p,
                Err(e) => return clear_field_error(e),
            };
            project.providers = None;
            if let Err(e) = rtrt_core::Config::save_project(path, &project) {
                return clear_field_error(e);
            }
            let (active, providers) = effective_provider_tools(Some(path));
            return Json(serde_json::json!({
                "active": active,
                "providers": providers,
                "scope": "global",
                "custom": false,
                "inherited": true,
            }))
            .into_response();
        }
    }

    let Some(Json(body)) = body else {
        return (
            StatusCode::BAD_REQUEST,
            Json(serde_json::json!({ "error": "missing body" })),
        )
            .into_response();
    };
    let active = body
        .active
        .as_deref()
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(str::to_string);
    let providers_cfg = rtrt_core::config::ProvidersConfig {
        active,
        enabled: body.enabled.clone(),
    };

    if let Some(path) = repo.as_deref() {
        let mut project = match rtrt_core::Config::load_project(path) {
            Ok(p) => p,
            Err(e) => return clear_field_error(e),
        };
        project.providers = Some(providers_cfg);
        if let Err(e) = rtrt_core::Config::save_project(path, &project) {
            return clear_field_error(e);
        }
        let (active, providers) = effective_provider_tools(Some(path));
        return Json(serde_json::json!({
            "active": active,
            "providers": providers,
            "scope": "custom",
            "custom": true,
            "inherited": false,
        }))
        .into_response();
    }

    // Global write.
    let mut cfg = match rtrt_core::Config::load() {
        Ok(c) => c,
        Err(e) => return clear_field_error(e),
    };
    cfg.providers = providers_cfg;
    if let Err((status, msg)) = write_config_file(&cfg) {
        return (status, Json(serde_json::json!({ "error": msg }))).into_response();
    }
    let (active, providers) = effective_provider_tools(None);
    Json(serde_json::json!({
        "active": active,
        "providers": providers,
        "scope": "global",
        "custom": false,
        "inherited": false,
    }))
    .into_response()
}

// ---------------------------------------------------------------------------
// GET/POST /api/agents/config
//
// Per-project agent enable/disable overlay (`ProjectConfig.agents`). "Agents"
// here are the detected coding-agent / local-runtime / MCP-server tools (every
// detected tool that is NOT a provider API). GET reports each agent's effective
// enabled state; POST writes the project override; `?scope=global` clears it.
// ---------------------------------------------------------------------------

pub(crate) fn agent_kind_label(kind: rtrt_core::ToolKind) -> &'static str {
    match kind {
        rtrt_core::ToolKind::CodingAgent => "agent",
        rtrt_core::ToolKind::LocalRuntime => "runtime",
        rtrt_core::ToolKind::McpServer => "mcp",
        rtrt_core::ToolKind::ProviderApi => "provider",
    }
}

/// Effective agent list (detected non-provider tools) with enabled state
/// resolved against the effective config (global ⊕ project override).
pub(crate) fn effective_agent_tools(repo: Option<&std::path::Path>) -> Vec<serde_json::Value> {
    let cfg = rtrt_core::Config::load_effective(repo).unwrap_or_default();
    rtrt_core::detect_tools()
        .iter()
        .filter(|t| !matches!(t.kind, rtrt_core::ToolKind::ProviderApi))
        .map(|t| {
            let enabled = cfg.agents.enabled_override(&t.name).unwrap_or(t.enabled);
            serde_json::json!({
                "name": t.name,
                "enabled": enabled,
                "installed": t.installed,
                "kind": agent_kind_label(t.kind),
            })
        })
        .collect()
}

#[derive(Debug, Deserialize)]
pub(crate) struct SetAgentsRequest {
    /// Per-agent enable map to persist for the project override.
    #[serde(default)]
    enabled: std::collections::BTreeMap<String, bool>,
}

pub(crate) async fn get_agents_config(
    axum::extract::Query(q): axum::extract::Query<ProjectQuery>,
) -> impl IntoResponse {
    let repo = resolve_project_repo(q.project.as_deref());
    let custom = match &repo {
        Some(path) => rtrt_core::Config::load_project(path)
            .map(|p| p.agents.is_some())
            .unwrap_or(false),
        None => false,
    };
    let agents = effective_agent_tools(repo.as_deref());
    Json(serde_json::json!({
        "agents": agents,
        "scope": if custom { "custom" } else { "global" },
        "custom": custom,
        "inherited": repo.is_some() && !custom,
    }))
}

pub(crate) async fn post_agents_config(
    axum::extract::Query(q): axum::extract::Query<ProjectQuery>,
    body: Option<Json<SetAgentsRequest>>,
) -> impl IntoResponse {
    let repo = resolve_project_repo(q.project.as_deref());
    let follow_global = q
        .scope
        .as_deref()
        .is_some_and(|s| s.eq_ignore_ascii_case("global"));

    if follow_global {
        if let Some(path) = repo.as_deref() {
            let mut project = match rtrt_core::Config::load_project(path) {
                Ok(p) => p,
                Err(e) => return clear_field_error(e),
            };
            project.agents = None;
            if let Err(e) = rtrt_core::Config::save_project(path, &project) {
                return clear_field_error(e);
            }
            return Json(serde_json::json!({
                "agents": effective_agent_tools(Some(path)),
                "scope": "global",
                "custom": false,
                "inherited": true,
            }))
            .into_response();
        }
    }

    let Some(Json(body)) = body else {
        return (
            StatusCode::BAD_REQUEST,
            Json(serde_json::json!({ "error": "missing body" })),
        )
            .into_response();
    };
    let agents_cfg = rtrt_core::config::AgentsConfig {
        enabled: body.enabled.clone(),
    };

    if let Some(path) = repo.as_deref() {
        let mut project = match rtrt_core::Config::load_project(path) {
            Ok(p) => p,
            Err(e) => return clear_field_error(e),
        };
        project.agents = Some(agents_cfg);
        if let Err(e) = rtrt_core::Config::save_project(path, &project) {
            return clear_field_error(e);
        }
        return Json(serde_json::json!({
            "agents": effective_agent_tools(Some(path)),
            "scope": "custom",
            "custom": true,
            "inherited": false,
        }))
        .into_response();
    }

    // Global write.
    let mut cfg = match rtrt_core::Config::load() {
        Ok(c) => c,
        Err(e) => return clear_field_error(e),
    };
    cfg.agents = agents_cfg;
    if let Err((status, msg)) = write_config_file(&cfg) {
        return (status, Json(serde_json::json!({ "error": msg }))).into_response();
    }
    Json(serde_json::json!({
        "agents": effective_agent_tools(None),
        "scope": "global",
        "custom": false,
        "inherited": false,
    }))
    .into_response()
}

// ---------------------------------------------------------------------------
// GET/POST /api/embeddings/project
//
// Per-project `embeddings_enabled` override on `ProjectEntry` (force semantic
// memory on/off for one project). `None` = Follow global (`[embeddings] enabled`).
// `?scope=global` clears the override back to None. Mirrors the shared
// "Follow global / Custom (this project)" scope contract used by the five
// `.rtrt/config.toml`-backed settings — but the value lives on the global
// config's `[[projects]]` entry, keyed by name.
// ---------------------------------------------------------------------------

/// Effective embeddings-enabled for a project: the per-project override when
/// set, else the global `[embeddings] enabled`.
fn effective_embeddings_enabled(over: Option<bool>) -> bool {
    match over {
        Some(v) => v,
        None => rtrt_core::Config::load()
            .map(|c| c.embeddings.enabled)
            .unwrap_or(false),
    }
}

fn embeddings_project_json(name_present: bool, over: Option<bool>) -> serde_json::Value {
    // `custom` is true only for a real project that pins its own override.
    let custom = name_present && over.is_some();
    serde_json::json!({
        "enabled": effective_embeddings_enabled(over),
        "override": over,
        "global_enabled": rtrt_core::Config::load().map(|c| c.embeddings.enabled).unwrap_or(false),
        "scope": if custom { "custom" } else { "global" },
        "custom": custom,
        "inherited": name_present && !custom,
    })
}

pub(crate) async fn get_embeddings_project(
    axum::extract::Query(q): axum::extract::Query<ProjectQuery>,
) -> impl IntoResponse {
    let name = resolve_project_name(q.project.as_deref());
    let over = match &name {
        Some(n) => rtrt_core::Config::load()
            .ok()
            .and_then(|c| c.project(n).and_then(|p| p.embeddings_enabled)),
        None => None,
    };
    Json(embeddings_project_json(name.is_some(), over))
}

#[derive(Debug, Deserialize)]
pub(crate) struct SetEmbeddingsProjectRequest {
    /// `Some(true)`/`Some(false)` forces semantic memory on/off; absent leaves
    /// the existing override (only the `?scope=global` clear path removes it).
    #[serde(default)]
    enabled: Option<bool>,
}

pub(crate) async fn post_embeddings_project(
    axum::extract::Query(q): axum::extract::Query<ProjectQuery>,
    body: Option<Json<SetEmbeddingsProjectRequest>>,
) -> impl IntoResponse {
    let name = resolve_project_name(q.project.as_deref());
    let follow_global = q
        .scope
        .as_deref()
        .is_some_and(|s| s.eq_ignore_ascii_case("global"));

    let Some(name) = name else {
        // No project selected — embeddings_enabled is a per-project field with
        // no global write target (the global toggle lives in [embeddings]).
        return (
            StatusCode::BAD_REQUEST,
            Json(serde_json::json!({ "error": "select a project to set the per-project embeddings override" })),
        )
            .into_response();
    };

    // "Follow global": clear the per-project override back to None.
    if follow_global {
        if let Err(resp) = upsert_project_field(&name, |e| e.embeddings_enabled = None) {
            return *resp;
        }
        return Json(embeddings_project_json(true, None)).into_response();
    }

    let Some(Json(body)) = body else {
        return (
            StatusCode::BAD_REQUEST,
            Json(serde_json::json!({ "error": "missing enabled" })),
        )
            .into_response();
    };
    let Some(enabled) = body.enabled else {
        return (
            StatusCode::BAD_REQUEST,
            Json(serde_json::json!({ "error": "missing enabled" })),
        )
            .into_response();
    };
    if let Err(resp) = upsert_project_field(&name, |e| e.embeddings_enabled = Some(enabled)) {
        return *resp;
    }
    Json(embeddings_project_json(true, Some(enabled))).into_response()
}

// ---------------------------------------------------------------------------
// GET/POST /api/security/project
//
// Per-project `security_profile` override on `ProjectEntry` (bound profile name,
// else the global `[security] default_profile`). `None` = Follow global.
// `?scope=global` clears it. Same scope contract as the embeddings endpoint.
// ---------------------------------------------------------------------------

fn global_default_profile() -> String {
    rtrt_core::Config::load()
        .map(|c| c.security.default_profile)
        .unwrap_or_else(|_| "ai-default".to_string())
}

fn security_project_json(name_present: bool, over: Option<&str>) -> serde_json::Value {
    let custom = name_present && over.is_some();
    let default_profile = global_default_profile();
    let effective = over
        .map(str::to_string)
        .unwrap_or_else(|| default_profile.clone());
    serde_json::json!({
        "profile": effective,
        "override": over,
        "default_profile": default_profile,
        "scope": if custom { "custom" } else { "global" },
        "custom": custom,
        "inherited": name_present && !custom,
    })
}

pub(crate) async fn get_security_project(
    axum::extract::Query(q): axum::extract::Query<ProjectQuery>,
) -> impl IntoResponse {
    let name = resolve_project_name(q.project.as_deref());
    let over = match &name {
        Some(n) => rtrt_core::Config::load()
            .ok()
            .and_then(|c| c.project(n).and_then(|p| p.security_profile.clone())),
        None => None,
    };
    Json(security_project_json(name.is_some(), over.as_deref()))
}

#[derive(Debug, Deserialize)]
pub(crate) struct SetSecurityProjectRequest {
    /// Bound profile name; absent/empty with no `?scope=global` is rejected.
    #[serde(default)]
    profile: Option<String>,
}

pub(crate) async fn post_security_project(
    axum::extract::Query(q): axum::extract::Query<ProjectQuery>,
    body: Option<Json<SetSecurityProjectRequest>>,
) -> impl IntoResponse {
    let name = resolve_project_name(q.project.as_deref());
    let follow_global = q
        .scope
        .as_deref()
        .is_some_and(|s| s.eq_ignore_ascii_case("global"));

    let Some(name) = name else {
        return (
            StatusCode::BAD_REQUEST,
            Json(serde_json::json!({ "error": "select a project to bind a security profile" })),
        )
            .into_response();
    };

    if follow_global {
        if let Err(resp) = upsert_project_field(&name, |e| e.security_profile = None) {
            return *resp;
        }
        return Json(security_project_json(true, None)).into_response();
    }

    let profile = body
        .and_then(|Json(b)| b.profile)
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty());
    let Some(profile) = profile else {
        return (
            StatusCode::BAD_REQUEST,
            Json(serde_json::json!({ "error": "missing profile" })),
        )
            .into_response();
    };
    let stored = profile.clone();
    if let Err(resp) = upsert_project_field(&name, |e| e.security_profile = Some(stored)) {
        return *resp;
    }
    Json(security_project_json(true, Some(&profile))).into_response()
}
