//! (generated by module split — pure refactor, behavior identical)
#![allow(unused_imports)]

use std::collections::BTreeMap;
use std::path::PathBuf;
use std::process::Stdio;
use std::sync::Arc;

use anyhow::Result;
use axum::{
    Json, Router,
    extract::{Path as AxPath, State},
    http::StatusCode,
    response::{Html, IntoResponse},
    routing::{delete, get, post},
};
use rtrt_core::{
    OutputStyleLevel, read_output_style_level, read_output_style_level_for,
    write_output_style_level_for,
};
use rtrt_memory::{
    ClusterIndex, ConceptHierarchy, DetailedRecord, Embedder, MemoryStore, PayloadFilter,
    Summariser,
};
use rtrt_providers::{
    ChatMessage, ChatRequest, ChatResponse, Gateway, MetricsView, Prefer, Provider, RequestMetric,
    Role, RouteAlternative, RouteRequest, UsageSnapshot, select_route,
};
use rtrt_security::{Profile, ScanReport};
use rtrt_templates::{Prompt, PromptRegistry};
use serde::{Deserialize, Serialize};
use tokio::io::AsyncWriteExt;
use tokio::sync::Mutex;
use tokio::sync::broadcast;

use crate::prelude::*;

pub(crate) async fn security_profiles() -> Json<Vec<String>> {
    Json(rtrt_security::list_profiles())
}

pub(crate) async fn security_profile(
    AxPath(name): AxPath<String>,
) -> std::result::Result<Json<Profile>, (StatusCode, String)> {
    rtrt_security::load_profile(&name)
        .map(Json)
        .map_err(|e| (StatusCode::NOT_FOUND, e.to_string()))
}

#[derive(Debug, Deserialize)]
pub(crate) struct SecurityScanRequest {
    profile: String,
    #[serde(default)]
    path: Option<String>,
}

pub(crate) async fn security_scan(
    Json(req): Json<SecurityScanRequest>,
) -> std::result::Result<Json<ScanReport>, (StatusCode, String)> {
    let profile = rtrt_security::load_profile(&req.profile)
        .map_err(|e| (StatusCode::BAD_REQUEST, e.to_string()))?;
    let path = req.path.unwrap_or_else(|| ".".to_string());
    rtrt_security::run(&profile, std::path::Path::new(&path))
        .map(Json)
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))
}

#[derive(Debug, Deserialize)]
pub(crate) struct ProfileSaveReq {
    name: String,
    toml: String,
}

/// `POST /api/security/profile` — validate and persist a profile to the user
/// profile directory. Powers profile clone/edit-save in the UI.
pub(crate) async fn security_profile_save(
    Json(req): Json<ProfileSaveReq>,
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    // Validate the TOML by parsing it into a Profile first.
    Profile::from_toml(&req.toml).map_err(|e| (StatusCode::BAD_REQUEST, e.to_string()))?;

    let dir = rtrt_security::user_profile_dir().ok_or((
        StatusCode::INTERNAL_SERVER_ERROR,
        "cannot determine profile directory".to_string(),
    ))?;
    std::fs::create_dir_all(&dir).map_err(|e| {
        (
            StatusCode::INTERNAL_SERVER_ERROR,
            format!("create dir {}: {e}", dir.display()),
        )
    })?;
    let path = dir.join(format!("{}.toml", req.name));
    std::fs::write(&path, &req.toml).map_err(|e| {
        (
            StatusCode::INTERNAL_SERVER_ERROR,
            format!("write {}: {e}", path.display()),
        )
    })?;
    Ok(Json(serde_json::json!({ "ok": true })))
}
