//! (generated by module split — pure refactor, behavior identical)
#![allow(unused_imports)]

use std::collections::BTreeMap;
use std::path::PathBuf;
use std::process::Stdio;
use std::sync::Arc;

use anyhow::Result;
use axum::{
    Json, Router,
    extract::{Path as AxPath, State},
    http::StatusCode,
    response::{Html, IntoResponse},
    routing::{delete, get, post},
};
use rtrt_core::{
    OutputStyleLevel, read_output_style_level, read_output_style_level_for,
    write_output_style_level_for,
};
use rtrt_memory::{
    ClusterIndex, ConceptHierarchy, DetailedRecord, Embedder, MemoryStore, PayloadFilter,
    Summariser,
};
use rtrt_providers::{
    ChatMessage, ChatRequest, ChatResponse, Gateway, MetricsView, Prefer, Provider, RequestMetric,
    Role, RouteAlternative, RouteRequest, UsageSnapshot, select_route,
};
use rtrt_security::{Profile, ScanReport};
use rtrt_templates::{Prompt, PromptRegistry};
use serde::{Deserialize, Serialize};
use tokio::io::AsyncWriteExt;
use tokio::sync::Mutex;
use tokio::sync::broadcast;

use crate::prelude::*;

pub(crate) const STATUSLINE_SEGMENTS: &[&str] = &[
    "project", "branch", "wip", "sess", "ctx", "cache", "opt", "model", "usage", "agents",
    "savings",
];
pub(crate) const LEGACY_STATUSLINE_SEGMENTS: &[&str] = &[
    "project", "branch", "wip", "sess", "ctx", "cache", "model", "usage", "codex", "savings",
];
pub(crate) const STATUSLINE_DEFAULT_FORMAT: &str =
    "{project} [{branch}] {wip} {sess} {ctx} {cache} {opt} {model} {agents}";

pub(crate) const LEGACY_STATUSLINE_FORMAT: &str =
    "{project} [{branch}] {wip} {sess} {ctx} {cache} {model}";

pub(crate) const STATUSLINE_DEFAULT_LINE2_FORMAT: &str = "{usage}";

pub(crate) const STATUSLINE_DEFAULT_LINE3_FORMAT: &str = "{savings}";
pub(crate) const STATUSLINE_DEFAULT_CODEX_TIMEOUT_MS: u64 = 200;

#[derive(Debug, Deserialize, Serialize)]
pub(crate) struct StatuslineConfig {
    #[serde(default = "default_statusline_segments")]
    enabled_segments: Vec<String>,
    #[serde(default = "default_statusline_format")]
    format: String,
    #[serde(default = "default_statusline_line2_format")]
    line2_format: String,
    #[serde(default = "default_statusline_line3_format")]
    line3_format: String,
    #[serde(default = "default_statusline_codex_timeout_ms")]
    codex_check_timeout_ms: u64,
}

impl Default for StatuslineConfig {
    fn default() -> Self {
        Self {
            enabled_segments: default_statusline_segments(),
            format: default_statusline_format(),
            line2_format: default_statusline_line2_format(),
            line3_format: default_statusline_line3_format(),
            codex_check_timeout_ms: default_statusline_codex_timeout_ms(),
        }
    }
}

pub(crate) fn default_statusline_segments() -> Vec<String> {
    STATUSLINE_SEGMENTS
        .iter()
        .map(|segment| segment.to_string())
        .collect()
}

pub(crate) fn default_statusline_format() -> String {
    STATUSLINE_DEFAULT_FORMAT.to_string()
}

pub(crate) fn default_statusline_line2_format() -> String {
    STATUSLINE_DEFAULT_LINE2_FORMAT.to_string()
}

pub(crate) fn default_statusline_line3_format() -> String {
    STATUSLINE_DEFAULT_LINE3_FORMAT.to_string()
}

pub(crate) fn default_statusline_codex_timeout_ms() -> u64 {
    STATUSLINE_DEFAULT_CODEX_TIMEOUT_MS
}

#[derive(Debug, Serialize)]
pub(crate) struct StatuslineOk {
    ok: bool,
}

/// GET response wrapping the effective statusline config plus a scope marker so
/// the UI can render the "Follow global / Custom (this project)" toggle.
///
/// `#[serde(flatten)]` keeps the config fields at the top level (back-compat
/// with the existing UI reads) while adding:
/// - `scope`: `"custom"` when THIS project carries its own override, else
///   `"global"` (inherits the global config — the default).
/// - `custom`: the same as a boolean for convenience.
#[derive(Debug, Serialize)]
pub(crate) struct StatuslineConfigResponse {
    #[serde(flatten)]
    config: StatuslineConfig,
    scope: &'static str,
    custom: bool,
}

#[derive(Debug, Serialize)]
pub(crate) struct StatuslinePreview {
    lines: Vec<String>,
}

pub(crate) async fn get_statusline_config(
    axum::extract::Query(q): axum::extract::Query<ProjectQuery>,
) -> DashboardJsonResult<StatuslineConfigResponse> {
    // Per-project override wins: when the project carries its own `statusline`
    // value in `<repo>/.rtrt/config.toml`, return it ("Custom" scope); otherwise
    // fall through to the global statusline config ("Follow global" — inherit).
    if let Some(repo) = resolve_project_repo(q.project.as_deref()) {
        let project = rtrt_core::Config::load_project(&repo).map_err(|e| {
            api_error(
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("load project config {}: {e}", repo.display()),
            )
        })?;
        if let Some(statusline) = project.statusline {
            let cfg = statusline.try_into().map_err(|e| {
                api_error(
                    StatusCode::INTERNAL_SERVER_ERROR,
                    format!(
                        "parse [statusline] in {}/.rtrt/config.toml: {e}",
                        repo.display()
                    ),
                )
            })?;
            return Ok(Json(StatuslineConfigResponse {
                config: upgrade_legacy_statusline_config(cfg),
                scope: "custom",
                custom: true,
            }));
        }
        // no project override — inherit the global config below ("Follow global")
    }

    // Global scope, or a project that follows global: serve the effective
    // (global) config and report `global` scope.
    let config = read_global_statusline_config().await?;
    Ok(Json(StatuslineConfigResponse {
        config,
        scope: "global",
        custom: false,
    }))
}

/// Read and normalise the global statusline config from `~/.rtrt/config.toml`.
pub(crate) async fn read_global_statusline_config()
-> std::result::Result<StatuslineConfig, (StatusCode, Json<ApiError>)> {
    let path = statusline_config_path()?;
    match tokio::fs::read_to_string(&path).await {
        Ok(content) => {
            let root = parse_config_toml(&content, &path)?;
            let Some(statusline) = root.get("statusline") else {
                return Ok(StatuslineConfig::default());
            };
            let cfg = statusline.clone().try_into().map_err(|e| {
                api_error(
                    StatusCode::INTERNAL_SERVER_ERROR,
                    format!("parse [statusline] in {}: {e}", path.display()),
                )
            })?;
            Ok(upgrade_legacy_statusline_config(cfg))
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(StatuslineConfig::default()),
        Err(e) => Err(api_error(
            StatusCode::INTERNAL_SERVER_ERROR,
            format!("read {}: {e}", path.display()),
        )),
    }
}

pub(crate) fn upgrade_legacy_statusline_config(mut cfg: StatuslineConfig) -> StatuslineConfig {
    let legacy_segments = LEGACY_STATUSLINE_SEGMENTS
        .iter()
        .map(|segment| segment.to_string())
        .collect::<Vec<_>>();
    if cfg.enabled_segments == legacy_segments {
        cfg.enabled_segments = default_statusline_segments();
    }
    if cfg.format == LEGACY_STATUSLINE_FORMAT {
        cfg.format = default_statusline_format();
    }
    cfg
}

pub(crate) async fn post_statusline_config(
    axum::extract::Query(q): axum::extract::Query<ProjectQuery>,
    Json(req): Json<StatuslineConfig>,
) -> DashboardJsonResult<StatuslineOk> {
    // "Follow global" action: `?scope=global` CLEARS this project's statusline
    // override so it inherits the global config again. Only meaningful for a
    // resolved project; ignored for the global scope (there is nothing to clear).
    let follow_global = q
        .scope
        .as_deref()
        .is_some_and(|s| s.eq_ignore_ascii_case("global"));

    // Per-project override: persist the serialized statusline config into the
    // project's `<repo>/.rtrt/config.toml` (`ProjectConfig.statusline`) instead
    // of the global file.
    if let Some(repo) = resolve_project_repo(q.project.as_deref()) {
        let mut project = rtrt_core::Config::load_project(&repo).map_err(|e| {
            api_error(
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("load project config {}: {e}", repo.display()),
            )
        })?;
        if follow_global {
            // Clear the override. `save_project` removes the file when the
            // ProjectConfig becomes empty, so the project falls back to global.
            project.statusline = None;
            rtrt_core::Config::save_project(&repo, &project).map_err(|e| {
                api_error(
                    StatusCode::INTERNAL_SERVER_ERROR,
                    format!("write project config {}: {e}", repo.display()),
                )
            })?;
            return Ok(Json(StatuslineOk { ok: true }));
        }
        validate_statusline_segments(&req.enabled_segments)?;
        let statusline_value = toml::Value::try_from(&req).map_err(|e| {
            api_error(
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("serialize statusline config: {e}"),
            )
        })?;
        project.statusline = Some(statusline_value);
        rtrt_core::Config::save_project(&repo, &project).map_err(|e| {
            api_error(
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("write project config {}: {e}", repo.display()),
            )
        })?;
        return Ok(Json(StatuslineOk { ok: true }));
    }

    validate_statusline_segments(&req.enabled_segments)?;

    let path = statusline_config_path()?;
    let mut root = match tokio::fs::read_to_string(&path).await {
        Ok(content) => parse_config_toml(&content, &path)?,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            toml::Value::Table(toml::Table::new())
        }
        Err(e) => {
            return Err(api_error(
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("read {}: {e}", path.display()),
            ));
        }
    };
    if !root.is_table() {
        root = toml::Value::Table(toml::Table::new());
    }
    let root_table = root.as_table_mut().ok_or_else(|| {
        api_error(
            StatusCode::INTERNAL_SERVER_ERROR,
            "config root is not a TOML table",
        )
    })?;
    let statusline_value = toml::Value::try_from(req).map_err(|e| {
        api_error(
            StatusCode::INTERNAL_SERVER_ERROR,
            format!("serialize statusline config: {e}"),
        )
    })?;
    root_table.insert("statusline".to_string(), statusline_value);

    let output = toml::to_string_pretty(&root).map_err(|e| {
        api_error(
            StatusCode::INTERNAL_SERVER_ERROR,
            format!("serialize {}: {e}", path.display()),
        )
    })?;
    if let Some(parent) = path.parent() {
        tokio::fs::create_dir_all(parent).await.map_err(|e| {
            api_error(
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("create dir {}: {e}", parent.display()),
            )
        })?;
    }
    tokio::fs::write(&path, output).await.map_err(|e| {
        api_error(
            StatusCode::INTERNAL_SERVER_ERROR,
            format!("write {}: {e}", path.display()),
        )
    })?;

    Ok(Json(StatuslineOk { ok: true }))
}

pub(crate) async fn statusline_preview() -> Json<StatuslinePreview> {
    let fallback = || {
        Json(StatuslinePreview {
            lines: vec![
                "(rtrt binary not found or timed out — save config and ensure rtrt is installed)"
                    .to_string(),
            ],
        })
    };
    match run_statusline_preview("rtrt").await {
        Some(lines) => Json(StatuslinePreview { lines }),
        None => {
            let Some(home) = dirs::home_dir() else {
                return fallback();
            };
            let cargo_bin = home.join(".cargo").join("bin").join("rtrt");
            match run_statusline_preview(cargo_bin).await {
                Some(lines) => Json(StatuslinePreview { lines }),
                None => fallback(),
            }
        }
    }
}

pub(crate) fn statusline_config_path() -> std::result::Result<PathBuf, (StatusCode, Json<ApiError>)>
{
    rtrt_core::Config::default_path().ok_or_else(|| {
        api_error(
            StatusCode::INTERNAL_SERVER_ERROR,
            "cannot determine config path",
        )
    })
}

pub(crate) fn parse_config_toml(
    content: &str,
    path: &std::path::Path,
) -> std::result::Result<toml::Value, (StatusCode, Json<ApiError>)> {
    content.parse::<toml::Value>().map_err(|e| {
        api_error(
            StatusCode::INTERNAL_SERVER_ERROR,
            format!("parse {}: {e}", path.display()),
        )
    })
}

pub(crate) fn validate_statusline_segments(
    segments: &[String],
) -> std::result::Result<(), (StatusCode, Json<ApiError>)> {
    for segment in segments {
        if !STATUSLINE_SEGMENTS.contains(&segment.as_str()) {
            return Err(api_error(
                StatusCode::BAD_REQUEST,
                format!("unknown statusline segment: {segment}"),
            ));
        }
    }
    Ok(())
}

pub(crate) async fn run_statusline_preview<P>(binary: P) -> Option<Vec<String>>
where
    P: AsRef<std::ffi::OsStr>,
{
    let sample = serde_json::json!({
        "model": { "display_name": "Opus 4.8" },
        "cwd": "/home/kernalix7/Desktop/00_Personal_Project/00G_rtrt",
        "transcript": [],
    });
    let sample = serde_json::to_vec(&sample).ok()?;
    let mut command = tokio::process::Command::new(binary);
    command
        .arg("statusline")
        .arg("--rich")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .kill_on_drop(true);
    let mut child = command.spawn().ok()?;
    if let Some(mut stdin) = child.stdin.take() {
        if stdin.write_all(&sample).await.is_err() || stdin.shutdown().await.is_err() {
            return None;
        }
    }
    let output = tokio::time::timeout(std::time::Duration::from_secs(2), child.wait_with_output())
        .await
        .ok()?
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let stdout = String::from_utf8_lossy(&output.stdout);
    let lines = stdout
        .lines()
        .map(str::trim_end)
        .filter(|line| !line.trim().is_empty())
        .map(ToOwned::to_owned)
        .take(3)
        .collect::<Vec<_>>();
    Some(lines)
}

// ---------------------------------------------------------------------------
// Environment / orchestration detection
// ---------------------------------------------------------------------------
