//! (generated by module split — pure refactor, behavior identical)
#![allow(unused_imports)]

use std::collections::BTreeMap;
use std::path::PathBuf;
use std::process::Stdio;
use std::sync::Arc;

use anyhow::Result;
use axum::{
    Json, Router,
    extract::{Path as AxPath, State},
    http::StatusCode,
    response::{Html, IntoResponse},
    routing::{delete, get, post},
};
use rtrt_core::{
    OutputStyleLevel, read_output_style_level, read_output_style_level_for,
    write_output_style_level_for,
};
use rtrt_memory::{
    ClusterIndex, ConceptHierarchy, DetailedRecord, Embedder, MemoryStore, PayloadFilter,
    Summariser,
};
use rtrt_providers::{
    ChatMessage, ChatRequest, ChatResponse, Gateway, MetricsView, Prefer, Provider, RequestMetric,
    Role, RouteAlternative, RouteRequest, UsageSnapshot, select_route,
};
use rtrt_security::{Profile, ScanReport};
use rtrt_templates::{Prompt, PromptRegistry};
use serde::{Deserialize, Serialize};
use tokio::io::AsyncWriteExt;
use tokio::sync::Mutex;
use tokio::sync::broadcast;

use crate::prelude::*;

pub(crate) async fn list_templates() -> Json<Vec<TemplateSummary>> {
    Json(
        rtrt_templates::list_all()
            .into_iter()
            .map(TemplateSummary::from)
            .collect(),
    )
}

pub(crate) async fn get_template(
    AxPath(name): AxPath<String>,
) -> std::result::Result<Json<rtrt_templates::Template>, (StatusCode, String)> {
    rtrt_templates::find(&name)
        .map(Json)
        .ok_or((StatusCode::NOT_FOUND, format!("template not found: {name}")))
}

pub(crate) async fn create_template(
    Json(req): Json<TemplateUpsertRequest>,
) -> std::result::Result<(StatusCode, Json<serde_json::Value>), (StatusCode, String)> {
    validate_template_name(&req.name)?;
    if is_builtin_template(&req.name) {
        return Err((
            StatusCode::BAD_REQUEST,
            format!("built-in template is read-only: {}", req.name),
        ));
    }
    let template = req.try_into_template()?;
    let path =
        rtrt_templates::custom::save_custom(&template).map_err(template_write_error_status)?;
    Ok((
        StatusCode::CREATED,
        Json(serde_json::json!({ "ok": true, "name": template.name, "path": path })),
    ))
}

pub(crate) async fn update_template(
    AxPath(name): AxPath<String>,
    Json(req): Json<TemplateUpsertRequest>,
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    validate_template_name(&name)?;
    validate_template_name(&req.name)?;
    if req.name != name {
        return Err((
            StatusCode::BAD_REQUEST,
            "template body name must match route name".to_string(),
        ));
    }
    if is_builtin_template(&name) {
        return Err((
            StatusCode::FORBIDDEN,
            format!("built-in template is read-only: {name}"),
        ));
    }
    let template = req.try_into_template()?;
    let path =
        rtrt_templates::custom::save_custom(&template).map_err(template_write_error_status)?;
    Ok(Json(
        serde_json::json!({ "ok": true, "name": template.name, "path": path }),
    ))
}

pub(crate) async fn delete_template(
    AxPath(name): AxPath<String>,
) -> std::result::Result<Json<serde_json::Value>, (StatusCode, String)> {
    validate_template_name(&name)?;
    if is_builtin_template(&name) {
        return Err((
            StatusCode::FORBIDDEN,
            format!("built-in template is read-only: {name}"),
        ));
    }
    if !rtrt_templates::custom::is_custom(&name) {
        return Err((StatusCode::NOT_FOUND, format!("template not found: {name}")));
    }
    rtrt_templates::custom::delete_custom(&name).map_err(template_write_error_status)?;
    Ok(Json(serde_json::json!({ "ok": true, "name": name })))
}

#[derive(Debug, Clone, Serialize)]
pub(crate) struct TemplateSummary {
    name: String,
    description: String,
    source: rtrt_templates::TemplateSource,
    category: rtrt_templates::TemplateCategory,
    variables: Vec<rtrt_templates::TemplateVariable>,
}

impl From<rtrt_templates::Template> for TemplateSummary {
    fn from(t: rtrt_templates::Template) -> Self {
        Self {
            name: t.name,
            description: t.description,
            source: t.source,
            category: t.category,
            variables: t.variables,
        }
    }
}

#[derive(Debug, Deserialize)]
pub(crate) struct TemplateUpsertRequest {
    name: String,
    #[serde(default)]
    description: String,
    #[serde(default = "default_template_category")]
    category: String,
    #[serde(default)]
    variables: Vec<rtrt_templates::TemplateVariable>,
    #[serde(default)]
    files: Vec<rtrt_templates::TemplateFile>,
    #[serde(default)]
    post_hooks: Vec<String>,
}

impl TemplateUpsertRequest {
    fn try_into_template(
        self,
    ) -> std::result::Result<rtrt_templates::Template, (StatusCode, String)> {
        let template = rtrt_templates::Template {
            name: self.name,
            description: self.description,
            source: rtrt_templates::TemplateSource::Custom,
            category: parse_template_category(&self.category)?,
            variables: self.variables,
            files: self.files,
            post_hooks: self.post_hooks,
        };
        validate_template_manifest(&template)?;
        Ok(template)
    }
}

pub(crate) fn default_template_category() -> String {
    rtrt_templates::TemplateCategory::Development
        .as_str()
        .to_string()
}

pub(crate) fn parse_template_category(
    raw: &str,
) -> std::result::Result<rtrt_templates::TemplateCategory, (StatusCode, String)> {
    match raw.trim().to_ascii_lowercase().as_str() {
        "development" | "scaffold" | "project" | "project-template" | "project-templates"
        | "rust-cli" | "rust-lib" | "rust-axum" | "node-typescript" | "python-uv" | "go-cli"
        | "custom" => Ok(rtrt_templates::TemplateCategory::Development),
        "design" => Ok(rtrt_templates::TemplateCategory::Design),
        "planning" | "doc-chain" | "document-chain" | "document-chains" => {
            Ok(rtrt_templates::TemplateCategory::Planning)
        }
        _ => Err((
            StatusCode::BAD_REQUEST,
            format!("unknown template category: {raw}"),
        )),
    }
}

pub(crate) fn is_builtin_template(name: &str) -> bool {
    rtrt_templates::builtin::ALL
        .iter()
        .any(|template| template.name == name)
}

pub(crate) fn validate_template_name(name: &str) -> std::result::Result<(), (StatusCode, String)> {
    if is_safe_template_slug(name) {
        Ok(())
    } else {
        Err((
            StatusCode::BAD_REQUEST,
            "template name must be a non-empty lowercase slug using letters, numbers, hyphens, or underscores"
                .to_string(),
        ))
    }
}

pub(crate) fn is_safe_template_slug(name: &str) -> bool {
    !name.is_empty()
        && !name.contains('.')
        && !name.contains('/')
        && !name.contains('\\')
        && name
            .chars()
            .all(|ch| ch.is_ascii_lowercase() || ch.is_ascii_digit() || ch == '-' || ch == '_')
}

pub(crate) fn validate_template_manifest(
    template: &rtrt_templates::Template,
) -> std::result::Result<(), (StatusCode, String)> {
    validate_template_name(&template.name)?;
    for variable in &template.variables {
        if variable.name.is_empty() || variable.name.chars().any(char::is_whitespace) {
            return Err((
                StatusCode::BAD_REQUEST,
                format!(
                    "template variable name must be non-empty and contain no spaces: {}",
                    variable.name
                ),
            ));
        }
    }
    for file in &template.files {
        if !is_safe_template_file_path(&file.path) {
            return Err((
                StatusCode::BAD_REQUEST,
                format!(
                    "template file path must be relative and stay inside the scaffold target: {}",
                    file.path
                ),
            ));
        }
    }
    Ok(())
}

pub(crate) fn is_safe_template_file_path(path: &str) -> bool {
    let path_ref = std::path::Path::new(path);
    !path.is_empty()
        && !path.contains('\\')
        && path_ref
            .components()
            .all(|component| matches!(component, std::path::Component::Normal(_)))
}

pub(crate) fn template_write_error_status(err: rtrt_core::Error) -> (StatusCode, String) {
    match err {
        rtrt_core::Error::Config(message) => (StatusCode::BAD_REQUEST, message),
        other => (StatusCode::INTERNAL_SERVER_ERROR, other.to_string()),
    }
}

#[derive(Debug, Deserialize)]
pub(crate) struct ScaffoldRequest {
    template: String,
    target: PathBuf,
    #[serde(default)]
    variables: BTreeMap<String, String>,
    #[serde(default)]
    overwrite: bool,
    #[serde(default)]
    manifest: Option<TemplateUpsertRequest>,
}

#[derive(Debug, Serialize)]
pub(crate) struct ScaffoldResponse {
    files_written: usize,
    root: PathBuf,
    post_hooks: Vec<String>,
}

#[derive(Debug, Serialize)]
pub(crate) struct ScaffoldPreviewResponse {
    root: PathBuf,
    files: Vec<ScaffoldPreviewFile>,
    post_hooks: Vec<String>,
}

#[derive(Debug, Serialize)]
pub(crate) struct ScaffoldPreviewFile {
    path: PathBuf,
    bytes: usize,
    executable: bool,
}

pub(crate) async fn scaffold_preview(
    Json(req): Json<ScaffoldRequest>,
) -> std::result::Result<Json<ScaffoldPreviewResponse>, (StatusCode, String)> {
    let tmpl = if let Some(manifest) = req.manifest {
        manifest.try_into_template()?
    } else {
        rtrt_templates::find(&req.template).ok_or((
            StatusCode::NOT_FOUND,
            format!("template not found: {}", req.template),
        ))?
    };
    let plan = rtrt_templates::render::plan(&tmpl, &req.target, req.variables)
        .map_err(|e| (StatusCode::BAD_REQUEST, e.to_string()))?;
    let files = plan
        .files
        .iter()
        .map(|f| ScaffoldPreviewFile {
            path: f.path.clone(),
            bytes: f.content.len(),
            executable: f.executable,
        })
        .collect();
    Ok(Json(ScaffoldPreviewResponse {
        root: plan.root,
        files,
        post_hooks: plan.post_hooks,
    }))
}

pub(crate) async fn scaffold(
    Json(req): Json<ScaffoldRequest>,
) -> std::result::Result<Json<ScaffoldResponse>, (StatusCode, String)> {
    let tmpl = rtrt_templates::find(&req.template).ok_or((
        StatusCode::NOT_FOUND,
        format!("template not found: {}", req.template),
    ))?;
    let plan = rtrt_templates::render::plan(&tmpl, &req.target, req.variables)
        .map_err(|e| (StatusCode::BAD_REQUEST, e.to_string()))?;
    rtrt_templates::render::write(&plan, req.overwrite)
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
    Ok(Json(ScaffoldResponse {
        files_written: plan.files.len(),
        root: plan.root,
        post_hooks: plan.post_hooks,
    }))
}
